<div class="row">
	<div class="col-xs-12">
		<h1>Chapter VIII.</h1>
		<hr>
		
		<p>Lord Redmond&#8217;s estate lay just beyond Easthaven&#8217;s western border. It was a sprawling expanse of land and building. From the manor house&#8217;s Italianate-style brickwork and rounded roof tiles, to the rooftop cupola that provided ventilation to its many rooms, the elder&#8217;s home hardly resembled its distant neighbors in sensibilities. If there was anything else to be said of the manor, it was that there was no lack of space. It boasted a carriage court and grounds to house the estate&#8217;s five horses as well as a large garden. There was a ballroom, a small library, a grand dining hall and enough rooms to keep a large family (and certainly as many guests) comfortable. Yet despite the full staff of servants and the older couple serving as the house and grounds keepers retained within the mansion&#8217;s walls, it quickly became apparent that Lian Redmond lived alone.</p>
		 
		<p>In the fortnight since Delilah had been hired, there had been no guests and rarely a sign of Lian himself through the days. In fact, it had taken a few days at all before he had even emerged from his quarters before the sunset. Since then, he fell into a habit of appearing in the late afternoons. He expressed little interest in seeking out company, save for the occasional conversation with his older retainers. Otherwise, he seemed more inclined to stroll through the garden, read in library, or, more recently, spend the last few hours before nightfall playing the old piano in the music room.</p>
		
		<p>It was for that reason that Delilah had assumed that she was totally safe from encroaching on the Lord of the Manor&#8217;s peace when she entered the music room at two o&#8217;clock in the afternoon on a mission. For the last two weeks, she had been assisting Alice and two other maids in stripping dust covers and drapes from the furniture and windows of each room of the manor for laundering. She had found that the Lord seemed to be excessively fond of a heavier and darker style of draperies that made for a rather sobering cast over the mood of the place. The ballroom had been scheduled to be next, but Delilah had not failed to notice the increased use of the music room. She had concluded that it made entirely more sense to get a room in use up to scratch.</p>
		
		<p>Ms. Flowers was not empty-handed. This was her third trip to the room, and there was evidence of it to the naked eye. Decorative vases filled with a variety of blooms from the garden had been placed strategically around the room and the piano, and the furnishings had been polished to a shine. There was also, in a certain corner that had been naked of color or ornamentation, a new piece of artwork: a small, colored-pencil sketch of a pair of mated swallows perched on the branches of one of the trees that had spread out over the estate boundary walls. In the corner of the piece, signed with a flourish, were the initials D.F.</p>
		
		<p>At that moment, Delilah was focused with a single-minded intensity on not brushing into any of the more fragile elements of the music room as she navigated with the ladder that she would need to reach the top of the drapes that shrouded the room in a semi-gloom.</p>
		
		<p>To look at the servant, one might almost have mistaken her for a lady of the house, were it not for the practical pair of elbow-length linen gloves that she had adopted to protect her skin while dusting. Her hair had been tamed into a single thick braid that had been coiled neatly into a high updo from which only a few stubborn curls escaped. A simple, high-waisted gown of olive green cotton that fell to her toes, was protected by a lightly patterned, puff-sleeved muslin overdress that served as an apron. It was only a certain feminine vanity that had caused her to use a wisp of olive green organza to shape the bow of material that accented her waist just beneath the rise of her breasts.</p>
		
		<p>Resting the ladder against the wall, the woman reached down to hitch her hemline above her ankles with one hand and began her climb. The first time she had done it, there had been a considerable amount of squawking and nervous chatter — much to Alice&#8217;s amusement. However, after a fortnight of scaling the mansion&#8217;s near twelve-foot internal walls, her confidence had grown so much as for her to try to retrieve the drapes without the retainer&#8217;s assistance. Not that she thought Alice would approve of her efforts to do so alone. Usually, there was at least one other maid to hold the ladder and open arms to catch the falling material, but it was going to the wash anyway. Delilah was certain that a little extra dust for falling directly to the rugs would do no harm. All she had to do was keep her balance. Surely she could manage that.</p>
		
		<p>Perched on the third rung from the top of the ladder, she leaned forward to begin the process of detaching the weight of the window draperies. That she began a soft conversation with herself was the only betrayal that she was not quite as confident as she thought she was about her experiment.</p>
		
		<p>&#8220;Here now, Lilah, you managed to get Mae into her first-day dress, surely you can manage a dusty set of drapes. They&#8217;ve not got nails to scratch your eyes out, have they?&#8221; she murmured. As if in answer to her presumption, a heavy mass of material slumped toward the floor, brushed against the ladder, and caused it to shift slightly as she moved to avoid getting smothered.</p>

		<p>&#8220;Please do not startle,&#8221; came the quiet, masculine voice from the doorway.</p>
		
		<p>Delilah flinched slightly at the utterly unexpected sound of her employer&#8217;s voice, but had enough self awareness to maintain a steady hold of the ladder for the sake of balance. That meant that she had to keep her back to him for those words, despite her desire to turn around and look at the man making what was, today, an untimely appearance while the sun was up.</p>
		
		<p>It was rare enough that Lian made any effort at all to announce his presence, given how silently he was capable of walking. He could slip in and out of a room without being noticed at all. Today, however, as if concerned that any sudden movement on his part might scare her into diving straight off the ladder, he stood still. That concern was probably the first display of a truer facial expression that the elder had made since her arrival: his jaw was tense with a faint grimace as his eyes drifted up the length of the ladder. He did not wait for it to shift a second time before moving forward. It seemed as if he had his attention on little else save for securing her perch. Only once he had a steadying hold on the side rails of the ladder did he appear to be capable of breathing properly again.</p>
		
		<p>Delilah felt safer — and guilty for his securing presence below. It was that sensation of guilt for knowing that she had not followed the expected protocol that made her pick up her chatter again. &#8220;I assure you, Lord Redmond, should you not have come into the room at precisely the hour one most expects you to not be present, that startling would not at all have been a thing to be concerned about,&#8221; she paused a beat and risked shifting on the ladder to peek down at him. &#8220;You have quite ruined the surprise, m&#8217;Lord. This room was meant to be ready before your arrival.&#8221; She stared at him reprovingly. There was another brief pause, and then as if she could not quite help but address the matter, she concluded. &#8220;And it is not at all appropriate for you to be doing a servant&#8217;s task, m&#8217;Lord.&#8221; There, it may not have been her place to say it, but Lord Redmond of all people, should not be standing around supporting ladders for serving girls.</p>
		
		<p>&#8220;I am entirely uncomfortable with your current position,&#8221; he admitted. However, there was little to show for it save for the slight furrow to his brows once he felt he had her safe. Whether it was to preserve her modesty for his angle or if he was concerned with fallen dust entering his eyes, Lian kept his head facing straight on. &#8220;Although I am appreciative for your enthusiasm, I do not think Alice is likely to approve.&#8221; That <em>he</em> did not went unsaid.</p>
		
		<p>He was Delilah&#8217;s employer. That she had that position afforded her a wealth of protection against those first stirrings of music in his blood that would otherwise have incited his claim. For all his effort at keeping her safe from himself, however, he was not as sure that there was much he could do for a girl who seemed inclined to risk cracking her head on his floor.</p>
		
		<p>&#8220;Alice does not approve of many things,&#8221; Delilah offered, unabated. &#8220;I&#8217;m positively surprised she even approved of Henry, to be honest. He&#8217;s quite an interesting fellow, did you know? I can&#8217;t imagine how they found each other.&#8221;</p>
		
		<p>Lian did not seem to be listening. &#8220;I hope you can forgive my preference for holding the ladder for you for the rest of these drapes, Ms. Flowers.&#8221;</p>
		
		<p>&#8220;You are quite forgiven. I suppose I will have to admit to it not being the smartest idea I have ever had to attempt it alone,&#8221; she conceded. Despite her realization that he was doing something that he should not be doing, she was not one to look a gift horse in the mouth, and the drapes had to come down. &#8220;You will have to lend me your arms, my Lord, or at least one of them. The drapes come down in a fury, and I apologize in advance for your jacket.&#8221; He was about to be covered in dust if he did insist on coming to her aid. &#8220;But an honest day&#8217;s work never but made for a good night&#8217;s rest anyway, and you shall enjoy your bath.&#8221;</p>
		
		<p>That she had slipped into a manner of speaking more appropriate for young Edward Morgan Curry, than the Lord Lian Redmond, she may not quite have realized. If anyone were to be asked, they would likely confirm that Delilah Flowers had a way about her that treated all men as equals, whenever she forgot her trained manners. &#8220;You might want to hold your breath&#8230;&#8221;</p>
		
		<p>With that warning, another large chunk of drapery material tumbled towards Lian&#8217;s golden crown, chased by a small billow of dust. It dropped into his outstretched arm almost as if it had no weight to it at all, and the man had but to shift slightly to accommodate the mass of material. &#8220;I can spare the jacket,&#8221; he offered. It was clear that he would not be escaping the room uncovered. Lian&#8217;s pristine black jacket was splotched with gray and brown dust, already. &#8220;And I will be more appreciative for the surprise in a moment, I am sure.&#8221; Or however many moments it took her to have to feet planted safely on the ground.</p>
		
		<p>He had little idea or inclination of exactly what he was supposed to do with the fabric now that it was hanging over his arm. He kept one hand firmly on the ladder&#8217;s rail and returned his second hand to that support so that the drape was tucked against him. The effect would no doubt be a thicker covering of dust up the white collar of his shirt and the red silk tie he wore. At the very least, he seemed unbothered for breathing the cloud in.</p>
		
		<p>When she moved to descend, Lian stepped to the side to allow her room, although she had little choice but for her feet to land on the length of drapery where the Lord allowed it to drag. Delilah, for the fact that she had been above the fray, managed to appear almost fresh when her feet finally found the ground. Her lavender gaze took in the settling dust with a measure of dismay. How silly had she been to attempt at the polishing first! &#8220;Oh, dear&#8230; it has made rather a mess, hasn&#8217;t it?&#8221; She let her eyes travel a slow path around the room. It was a bit of the worse for wear, but enough of what she had done remained to be visible.</p>
		
		<p>The light poured through the window, impeded now only by the heavy curtain of dust that had not yet settled. It would not be long before the sheen was hidden again. Lian noticed her work, however, just as he saw the fresh flowers that she had brought and the new artwork on his wall.
<em>&#8220;Et Voila!&#8230;&#8221;</em> Her attempt at the huzzah for what she had been working on was a little feeble. She noticed that he had realized and was absorbing the changes that she had made to the room, but then her attention landed on Lian and the dust that now covered him. Reflexively, she tried to clean him off. Her white linen glove ran down the jacket arm, and then feathered across his left lapel in a dusting motion, while he tolerated the cleaning in silence. He continued to watch her even as she shook the heavier remnants of dust from her fingers.</p>

	<p>Suddenly aware of how very close to her he was and just how put out her activities must have made him, Delilah reached out to take the drapes from his hold. She needed something to do with her hands.</p>
	
	<p>&#8220;This is a rather embarrassing amount of dust,&#8221; Lian said. &#8220;The mess will no doubt cover your efforts. I should have startled you before you were on the ladder.&#8221; When he had first been aware of those whisperings through his mind that drew him from his quarters.</p>
	
	<p>&#8220;It&#8217;s no more embarrassing than any other great house, I&#8217;d suspect,&#8221; she answered reassuringly. &#8220;There&#8217;s just too much tending to be done, to manage any more than once a year for a grand clean. I&#8217;m so sorry that you&#8217;ve been inconvenienced. I was hoping to have them washed and up again by dinner time.&#8221;</p>

	<p>There was an oversized wicker basket set against the door to the room, and that was where she turned to head, carrying the bundle of material against her chest to drop unceremoniously into its empty mouth. &#8220;Perhaps it can still be managed&#8230;&#8221; Her smile was a coaxing effort as she turned around to face him. &#8220;It would be so very appreciated if you might happen to find yourself occupied with whatever you typically do at this time, and come back at the usual hour&#8230;&#8221; Her tone was at once hopeful for his cooperation, and doubtful for his compliance. He was under no obligation to do anything but exactly what he desired to do in his own home. &#8220;Either way, I was hoping to make the room a little less dreary for you, as you&#8217;ve taken to spending part of your evening here,&#8221; she concluded.</p>
	
	<p>&#8220;It is less dreary,&#8221; Lian confessed, but he did not seem to be speaking only of her work in the room.</p>
	
	<p>She shook out her skirts slightly, removing traces of dust, and then moved back toward the naked window. She stood in the sunlight that was streaming through it and looked out into the garden. &#8220;See? Isn&#8217;t it so much better to let in the light?&#8221;</p>
	
	<p>&#8220;It is&#8230; by far an improvement on its previous state. I keep the rooms I make use of, much too much like a crypt.&#8221;</p>
	
	<p>She leaned forward and released a latch that let part of the window swing open. A gust of warm, late summer afternoon air blew in, chasing away the scent of age and dust and bringing with it the aroma of grass and flowers. She leaned on the sill, took her weight on her hands, and closed her eyes to hold her face up to the sun as she took a deep breath. &#8220;Your home is beautiful, Lord Redmond, but I must confess it to be terribly in need of a bit of life.&#8221; She turned and leaned her hips against the sill. &#8220;If you will pardon my being terribly direct.&#8221;</p>
	
	<p>With her back to the sun, its light teased into her hair, revealing that its color was not nearly so dark as it had first seemed, but rather, was deep and multifaceted with shades of rich browns and caramels. The light made a bit of a halo around her skin, and for a beat or two, one might have been forgiven for comparing her to one of the Greek goddesses of Spring that the styles of the regent&#8217;s England so delighted in.
Lian watched her quietly as if committing the moment to memory. There was a part of him that had some awareness for the intensity of his stare. It did little to keep him from letting his eyes drift in a silent study over the roundness of her face and the shades of earthy warmth that comprised her hair.</p>

	<p>&#8220;Ms. Flowers,&#8221; he began again after a moment. &#8220;You will excuse me for saying that I have yet to experience you be anything but direct. It is not a trait I find you need to ask pardon for.&#8221; It took some effort for him to let his attention turn back to the room. He suddenly had the urge to touch her hair, and he knew all too well where such impulses led. His hands retreated to the safety of his pockets and he bowed gently instead. There was a final twitch at the corner of his mouth, something of a smile as he looked up at her. &#8220;I have no doubt that with time I may regret the sentiment, madam.&#8221;</p>
	
	<p>Lian straightened. &#8220;I shall do as you ask.&#8221; And occupy himself away from her. &#8220;Please do not climb the ladders without someone else present. I am far from above tattling to Alice. She would have my hide as much as yours if she thought I abided such actions.&#8221; He took a step back and leaned forward as if he meant to bow again. However, he stopped when he was bent at eye level to her. &#8220;Good afternoon, Ms. Flowers.&#8221;</p>
	 
	<p>With that, Lian left her to her work.</p>

	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="7-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter VII.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="9-link">Chapter IX. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
