<div class="row">
	<div class="col-xs-12">
		<h1>Chapter XVIII.</h1>
		<hr>

		<p>The new year had come and gone, and Lian arrived every Saturday morning at the castle like clockwork. Whether it was freezing rain or the steady, stubborn accumulation of snow that had arrived with February, his carriage came rolling into the carriage court at 3 o&#8217;clock in the morning on the dot. It was a duty to perform, and while he kept a hold of the pocket watch through the journey, he tucked it into the security of his front breast pocket before facing his queens.</p>
		
		<p>And face them he did.</p>
		
		<p>Each weekend had turned into a perfunctory ritual, accompanied by smiles and flirtations and attention paid to each. It was only Ayla who never came to him except for her own polite greetings before disappearing again into the depths of the castle. Joanna had stop coming to him altogether. It had been in the moment that Dorian&#8217;s feelings had been felt in song and in mind too loudly to ignore, that Lian had determined that he would not touch her again. So it was that when she had come to him like all the others, lost to the fluttering of the flock, his fledgling bride had been afforded only offhand greetings or kisses on the knuckles. It had not taken many weeks before he stopped seeing her at all. He was pleased enough that it was not only one less queen to tend, but that she remained out sight. It meant that he need not turn his mind yet toward determining how to sort out that mess.</p>
		
		<p>Sundays were the days he dreaded; some, admittedly, more than others. Aziza had remained the favored of his queens to visit alone, as he permitted himself the bittersweet betrayal of losing himself to the wildness of her song and the comforts of her body. She had been the safer choice for knowing his true heart, and he had thanks to give for her advice. Sophie too had been granted more time in his sun, and it was not long before Kristiana had been bold enough to find a way to join her.</p>
		
		<p>It had not been an unusual occurrence in the past, that two might earn his favor, in a sequence or together to weave a unique melody or harmonization. Even Efe found a renewed song alongside Aziza one night.</p>
		
		<p>Then there were weekends that he had taken Shar — always at the last moment, and always soon after, he had left to return to the balm that only Delilah&#8217;s presence could provide. He had been no fool to be unaware of exactly who among his brides could be counted as the viper about whom he had been warned. He took Shar in part because the strength of those renewed bonds made her heart harder to hide from him, and in part because the song they made cut as deeply as a knife, and left a black tar on his soul that he thought was well deserved.</p>
		
		<p>It was the week after such an encounter, in the middle of February, that he had arrived again. His attentions were divided among the queens as had become their weekly ritual. Yet he seemed more distant, as if he were not quite making the effort to be fully present for them. It was perhaps that he had not quite shaken off the harsher chords of Shar&#8217;s song, even for the time spent in Delilah&#8217;s company. His Delilah had not been able to draw him from dark humor in the passing days, and worse, he wanted her in all the ways that time with his queens reminded him that he could not or would not take her. The hours spent at the castle felt like a payment for her peace and security that was beginning to wear on him for the falseness of it all. He began to resent his brides — all but one.</p>
		
		<p>It was her company that he climbed the stairs of the castle to seek.</p>
		
		<p>The haunting sound of music drifted out into the hallways of the uppermost floor of the castle; the semi-private quarters of its oldest queen. It was the sound of a harp, and it, more than anything else might have been the indicator that Celia was present.</p>
		
		<p>The icy beauty of a queen lounged at ease in one of the plush chaise lounges that were to be found in the sprawling comforts of the luxury suite. Noelle was nestled into the corner at her feet, her legs tucked under her and her nose in a magazine. Celia&#8217;s room was bare of the types of decorations that might have hinted at who she was, or had been, but there was a single portrait of Lian dressed in the finery of an older time, that held pride of place over her fireplace. Nadine&#8217;s soul flowed out of her fingers, over the strings, singing of sorrow and loss, of love, and of her devotion to what she had left now to call family.</p>
		
		<p>Celia&#8217;s hair, even in the privacy of her lounge was still up in its crown of braids. In this house, Lian alone had been privileged to free it from its bonds to fall to her waist — a sheet of silvery silk. It was almost a sign, outwardly, of the loss of that magic between them that she kept it in its prison now. She lay with a crystal goblet of wine in her hands, eyes closed. Nadine&#8217;s music was a poor substitute for the song in her blood that still thrummed, but the harp&#8217;s notes were a solace outside of the queen&#8217;s head and heart that made her burden of loss easier to bear.</p>
		
		<p>That Lian had become more attentive than he had been in many seasons to his brides, Celia knew, could only be laid at the feet of one. Even now, she turned pensive at the thought of her desert sister. The change had happened after his harmony with her, and she knew that wisdom had prevailed in their union, even more so than the power of their melody. She knew also, what it must mean.</p>
		
		<p>The children had been right. The mortal was different. That Lian went to such extremes to protect her, spoke louder than all of the harmonies that had rippled through her blood on the lonely nights that he had been in the castle and not at her side. He would come. She knew that, and her patience was eternal as it had always been. She had waited for lifetimes, through every new bride and season with the patience of one who knew that in all the ways that mattered, she was one of the few who truly did, to the Lord of the castle. She was sure now that that number had been increased by the sum of one mortal. Celia found herself increasingly curious to know about the flower who had unleashed such a storm onto the coven&#8217;s peace.</p>
		
		<p>The elder queen&#8217;s eyes opened, slowly, and the angle of her head turned slightly toward the door in the side wall of her suite. &#8220; Leave us, children&#8230;&#8221; she said quietly. Another song had stirred, inside, rather than out. It was not often that Lian sought her out in her quarters. For all the years that had passed, she still felt the shift in her core that moved her, drawing her towards his intoxicating presence. There was the quiet hope rising that he had come to her, finally, but it was masked by the neutrality that was prepared to give him only as much as he had come to seek.</p>
		
		<p>The younger females glanced toward the door too, hearing his song as uniquely as Celia did. However, the matriarch held sway in her dominion. Lian was hers if she wanted to claim that right.</p>
		
		<p>The rap of his knuckles against Celia&#8217;s door preceded the moment that it opened. Although Lian&#8217;s mood was far more solemn, the fledglings were offered an affectionate smile and a slight bow at his waist as they heeded their elder queen&#8217;s directive. He stepped aside to allow them to pass before he filled Celia&#8217;s door again. A hand found an anchor on his heart, and the other folded neatly behind his back. &#8220;May I come in?&#8221; For all that he walked as if he had claim and access to every piece of his kingdom and those therein, she alone seemed to be the one he afforded a measure of truer privacy. </p>

		<p>Celia smiled slightly. &#8220;There was a time, Lian, when a door was hardly a barrier enough to keep you out.&#8221; Theirs had been a heady, forbidden love. She the daughter of a Duke, and he the seductive commoner, reaching above his rank. &#8220;Sometimes I miss those days. Come in, please&#8230; you are always welcome to my chambers&#8230;&#8221; And to her comforts. She was not so cold as to not be moved by his attentions when he chose to give them to her. Her steel-grey gaze touched over his expression and posture. &#8220;But I have a feeling that this is not a visit for pleasure&#8230;&#8221; She didn&#8217;t seem embittered or upset by the notion. If anything, she retreated into the safer cocoon of matriarch that she had allowed to crack for the merest of moments, when she had thought he had come for her. Her rise from the chaise was graceful, then she was moving toward a small bar located against a wall at the side of the room.</p>
		
		<p>&#8220;It is <em>always</em> a pleasure, my Lady,&#8221; Lian countered. He smiled, faintly, and drifted deeper into the suite.</p>
		
		<p>&#8220;A drink?&#8221; She looked his way, her gaze assessing him in even so casual a glance. Standing at the side bar she poured a refill for herself from the decanter. </p>
		
		<p>&#8220;Yes, thank you.&#8221;</p>
		
		<p>&#8220;All is well, I hope&#8230;&#8221; But if he was seeking her counsel, it likely was not.</p>
		
		<p>Lian moved to the chaise longue, letting his palm skim over the warmth she had left there. &#8220;I was foolish then,&#8221; he said, although he did not make it immediately clear of what he spoke. The storm-grey of his eyes were upon a thread of silver hair that had caught to the lining of the cushion. &#8220;Your father would have taken my head or worse if he had ever caught me.&#8221; That had been so many centuries ago now; Lian had been so young that that he had not yet been able to stand the sun. Theirs had been an affair of the night and shadows. Celia was as much a star now in their shared eternity, as she had first been in the darkness of the night that he had first seen her. &#8220;I admit, a door is much easier to come through than scaling the ivy of your balcony.&#8221;</p>
		
		<p>As if just the memory had taken her back to the moment, Celia&#8217;s expression softened. She poured a second goblet and paused where she was, to reach long fingers up into her hair. She extracted a pair of long pins. As if they had been waiting for some breath of magic to set them free, silvery ropes tumbled down, unwinding their tension with the weight of gravity until long, loose waves of silk had spilled to the waist of a silver and gold gown she wore. Celia&#8217;s style was uniquely her own, and while it was evident that she had yielded somewhat to the fashion plate of this current age, the waistlines of her gowns tended to be a little lower, elongating her torso and emphasizing her trim waistline. The material of her gown clung lovingly to her hips before falling to the floor, and the deep, almost square collar of the dress spread wide to bare the expanse of her pale shoulders, framing breasts that were just full enough to be present in the subtle swell of cleavage.</p>
		
		<p>Now, as she walked toward him with the goblet extended, she gifted his homage to their origins with the hint of a smile. &#8220;I don&#8217;t know. I might not be averse to such a display of determination from you once more, my Lord. It has been quite some time since the thrill of the chase.&#8221; That she somehow managed to chastise him for making her wait, while raising the subject of the mystery of his present mortal bloom in one sentence, was a testament to the strength of wit and intelligence his first bride still held.</p>
		
		<p>&#8220;That, my Lady,&#8221; Lian began with a twitch of a smile. &#8220;Is because we are old and well beyond thrills&#8230; I should be pleased that you are not altogether averse to my attentions now, for how I&#8217;ve left you.&#8221;</p>
		
		<p>Her lips curved slightly for his admission to their great age. Sometimes she felt every one of those years in her soul, despite the youth that looked out upon her from the mirror.</p>
		
		<p>Lian studied her. Celia had been beautiful before the touch of immortality, but it had not been beauty that had first drawn him to her. He had mistaken the soft strumming of a harp for true music when it had first drifted from her window; but the quickening and flush of life in his soul that had been an almost instantaneous reaction to her song, had spoken to his blood in a deeper way than any instrument ever could. He had not known that it was possible to hear a blood song outside of that eternal bond until that moment. Now he had heard it again from another mortal, in Delilah.</p>
		
		<p>For a moment, he hesitated. It was easier to make claim to the goblet she extended to him, roping his fingers around its stem and tangling them briefly with hers. He found it had not been enough contact, and even as he took the drink, his free hand lifted to secure her wrist. He drew her down onto the chaise with him, if only to tuck her into a lean against his chest. Celia yielded to his embrace, her body fitting against his with the familiarity born of half a millennium of their bond. For a moment, she was content to simply lean against him, nursing at the sampling of wine in her own goblet until her desire to be closer yet, became greater than the want to indulge her thirst for the blood that mingled red in its depths. Gently, she set the goblet aside and turned into him, her lips brushing a kiss to his throat as her silver crown found its rest against his shoulder.</p>
		
		<p>He was uninterested in the blood wine, not with the scent of age like old books and crisp evergreens drifting from her hair where he nosed a touch of a kiss to her temple. He had quieted, tilting his head so that his jaw rested against her crown. &#8220;Whatever am I doing?&#8221;</p>
		
		<p>&#8220;You are trying to do the right thing,&#8221; she murmured, &#8220;In a situation for which there is no right answer, save one.&#8221; A turn of her head touched her lips to his jaw and she brushed a kiss there. &#8220;You are trying to stay alive so that we might all live.&#8221; She rested her head on his shoulders. The entire garden that was his family could not thrive without his song vibrant and alive. They might resist the source of his life, some might even hate what it meant for themselves, but they were all as captive and dependent on Lian finding it, as he. His withering, would mean their own.</p>
		
		<p>&#8220;You make me sound nearly altruistic.&#8221;</p>
		
		<p>&#8220;We can all make a pretense of fighting it, Lian&#8230;&#8221; There was a hint of sadness to her tones. &#8220;But you know&#8230; I know&#8230; we all know, that you cannot watch her wither if her song remains.&#8221; A season could last a lifetime, as her own had. Seventy-five years he had given her. &#8220;If she brings you life, you will make her your bride in the hour that you can no longer fight the battle with time for her body and soul.&#8221; It was not the Elder&#8217;s need for a source of new life that caused suffering, but that pattern that was almost certain to be doomed a repeat. There would have to be a balm for the heartbroken emptiness that was eventually left behind.</p>
		
		<p>Her hand reached up to brush a thumb across his cheek. &#8220;Their pain comes not from the absence of your song&#8230;&#8221; They still had that. &#8220;&#8230;but from the loss of love. Once it has been tasted, eternity is a living death without it.&#8221; She hesitated. What needed to be said stood the risk of disturbing him. &#8220;If they cannot have your love forever, beloved, they must be free to find their own, somewhere.&#8221; She had little care for seeking such a solace, but she had seen more than enough evidence of the potential of other bonds being forged, even within the castle walls. &#8220;If they can find their own happiness, they will no longer begrudge you your own.&#8221;</p>
		
		<p>&#8220;I have not done well by this family,&#8221; Lian murmured. Not in the half-millennia of its existence, and certainly not now that he had turned his attentions on them only as a price to pay. There was no love left for them, save the remnants of an affection that was owed those souls who were his children and once-lovers both. Even that was at risk, now. His arm tightened slightly in its loop around Celia&#8217;s waist. He turned his head to draw from the goblet, and he used it as an excuse to quiet again. He knew that it was the power of the blood ties that kept the family alive, that although his string was the center that kept the tapestry together, more bonds among them could only strengthen the weave. However, all that it was now, seemed to be a tangle held by one cord. The wisdom in her words was evident. He shifted, keeping her close, and lowered his goblet to the floor so he could hold her with both arms.</p>
		
		<p>&#8220;What of you, Celia?&#8221; He asked, quietly. &#8220;Of us? You have waited longer than any. If I could free you from this bond to find a heart that could be only yours, would that be your wish?&#8221; He turned his head to brush a kiss into her hair. &#8220;I will not be wounded by honesty.&#8221;</p>
		
		<p>Celia studied Lian in silence, raising her fingers to touch his face and lips as if she could read his thoughts in their sculpted stillness. There was about her expression that which was the beauty of sadness, laid bare for him to see it. &#8220;Even now, you sell yourself short, Lian&#8230; You have not failed to give me all of your heart. I have everything that you have to give,&#8221; she said quietly. And it was true, he had withheld her nothing. If he had held anything back from any of his brides, it had never been from her. &#8220;Here, is fate&#8217;s cruel weakness&#8230;&#8221; She withdrew her hand and rested it upon her own breast. &#8220;That I cannot fill all of yours&#8230;&#8221; She managed a tired smile. It was a painful admission, but one with which she had made her peace. &#8220;You have been searching for lifetimes for the one who can, who will. She will be your everlasting song.&#8221; And how she had hoped that it could be she.</p>
		
		<p>She reached out then, and rested her hands on his shoulders, cradling the column of his throat. His steady pulse beneath her fingers was a piano sonata that tasted of moonlight, of regret, and of love at one and the same time. &#8220;All I have ever wanted for you Lian was your happiness. It is for this reason, that I have accepted and protected the family that you have built. I, as much as you, lived in the hope that each new bride, would be the one whose song you would hear forever.&#8221; A beat, then, &#8220;Although there are some, should you have had the sense to introduce us before you made your choice, I might have made some effort to save you from yourself.&#8221; That was spoken with her familiar dryness. &#8220;I still hope for that, for you.&#8221; But she had not answered his question, yet. &#8220;I will be honest, and say that I love you, Lian&#8230; I have always loved you. I gave up my life for you, and I gave up your love, for you.&#8221;</p>
		
		<p>She smiled, and this time it was a gentler assurance. &#8220;My one desire is that you should never be alone. The seasons come, and the seasons go. I remain, that when they end, your heart is yet assured a home. We will both know when your unending song has come.&#8221; And it would be then, that she would make her greatest sacrifice.</p>
		
		<p>&#8220;Our bond, weaker though it is, is all that I have left to give,&#8221; It was her gift, and his anchor, though it had cost her everything. &#8220;I cannot imagine a life without your song, or a life lived in the fear that you become lost without one to fill at least part of the silence.&#8221; She raised a hand to silence any protest that might come. &#8220;I expect nothing more than what you have to give, Lian, and I will be your champion to find your eternal song. Whatever you need of me, you have but to ask. But do not, I ask, request that I lose your song, or that I recuse you of my own. My answer will be no.&#8221; Her gray eyes rested on his storm-cast blue. &#8220;When you are free&#8230; so will I be.&#8221;</p>
		
		<p>Lian knew in those moments, in the face of her sacrifice, that he loved her too; more than he could ever profess. That he could not find his eternity in her song had been his greatest failure. His Celia, with hair like starlight and eyes like steel. He lifted his hand to steal one of hers from his shoulder. For a moment, he seemed content to remain there, so that his thumbs could brush over the paleness of her knuckles. He had stolen her hold before, left kisses on the softness of her skin, and had known even then that he might never let her go. He lifted her hand to his lips then, to breathe her in. Lian&#8217;s kiss lingered on her wrist, where he could feel her life flowing through her.</p>
		
		<p>Celia yielded her hands to the gentleness of his hold and the exploration of his kisses, her eyes fixed on him. How many times, in how many centuries had it been thus? The seductive whisper of anticipation rose in her blood for the promise of the song and pleasure that he could bring. She had always been his to command. Whether his need for her music arose in the throes of their passions, or in the rest of her comfort, she had never failed to answer his call and the ache in her heart for the sake of the weight of the subject of their conversation could only be eased now, by the balm of his song.</p>
		
		<p>He released her just as her song had lifted to greet him. It was almost jarring. Celia could not help the shuddering sigh that escaped her as she tried to rein her desire in. He had not come to her yet. She closed her eyes against the thought as he rested his head against her crown. They fluttered open once again amid a slight disorientation, at the brush of his fingers against her jaw. His wrist was held up in offering before her. She felt the weight of his closeness and the blossoming realization of why he had not chosen to partake of her music. He was gifting her his own.</p>
		
		<p>Celia let her fingers curl over her bond&#8217;s, the slight pressure given in acknowledgment of the favor bestowed. For a moment, she let herself get lost in his very offering; in the swell of his song reaching out to her, louder than she had heard it in what seemed an eternity. That this was his answer spoke more loudly than any words that he could have spoken. It was an invitation to be drawn to the depths of himself that had not been explored since the night of her turning. Lian had always taken freely of his bonds, their blood, and their songs his treasure and feast. In turn, a pleasure that broke the body and the mind of his favored had been the price paid and received for an eternity without his heart. Or his blood. He never gave his blood.</p>
		
		<p>It had been over five hundred years since she had tasted his life. They had never spoken of why it was that way. Although she had dreamed of taking of him again, she had never dared to try or to ask if he would permit it. It had been her private yearning, to know him utterly from the inside out, as he knew her. That she did not, she knew in some innate way, was part of the reason that she would never complete him. A part of her understood that it was perhaps self-preservation that had made him choose that path, even if it created one-way relationships. But now, he was offering her access, and it puzzled her. Why now, when it seemed she was so close to losing him to a new mystery of a song, did she feel like she was finally being invited to fill yet more of him? </p>
		
		<p>It had to be the girl, the Delilah Flowers whose name had been whispered throughout the castle. He was being in this moment, more selfless, and more human than he had been in centuries. He was feeling; feeling enough to invite her into the secrets of his deepest soul.</p>
		
		<p>It was then, that Celia knew that she would be as bonded to Lian&#8217;s mortal, as he might become. Delilah Flowers had given Celia a gift that the servant girl might never know of, or understand. She had given the older woman access to an unclaimed piece of Lian&#8217;s heart, where the younger was awakening his soul. Something twisted inside of her, almost painfully in joy. &#8220;I will always choose you.&#8221; It was a sworn covenant, breathed over his skin before she lowered her head and slid her fangs into his veins. The flow of his life song spilled onto her tongue. She would not be able to help the soft sound of pleasure and want that escaped her lips around the wound. He was everything that she had dreamed he would be. Inside of her, his song exploded at a ferocity and volume that she had never experienced, singing a conflicted crescendo that sought out and seduced her own music to a riotous answer.</p>
		
		<p>Lian flowed into her, blood and heart and song, the drumming of his heartbeat synching with the tempo of her life. He closed his eyes, inhaled the scent of her hair, and sighed. His arm shifted from the loop of a hold around her if only so that his freed fingers could thread through the curtain of silver that covered him. Celia, Celia. Her name was a sweeter note than it had been, in the melody of his soul. His fingers trailed through her hair, brushing the tresses back from the slender column of her throat, and he lowered his head to her pulse. Theirs were the layers upon layers of piano and harp that drifted through the bonds of blood shared by those within the castle.</p>

	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="17-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter XVII.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="19-link">Chapter XIX. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
