<div class="row">
	<div class="col-xs-12">
		<h1>Chapter XI.</h1>
		<hr>

		<p><em>&#8220;Release the hounds!&#8221;</em></p>
		
		<p>The call echoed over the yard, preceding a rush of chaos as forty harrier hounds and terriers were freed from their kennels. With tails wagging, they howled and barked, joined by some of the guests. The dogs swooped between feet and around skirts, snapping up offerings of bread, meat, and cheese that were tossed their way. If there had ever been a sign for a final call to mount one&#8217;s horse, that was it.</p>
		
		<p>Colonel Cunningham sat tall upon his mount, no small feat for a man of near seventy years who was more often bent over his cane. Dressed in his red coat and a tricorn hat from a bygone war, he managed to be even louder than the dogs, calling the riders to attention. There had been no alcohol served in Dorian&#8217;s yard, but the clear flush in the Colonel&#8217;s cheeks was indicative that he had found a way to imbibe. He lifted his bugle and the triumphant blaring was the signal that the games were on. The hounds were bounding in droves toward the feet of his mount, and it was a smart swipe of his crop that urged the white onward.</p>
		
		<p>A parade of riders followed. Some younger men (Eden&#8217;s voice included) hooted to the young women who would be staying behind. Their horses followed the pack at a steady trot, off the paved paths, beyond the tree line and out into the open fields. Signs abounded of the efforts of the workers who had been out before the sun had risen, plugging fox holes to force the creatures into seeking shelter above ground. Trampled mounds of grass attracted the hounds, only for the Colonel to lead them away with thundering commands. Two young gentlemen with the honor of serving as whippers-in were quick to step their mounts in and rein the pack back together as needed.</p>
		
		<p>The party moved between coverts with the hounds barreling in so that only their tails could be seen over the thick underbrush. The Colonel remained close to watch the rustling leaves with rheumatic eyes. It was at his call whether the hounds were recast to the next covert and withering stares found any young aristocrat he thought fell out of line.</p>
		
		<p>Lian sat upon his black stallion, abreast of Delilah. He had not exaggerated about his intention to keep close; even if that meant that they were at the back of the pack. His attention, however, remained divided between the woman mounted upon the strawberry roan at his side, and the position of his brides further ahead. Ayla, he knew, cared for little but the ride and the opportunity to send her blue into a charge. It was Shar that he felt the concern for, all too aware of the dark ripple resonating through his blood. For his efforts to try to relax, Lord Redmond sat almost stiffly upon his mount.</p>
		
		<p>&#8220;You have hunted before,&#8221; he offered, mostly for the sake of conversation and to relieve Ms. Delilah Flowers of any impression that he was not enjoying himself. The pack was on the move again, and he flicked his reigns to coax his stallion into following. &#8220;I should have asked how comfortable you were with the jumps.&#8221; Before assuming she would wish to ride at all. &#8220;Rouge is an excellent mount. Although I admit I am at a loss for how one manages to remain anchored to a side saddle.&#8221; He smiled, faintly. &#8220;It is more skill than I can claim.&#8221;</p>
		
		<p>Delilah didn&#8217;t know either, frankly. The side saddle was the worst possible contraption. She was always sore in her abdomen and sides for days after for the effort of using her core to stay planted. Fortunately, the nuances of staying centered and balanced came back like a familiar old friend once a rhythm was found. Next to Lian, she urged her roan to stretch out into a wider stride and threw her back and laughed. &#8220;Well now you have removed all excuses for not being the more skillful with his mount!&#8221; she teased, raising her voice slightly to be heard over the wind as she addressed that latter statement. Distracted by a rapidly approaching low hedge, she leaned forward slightly over her mare&#8217;s neck and urged her into picking up the pace needed to make the jump in stride. Her form was perfect for the jump, and she turned her head on safe landing, her face aglow for the rush of the moment and the wind against her cheeks.</p>
		
		<p>&#8220;And yes, one hunt, the year I came out. I was invited by a suitor whose mamma was quite horrified by the fact that he had done so.&#8221; Her answer was offered dryly as she slowed the horse down to a more even pace. &#8220;I feel comfortable enough with the jumps, provided I&#8217;m paying attention&#8230;&#8221; Saying it made her turn her gaze toward the pack again. &#8220;They are hiding well today. Good for them!&#8221; It might not be the fashionable thing to wish the prey good fortune, but Delilah had a tender heart.</p>
		
		<p>A much harder heart leaned over her own sorrel mount, riding the mare hard as if that energy could replace the one she could feel coiling inside her like a serpent about to strike. She could feel Lian&#8217;s correction singing in her blood, and like a rebellious teenager whose control was tenuous at best, it was as if she were trying to outpace his influence. If she could get him to shut up in her blood, maybe she could find a moment to think with her own will without that seductive bittersweet tune trying to redirect her into controllable paths. Shar hated his ability to steal her will from her. That he rarely, if ever, exercised the option made no difference. Just knowing that she was not truly free made her feel as hopelessly trapped as today&#8217;s fox would be. She barely paid attention to the chase. In the back of her mind, she could hear the baying of the dogs, the cheerful noise of the chase, but none of it was as loud as the warning she heard singing in her blood.</p>
		
		<p>&#8220;To the blazes with you Lian&#8230;&#8221; she hissed it into the air, over her mare&#8217;s flickering ear. &#8220;And your new bitch!&#8221; The insult to them all would not be tolerated. He was heartless, selfish, and dead. A parasite who could only live on the life of others. And what was the best way to destroy a parasite, but to destroy everything that it could use to sustain itself to live? She could feel her fangs elongating between her lips, and willed herself into a more controlled state. &#8220;Careful. Careful,&#8221; she murmured aloud. There was no one near enough to see the glittering, almost fevered heat of her aquamarine gaze. It could be done. It could be managed if she played her cards right. She would have to learn to hide, to take the stupid bitch&#8217;s advice and learn to mask her darkest passions. One by one, until only Death remained for him to suck on its teat. Then maybe, she could finally find her rest.</p>
		
		<p>He had been so close. She had felt it in his inertia, his apathy. The right nudge and perhaps he would have done the deed himself. But now, he was alive again, and it was because of her: Delilah Flowers, if the whore had been formally presented by her true name. It would make Shar&#8217;s work all the harder, to destroy his song forever. The leech had found a new source of blood for life, so that was where she must begin. Shar was almost at the front of the chase, in the thick of the stampeding herd. Slowly she began to reduce her pace so that she began falling back toward the center of the chase.</p>
		
		<p>&#8220;Riding hard as always Shar,&#8221; Dorian&#8217;s drawl carried the polite neutrality that he tended to carry for Lian&#8217;s older bride. He had not been fond of the pairing to begin with and had watched the bond weaken with a strange knowing that there would be a high price for the mistake that Lian had made with this one. Centuries of catty behavior had been the worst of it, and a certain darker influence on Lian in some moods that Dorian could not like, but to date, she had endured her sentence as had they all with whatever stratagems she had designed to cope.</p>
		
		<p>This time was different. Call it intuition or premonition, or the result of Eden&#8217;s flat dismissal of the idea of another sister, but Dorian knew that if Lian attempted to take another bride, chaos would ensue. It put Lord Vaughn in the most untenable situation of deciding between Lian&#8217;s happiness and&#8230; and what? The happiness of his family? To whom did he bear more allegiance? For all that this new pretty caused Lian some temporary joy, how long would it be before they were in the dirge boat again? He could feel a measure of sympathy for the brides. More than a measure. He loved one who had been sacrificed on its altar. It made too much of a mess to be worth thinking about. He drove his heel into the rib of his stallion. &#8220;Sometimes a gentler touch will still get you where you want to go.&#8221; That was for Shar again, as he drove forward into the knot of horseflesh.</p>
		
		<p>The first of the hounds loosed a cry, its tail thrown up in the air. It was not a moment after that the rest of the pack gave tongue. The Colonel lifted his bugle, and with that long, resounding call, the chase was on. There was no sign of the quarry at first, but dogs followed the scent and were in turn followed by the galloping horses. The bellowing howls and barks that erupted from the pack as they threw themselves into the underbrush were accented by a startled, higher pitch of a yip. The fox leapt from the covert, its bush of a tail high as it fled.</p>
		
		<p>The chase was on with intent, now, and the distance between those who hunted in earnest and those who were just along for the gallop increased; two distinct groups became evident. Lord Vaughn was in the thick of things, keeping up with the best of the riders at the front of the chase. Ayla, likewise, was a dark shadow near the front of the charge. It would not be her honor to ride in at the death of the fox, but it did not stop her from pushing her Horse to ride ever faster.</p>
		
		<p>Permission had been granted by the landowners to use their grounds for the hunt, but they no doubt had higher expectations than the herd of horses that came galloping through their yards and leaping over their fences. The Colonel led the hunt through gardens without reservations, chasing the fox as it darted to and fro. There would be no shelter for it, of course. It was only a matter of time before the dogs caught the creature. It threw itself beneath a fence that separated a yard from the field, a splotch of red against the green openness of the lands. The riders followed.</p>
		
		<p>Eden was somewhere near the middle of the winding charge of horses, her top hat lost to the wind the moment their pace had picked up. She followed well for a while, up the hills and winding around the coverts. It was the moment that the fox had dove for cover into the brush and the dogs and horses chased after that she was bounced straight from her saddle into a roll through the leaves. Lian&#8217;s curse was all too audible the moment he caught sight of that tumbling body, and despite his promise to stay close, he drew his reigns in turning his stallion to cut a path to where the girl had landed.</p>
		
		<p>Lilah had been focused on a jump when she heard Lian&#8217;s expletive. Wise enough to avoid distraction at a moment when focus was critical, she maintained her form until all four hooves were on the earth again and then she was slowing the mare to a loping gallop that was just slow enough that she could twist in her saddle to look back the way that she had come. </p>
			
		<p>&#8220;Are you alright?&#8221; Lian asked, drawing the mount to a stop alongside the fallen girl.</p>
		
		<p>&#8220;Uh.&#8221; Eden straightened, smacking her hands against her britches. &#8220;Yeah. I&#8217;m shyte at this. Where&#8217;d the horse go?&#8221;</p>
		
		<p>&#8220;Riding ahead without you.&#8221;</p>
		
		<p>&#8220;Well, bugger. This is a stupid bloody sport. Looks like your Lady might be runnin&#8217; ahead too.&#8221; Eden frowned, leaning forward as if to catch her breath, before she was throwing her hand back to the horses. &#8220;I&#8217;m alright, I&#8217;ll just walk back. What a cock-up.&#8221;</p>
		
		<p>"You are not walking."</p>
		
		<p>&#8220;Well, of course, <em>father,&#8221;</em> Eden grunted. That was the extent of her argument. Taking Lian&#8217;s hand, she managed to swing herself behind him, wrapping her arms around his middle. &#8220;This is embarassin&#8217;.&#8221;</p>
		
		<p>&#8220;Be happy you chose not to wear a dress.&#8221;</p>
		
		<p>&#8220;Yeah, but we look like a couple of mollies. I got a lady waitin&#8217; who&#8217;s pretty sure I&#8217;m going to marry her. Speakin&#8217; of marryin&#8217;&#8230; I really don&#8217;t want a new sister. Have you thought about brothers? Or, sisters who prefer the game of flats?&#8221;</p>
		
		<p>&#8220;Eden, as impressed as I am with your ability to turn a fall to your advantage, this is rather not the time.&#8221;</p>
		
		<p>At the rear of the group and still moving forward, Lilah raised a single arm to wave in the direction of the blonde who she could make out talking to the unhorsed youth. How kind of him to stop for a stranger. &#8220;Lord Redmond! Here!&#8221; She used the politer moniker to signal her location, in the event that anyone took notice of her call to him.</p>
		
		<p>Someone heard. Drifting even further to the back of the leisure riders, Shar flicked a blue-eyed gaze in the direction that her bond&#8217;s name had been shouted. Her smile was grim and did not reach her eyes. &#8220;Silly Eden&#8230;&#8221; Her murmur was almost a purr of satisfaction. The guardian was away from his ward. Shar could not have planned it more perfectly if she had tried.</p>
		
		<p>She only had minutes and she would have to make sure that she was nowhere near the events that were about to unfold — whatever their outcome. The elder slowed her horse just enough that she was two horse lengths ahead of prey. She never looked back, never gave any indication that she was aware of or interested in the presence of the woman who continued to wave to draw attention. Shar didn&#8217;t need to look at what she had already seen to reach her target. A flicker of concentration and focus, and the picture or horse and rider were there in her mind. She needed little more than that.</p>
		
		<p>If there was one thing Shar could be thankful for in her eternal sentence, it was the gift of fire that she had been nursing and growing. She was too young yet for it to have reached full maturity, but she still found a certain, beautiful irony that Lian&#8217;s curse had gifted her with the power to channel her bitter venom into a very real and tangible flame. Unfortunately for the strawberry roan, the mare happened to be carrying the current object of Shar&#8217;s venom for a rider.</p>
		
		<p>In the middle of a galloping stride, and while Delilah was sitting higher in her saddle to wave, the mare screamed and lifted her two forelegs off the earth in a jarring rear as she twisted toward the left. Lilah&#8217;s body, still moving forward for the trajectory of the gallop, slammed into the column of Rouge&#8217;s neck and head, eliciting a cry of distress from her rider. Then as her skirts began to slide over the saddle toward the mare&#8217;s rear, the roan was on four legs again and racing in a full panic away from the body of the hunt, fleeing the terrible burn and smell of scorched flesh rising from its own chest.</p>
		
		<p>&#8220;Whoa, Rouge! Whoaaa!&#8221; Lilah&#8217;s cried desperately. She had lost control of the reins and was laid out sideways across the neck of the mare in her bolting frenzy. Lilah knotted her fingers in the horse&#8217;s mane and hung on for her life. With each stride, she could feel herself slipping, shifting, and losing her sense of balance. She couldn&#8217;t hold on. &#8220;Oh&#8230; bugger.&#8221; It was a soft breath of utterly understated despair that escaped her as her fingers gave way, and she fell.</p>
		
		<p>It would not have been so terrible a fall had it not been for the fact that the rear hoof of the roan clipped Delilah&#8217;s temple as the mare barely avoided trampling her. The impact stunned the woman. It was not an assuring, rolling tumble upon landing that might have been viewed by an onlooker, but the sight of Ms. Delilah Flower&#8217;s unresponsive body hitting the earth, as heavily as a sack of potatoes, and lying quite still. Almost immediately, red blood swelled to the surface of her split crown and began to stream steadily over her cheek and jaw, dripping to soak into the earth beneath her.</p>
		
		<p>Shar neither stopped nor looked back. From the moment that the roan screamed she dived forward over the sorrel&#8217;s neck and urged her forward, making up ground through the leisure riders to rejoin the chase. The only evidence of her participation was the thin ghost of a smile that curved her lips. All was suddenly well with her afternoon again.</p>
		
		<p>Lian saw only the moment that Delilah&#8217;s mount took off like a shot, and there was no warning as he pressed his own horse into a barreling gallop. Eden cursed against his back. She could hear the sudden rise of sharp violin chords resonating in his blood. Eden&#8217;s brows furrowed, her arms squeezing against him in subconscious response to the jarring layers of sound. He was&#8230; worried? Bouncing painfully against the black&#8217;s rump, Eden lifted her head to look over his shoulder to the place where that black and blue clad Lady had landed. She almost fell again for the rapidness with which Lian pulled his stallion to a stop. The mount reared and whinnied his complaints, but the moment four hooves were on the ground, Lian had dismounted.</p>
		
		<p>&#8220;She&#8217;ll be alright, probably,&#8221; Eden slid down after her sire. She was the one standing over Lian&#8217;s shoulder as he dropped into a crouch alongside his Lady to carefully turn her. That was the moment that she caught sight of the wound.</p> 
		
		<p>Eden&#8217;s frown deepened, and the garnet color of her eyes flashed a brighter red. She turned her head, burrowing her face against her collar as if to protect herself from the scent. &#8220;What&#8217;s <em>wrong</em> with her?&#8221; The smell was making her veins burn and her throat tighten. It was worse an effect than any bleeder of a wound on a mortal she had ever witnessed. Throwing her hands up, Eden retreated to the safety of the black stallion. &#8220;It&#8217;s fine, it&#8217;s&#8230; I&#8217;ve seen people crack their heads worse, just&#8230; let me get a horse, I can&#8217;t ride around with her. Just. Ugh. I&#8217;ll be right back.&#8221;</p>
		
		<p>Lian was not listening. The silk cravat was loosened from his throat, and he used it to apply pressure against the bleeding wound. &#8220;Delilah,&#8221; he spoke quietly, his voice almost lost beneath the sound of Eden leading his stallion to chase one of the riderless mounts. He slipped his free hand into his jacket and began to unbutton it. The other remained cradled against her face to keep pressure against her wound. &#8220;This was a little more of an adventure than I had anticipated for you today. What do you think?&#8221; It was a quiet effort to rouse her, to at least get her to speak, though the furrow of his expression would do little to hide the concern. &#8220;You held on like a devil though, I daresay&#8230; Come along then&#8230;&#8221; He shrugged from his coat, and clumsily folded a makeshift pillow for her. Not that an open field made for much of a comfortable bed, but he knew something of wounded humans from his centuries. It was better not to move them until one could be sure their head would not roll off.</p>
		
		<p>For a few moments, there was only the sound of the wind as it moved through the wild grasses and the distant baying of the hounds as they closed in on their mark. Then, beneath it all, there came a soft, shuddering intake of a breath, followed by a slow exhale from the woman. After a hesitant flutter of dark eyelashes, Delilah&#8217;s lids broke open; her lavender gaze was darker for the larger dilation of her pupils. For a few beats she looked into Lian&#8217;s face, with a strange, sober studiousness, and then her tongue escaped to touch some moisture to pink lips in preparation for the effort of talking. &#8220;Other &#8230;ways&#8230;&#8221; she managed that much before she paused. His face was so close. She lifted a hand weakly to touch his jaw, &#8220;to sweep&#8230;&#8221; She couldn&#8217;t get the rest out, just yet, but at least she spoke at all. &#8220;Head&#8230; hurts.&#8221; Her brow furrowed slightly, as if she were trying to determine what exactly it was about her head that was hurting.</p>
		
		<p>Lian turned his head into her touch and he permitted himself the soft brush of his lips against her palm. &#8220;Yes. I do not know if it was from the fall or the horse.&#8221; He had the jacket slipped beneath her head and shoulders, fully. &#8220;There you are. You saw that young one I picked up? She is going to fetch a horse, but I admit I am not quite sure that we should move you. I will send her for a doctor.&#8221; He leaned in, holding her hand. &#8220;She was not even riding sidesaddle and she fell. I think you the better horsewoman. Is it only your head?&#8221;</p>
		
		<p>Her answer was a slightly dazed and distracted look at her hand where he had kissed her. She felt it wrap around her heart through the mist of pain and the fog of disorientation. Her fingers curled in as if she could capture the sensation and hold in there forever. It was their first kiss. Somehow, awareness of that fact filtered into her consciousness. A real kiss. She tested her ability to move. First, she moved her folded fist to rest it against her breasts, and then her other hand followed suit, so that she laid all too much in the position of a corpse. Delilah closed her eyes for a moment, focusing her senses of each limb of her body, one after the other, searching out warning signs of damage. Small movements under her skirts, tested her ability to move her lower limbs and they responded. &#8220;Just&#8230; sore, I think,&#8221; she murmured. Although her voice was raspy, it was getting easier to keep her words together and to think.</p>
		
		<p>&#8220;That&#8230; makes me feel a little less as if my heart is going to quit,&#8221; Lian exhaled, and he rewarded her with a faint smile. His expression managed to be no less concerned, despite the curve on his lips. The hand not currently occupied keeping the silk puff against her head shifted to offer light brushes against her cheek and jaw. He raised his head, even before the sound of hooves approached.</p>

		<p>&#8220;Hey,&#8221; That was a distinctly feminine voice from the male-dressed rider. &#8220;She&#8217;s alright?&#8221; Not eaten at least. Eden still couldn&#8217;t look at her.</p>
		
		<p>&#8220;I believe she will be, but I cannot move her. There should be a doctor back at Dorian&#8217;s.&#8221;</p>
		
		<p>&#8220;Yeah, sure. The best rider of the group &#8217;ought to go fetch him.&#8221; Eden released the reins to leave Lian his black. The horse she was mounted upon was a bay, and not at all the one she had begun the hunt with. Better to take her chances with one that hadn&#8217;t bloody well tossed her. She turned to ride back to the mansion, leaving the Lord and his Lady alone.</p>
		
		<p>&#8220;I shall endeavor to be entertaining, Ms. Flowers, as I do think you will need to stay awake with me for a moment more.&#8221;
Delilah smiled faintly, and when she spoke, it was slowly, but with more clarity than she had been able to muster, &#8220;My life&#8230; is in your hands, m&#8217;Lord.&#8221;</p>

	<p>&#8220;That is a most dangerous place for it to be, Ms. Flowers.&#8221;</p>
	
	<p>She could not help the lingering of her eyes on his features. With the sun almost directly overhead now, he shone, golden as he hovered over her. &#8220;You look&#8230; like an angel. I&#8217;m sorry&#8230;&#8221; for ruining his day with doctors and blood. "She just&#8230; ran." She still didn&#8217;t know why the horse had bolted.</p>
	
	<p>&#8220;Oh, Delilah&#8230; I am anything but an angel.&#8221; For a moment, he seemed almost saddened for the words, but his gentler smile returned within the next heartbeat. &#8220;I am, however, pleased that you do not seem to be quite so injured as I imagined when you fell. You need not apologize. Besides&#8230; I do think this means you will have several days off.&#8221; For that singular condition she held him to. He remained in crouched at her side, stroking her hair and speaking softly even when the doctor arrived.</p>


	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="10-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter X.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="12-link">Chapter XII. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
