<div class="row">
	<div class="col-xs-12">
		<h1>Chapter XV.</h1>
		<hr>
		
		<p>Hours later, and not long past the climb of the rising sun over the horizon, Delilah was cold and feeling close to tears for her exhaustion. She had not thought there was any water left in her body, but the several hours that had passed since she had started walking in the night had proven to her otherwise. Her toes had begun to feel numb in her winter boots; likely because they had been crafted more for fashionable garden walks than for trudging along a coach road. Even though the fur lining of her hunter-green pelisse was keeping her warm from her knees to her throat, the bite of the wind of early winter around calves covered only by the cream-colored linen of her walking dress seemed to send a chill directly up her spine to settle on her heavy heart. It was as if she had a block of ice located in the part of her chest where the beat of that organ should be.</p>
		
		<p>The woman shifted the weight of her travel bag from one gloved hand to the other for the hundredth time and tried to ignore the soreness that she knew was a blister forming. Gusts of wind tugged at the brown, hooded traveler&#8217;s cloak that hid her bonnet and most of her features and form from the road. The protection of her privacy was important. A woman alone, walking by foot on the open road was not a sight to which one was accustomed, and already since the dawn she had had to fend off the occupants of two carriages who had been both drunk from a night of revels and of the impression that she was a female of less than reputable status.</p>
		
		<p>That they had thought to be chivalrous and rescue her from her evident plight, and that one had proposed marriage on the spot in a grandiose flood of drunken generosity, should have tickled her typically ready sense of the ridiculous. Instead, she had stood there in the early morning light, looking down at her would-be swain on bended knee, and had broken down into another bout of those incessantly dreadful tears. She was tired of weeping, had believed herself finally drained of the ability to feel, but now, as the sun rose higher in the sky of a new day that should have been the first day of a courtship beyond the confines of her sick bed, her not quite frozen heart betrayed her again.</p>
		
		<p>Delilah didn&#8217;t bother to wipe the tears that rolled down over the wind flushed redness of one cheek. She kept walking.</p>
		
		<p>The sound of approaching hooves was, to Miss Delilah Flowers&#8217; misfortune, both evidence of a single rider and coming from exactly the direction that she had been walking away from. It was no chivalrous drunkard that rode up alongside her. Lian Redmond was in the same attire that he had left her room in on the previous night, and the black stallion he rode was still strapped in the carriage tacks. If he was pleased at all to have found her, or at all guilty for what had transpired, the Lord&#8217;s expression was carefully neutral.</p>
		
		<p>&#8220;Ms. Flowers, if your intention was to leave a letter and flee in the middle of the night to spare me the pillow you might have thrown at my head, I do believe this week has more than proven that I am sturdy enough to withstand it.&#8221; Lian swung his leg over his black in a smooth dismount. He made no effort to block her path or stop her. Instead, he quite readily slowed his long-legged walking pace to fall in at her side, leading his mount by the reins.</p>
		
		<p>The anxiety that Delilah had felt rising for the sound an approaching horseman was replaced almost immediately upon hearing that voice, with a lurch in the pit of her stomach that was terribly close to a dry heave. The swelling rise of her distress caused her heart to race and her palms to sweat a cold moisture inside her gloves. He was here. He had followed her, the bastard. Of all the gall! She found that she could not find the words to speak for several moments and so she busied herself with placing one foot in front of the other as she had all night.</p>
		
		<p>&#8220;You do realize, of course,&#8221; Lian offered, &#8220;Even baby killers are permitted a day in court to defend themselves?&#8221;</p>
		
		<p>&#8220;You have little need of a courtroom, Lord Redmond,&#8221; she said huskily. &#8220;What crime have you committed? And I will thank you to leave the mistakes of the past where they rightfully belong.&#8221; She didn&#8217;t want to think about the last week. Didn&#8217;t want to think about his tender concerns and their playful interaction. It had been a tapestry of lies. So badly did she want to speak further, to sting him with the whip of her tongue, but he did not deserve her breath. She had not yet even turned to look his way, and for his efforts at conversation he was talking to the profile of a shadowing hood.</p>
		
		<p>&#8220;Please go away. Leave me alone.&#8221; That plea, her heart would not allow to go unspoken. His presence was a torment of lost happiness.</p>
		
		<p>&#8220;No. I am afraid it is a lovely morning for a walk, and I am inclined to continue in this direction with you.&#8221;</p>
		
		<p>&#8220;It seems you have been inclined to many things where I have been concerned, Lord Redmond. Please yourself,&#8221; she said evenly. He was going to, anyway.</p>
		
		<p>Delilah continued her tramping walk, stubbornly ignoring the man walking at her side. The telling burn of muscle exhaustion in her bag carrying hand betrayed that it was time to make the shift again, and she did, taking a side step or two to put distance between herself and the male, now that she was no longer protected by the bulk of the bag between them. He had no right to be demanding, to expect her to come running to heel because she was his servant. That was no longer the case.</p>
		
		<p>&#8220;Your manners betray you, my Lord. I am no longer in your employ. You have no right to impose your attentions upon me, and contrary to popular opinion,&#8221; Her feet stopped moving, and finally, he had her tear stained and red-rimmed lavender gaze fixed on his features. &#8220;&#8230;I &#8230;am not&#8230; a whore.&#8221; She all but bit the word out between clenched teeth. Her bruised lip betrayed her with a faint tremble before she firmed it up. &#8220;So, when a lady asks you to Leave. Her. Alone. You bloody well Leave. Her. Alone!&#8221;</p>
		
		<p>Delilah accompanied that last outcry with an almost violent swing of her travel bag, striking out at the source of her pain with the only weapon in her armory.</p>
		
		<p>Lian did not duck away from the swing, though the black nickered and stomped his hooves in protest. She hit what felt like a solid wall, with only the pinch of his brows to betray that he had felt anything for it. She found that she was unable to pull it back however; though when his hand had caught hold of the strap, she had not seen. &#8220;No,&#8221; he said again. &#8220;You will listen because it matters to me that you hear it&#8230; Stop your ears if you are so desperate not to hear me.&#8221; He twisted his wrist to draw the bag in closer, reeling Delilah in along with it. &#8220;What you do after is your business. You have lived with me for months, Delilah. That it was not worth a moment for you to hear what I may have to say was quite a sharper knife than I thought I could still feel.&#8221; He made a sound almost a scoff, but the irritation did not seem to be directed at her. Rather, he lifted his free hand to rub the space between his brows.</p>
		
		<p>Delilah tried to stop the wellspring of tears that threatened and failed. The shimmer in her gaze that she tried to blink away became a trickle of tears. How dare he? How dare he try to make her into the guilty one? But she had not stopped her ears, and she was not trying to pull away.</p>
		
		<p>&#8220;What answer, Lian&#8230;&#8221; her voice broke over his name. &#8220;What answer could you possibly have for a wife&#8230;&#8221; It broke, even more harshly over that word. &#8220;I look just like her. I was in her room! Can you deny any of it to be true?&#8221; The desperation that she was feeling clawed at her insides like a ravenous beast. &#8220;Please&#8230;please&#8230;&#8221; She couldn&#8217;t finish. Please don&#8217;t make her feel anymore.</p>
		
		<p>&#8220;Her name is Angelica. Not Lady Redmond. Not in this lifetime or any other.&#8221; There had only been one, truly, in the whole of that too long existence that he would have ever considered such, and that season had been the first and highest price that he had learned to pay for his curse.</p>
		
		<p>He had her fixed gaze on his face for that first spoken claim, and as if his connection to her through her bag threatened to rob her of her will and her strength to resist him, she released it to his possession. Almost immediately she regretted the decision. Now she was helpless for maintaining her course. How could she run away without even a purse or one change of clothes? She had been foolish to risk her bag to his taking. &#8220;Angelica,&#8221; she repeated the name, seeing the cruelly twisting smile of the face it belonged to. Not Lady Redmond. Her brow furrowed slightly. Was he saying the woman had been lying? But what about all the rest? All the things she had said?</p>
		
		<p>Lian exhaled and looped the bag over his shoulder. &#8220;She was a servant in my employ, yes. Her mother and father retained the position currently occupied by Alice and Henry while she and her sister were maids. She was a child. I remember her hair was barely freed of the kinks from the plaits she wore before coming of age.</p>
		
		<p>I knew how she felt. I never pursued her, I never gave her special attention. Yet the day came that she offered herself to me, and I was foolish and too desperate for&#8230;&#8221; He could not explain their songs. That his world was so far separate from the world of mortals had never felt more evident than when trying to describe the bonds that tied the family. &#8220;&#8230; a connection. There was a beautiful girl on my bed as bold as the sun, and I took her. It is all I ever do, I find. I take until that which I admired is left a ghost of itself. I ruined that child.&#8221;</p>
		
		<p>&#8220;She told me the story, yes,&#8221; Delilah&#8217;s voice was husky for the admission, and a skim of the prints of her gloves was wiping the moisture from her cheeks. &#8220;She was not particularly reticent in the telling, either.&#8221; There was a ghost of Delilah&#8217;s drier nature in that observation, but she was determined that he should not think that she was to be so easily comforted for the shock that she had sustained. So, he was no different than any other man about town. He was not the first to take the virtue of a housemaid, and he would not be the last. She turned her face toward town and started walking again. He could follow her, or not.</p>
		
		<p>&#8220;She did not seem to be particularly ruined,&#8221; Delilah&#8217;s voice was stronger, and less broken, now. &#8220;&#8230; dressed as she was in rubies and finery. And she was in your house, Lian. Behaving as if she had free run of the place.&#8221; An echo of memory stilled her feet again. &#8220;She claimed you had come to her, those four nights that you were gone, late in the summer.&#8221; A hint of wariness crept into her gaze again. If the woman had been a one-time mistake, why was he still going to her? If he was. &#8220;I don&#8217;t understand any of it.&#8221;</p>
		
		<p>&#8220;No,&#8221; he said, walking after her with his horse plodding behind. Angelica would not have seemed ruined. &#8220;I have no honor, but she would not suffer for it. I think it was never her intention to suffer. She ran to her parents with my bloodied sheet as evidence of what I had stolen from her. I do not know what they must have felt. If they were frightened or pleased. I could have thrown them all out on the street or married her for her honor. Her mother seemed inclined for the latter.&#8221; He paused as if remembering. &#8220;Her father looked tired,&#8221; he added, quietly. &#8220;I did neither. I purchased an estate near King&#8217;s Lynn and officially hired her parents and sister to retain the property, along with a sizeable annual allowance until they passed. Angelica&#8230; I gave her a few years. I knew I did not love her, I knew I would not elevate her, and I knew that even if she could be free of me, she would not. She lives in comfort with all that I am able to supply, but I do not seek her arms or her love. She is not my wife, and she is not my mistress, but I care for her needs. I visit because I can give little else but material comforts and my company. It is my penance for the future I took from her. Until recently she seemed satisfied with the arrangement, if&#8230; still holding to hope that I might look her way again.</p>
		
		<p>I cannot make right what has been done in the past. I have dredged a long way through this life making series of mistakes that cannot be undone, and there is only my own selfishness to blame. I saw you and from that first moment I knew I wanted you. I could have taken you the moment you arrived at my home, and I know that you would not have said no, even if you think now or thought then that you would have had a choice.&#8221;</p>
		
		<p>Delilah stopped walking again and stood with her arms hugging herself against the cold. She could feel it more bitterly now that the height of her passions was no longer with her to heat her core. She could hear the ring of truth in his voice, and everything that he said made sense. And yet. &#8220;She was&#8230; not kind, Lian.&#8221; It was said gently, sadly. He had not answered her concern about Angelica being in the house. &#8220;Now that she knows I am there&#8230;&#8221; she did not stop to think that she had inadvertently betrayed her willingness to remain. &#8220;&#8230;what is to stop another such incident, or several such from occurring? I do not think I have the fortitude to endure it.&#8221;</p>
		
		<p>&#8220;She will not cross the grounds again,&#8221; he said, too firmly. It was as if he thought he could make it true just by speaking it. &#8220;It was not her place. It was not made clear enough, but it will be.&#8221;</p>
		
		<p>She looked up into his face, allowing her gaze to trace over his features, there was an odd expression in her own, a strange sort of wistful yearning, the ghost of desire and a hint of fear. Lian Redmond had the power to destroy her, to ruin her as thoroughly as he had ruined Angelica, only she had no mother or father, no sister to protect her interests or plead her cause. He could have ruined her months ago as he had so willingly pointed out. It begged the question.</p>
		
		<p>&#8220;What do you want from me, Lian Redmond?&#8221; He had admitted that he was a destroyer of those things that he desired. That he desired her, she could not now deny, or that she desired him. Where could they possibly go from here, that was not a recipe for disaster? &#8220;You terrify and enthrall me.&#8221;</p>
		
		<p>Lian stopped, regarding her quietly with that same intensity of a stare. &#8220;You are&#8230; a rarity that I find myself lucky to know&#8230; Just as I find myself fortunate that in the first moment we met I was so consigned to a death of the heart that I did not touch you. I thought I could be content to your presence in my home, but no hour that I could slip from my quarters seemed to be early enough. I never saw Angelica in your face. She is as similar to you as a carnation is to a rose. Perhaps I am blind for only seeing Delilah Flowers, but&#8230; being near you, I thought perhaps this time, I would try to do this right.&#8221;</p>
		
		<p>Delilah didn&#8217;t know how much she had needed to hear those words until he had said them. That she had been a replacement, the second course in some habitual meal of the Lord&#8217;s had been one of the hardest thoughts to endure. &#8220;There is no such thing as a right way, Lian&#8230;&#8221; she murmured. &#8220;We are all as men, too selfish to be anything less than imperfect in our efforts. It matters only that the intentions of the heart are pure&#8230;&#8221; she said it with a tired smile, &#8220;&#8230;even if they pave a way directly to hell, in the end.&#8221; It was all she hoped for and dreamed of. The hope that whatever he wanted of her, needed of her, came from a pure and honest heart. The game, she could not endure.</p>
		
		<p>He finally risked lifting a hand to touch his fingers to her cheek, as if to wipe away the tears she had endured. For the chill that clung to her from her night&#8217;s travels, he seemed almost warm where his touch lingered. &#8220;There is some honesty and directness for you, Ms. Flowers. I am sorry for the tears you shed and that you were given the impression that this was a game I played with you.&#8221;</p>
		
		<p>&#8220;I am sorry that I do not know how to be any other way&#8230;&#8221; but direct. She turned her face slightly, into the brush of his fingers, before lifting her chin and gently freeing herself of that touch, as if it had to power to cloud her judgment and thinking. She had decisions to make.</p>
		
		<p>&#8220;I am, and have only ever been, a monster,&#8221; Lian admitted quietly, lowering his hand. &#8220;There should be no cause to believe my truth, but it is as much sincerity as I am capable of giving.&#8221; And he was a monster. There was only one future he could give her, one withering curse that he could inflict and no guarantee that her song would keep him alive for her eternity. &#8220;&#8230; I would like for you to come home. If&#8230;&#8221; He seemed to be struggling with what to say next. &#8220;&#8230; you are concerned of the room you stay in, you could move to another.&#8221;</p>
		
		<p>Delilah shook her head slowly, in the negative, and for a moment it almost seemed like she was refusing to return with him. &#8220;You are not a monster, Lian, only a man.&#8221; She paused and sighed. &#8220;There is no need for another room. I will not cede her that much power over me,&#8221; she said quietly. Then she smiled, faintly. &#8220;Besides, it took entirely too long to make it anything less than a dusty mausoleum.&#8221; She loved her spring bower of a room, and would not be chased from it. If she stayed. &#8220;I just&#8230; don&#8217;t know, what to do.&#8221; Delilah was no fool. She knew her heart and her body. She desired Lian, and it would only be the worst for knowing now, that he wanted her too. Could she stay under his roof, indefinitely, without the inevitable result? And was she willing to pay that price? No man that she had ever known, had denied himself his desires indefinitely.</p>
		
		<p>&#8220;&#8230;I am&#8230; sorry,&#8221; Lian murmured, hesitantly. He must have seemed to be trying to bribe her. &#8220;I wish you would stay. I have no expectation that life will simply continue as if this had not occurred, and I would not presume your own wishes on the matter. At least come back to finish the fortnight. Whether you choose to stay or go then, I will not stop you, and I will be pleased to write you a letter of reference.&#8221;</p>
		
		<p>Delilah looked up into his eyes again. A fortnight. He was giving her an out, the opportunity to make her decision on a cooler head and from an objective perspective. It was not like she had any legitimate plan at the moment for what she would do, or where she would go. It was cold and getting colder and she found herself craving suddenly, the warmth of the fire, a cup of Alice&#8217;s tea and the end of her book. He was not denying her right to go. She could look around and make better plans during that time if it seemed necessary.</p>
		
		<p>Finally, she nodded her head in a slow affirmative. &#8220;A fortnight,&#8221; she echoed it huskily. &#8220;A fortnight and then I will decide.&#8221; A fortnight to decide whether to release the last bit of rationality and sense she possessed, because remaining Lian Redmond&#8217;s servant was probably the worst decision that she might ever make in her life. &#8220;Take me home, my Lord. My toes are likely lost for frostbite, and I fear my legs cannot walk another step.&#8221; And if he were studying her features, there would be no denying Ms. Delilah Flowers was carrying an evident shade of blue to her generally rosy lips and cheeks. For good measure, her teeth suddenly clicked together for a chatter. She was spent, physically and emotionally, and now that the worst was past, everything about her was threatening a collapse.</p>
		
		<p>&#8220;My Lady,&#8221; Lian had her, suddenly by the waist, swooping her up and onto the horse&#8217;s back as if she weighed nothing at all. That he had ridden bareback would be evident enough, given that there was nowhere to sit save for a blanket that had been thrown over the carriage tack. &#8220;Hold on, Ms. Flowers,&#8221; he warned softly, a hand on her knee where he had placed her aside on the mount, as if he were concerned that she might fall over, despite the reins she held. Her travel bag was on the ground only as long it took for him to shrug out of his jacket before he swung up and behind her. The jacket would not quite be as warm as he knew she needed when he wrapped it around her, nor would his body be, where he looped an arm around her to keep her secure. He did not let her go until the moment they were safely back on the manor grounds.</p>

	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="14-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter XIV.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="16-link">Chapter XVI. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
