<div class="row">
	<div class="col-xs-12">
		<h1>Chapter V.</h1>
		<hr>

		<p>Anowen Castle had two sprawling basement levels with enough rooms to house the army of servants that should have been tending the castle. However, the basements may as well have been an empty cave system for the cobwebs and dust that had accumulated over centuries of disuse. Despite this, there was one corridor where fresh footprints left a trail to a secret room.</p>
		
		<p>It had taken years of slipping between sunbeams while Joanna&#8217;s sisters slept to squirrel furniture down the stairs. The effect was a simple hideaway. Outdated rugs provided comfortable flooring for feet that were often bare, and paintings and sketches had been hung on the walls. There were six pieces of furniture in the little room: a single bed with a patch quilt comforter, two small tables (both with vases of fresh flowers), a writing desk, a chair, and a bookshelf that was home to the library&#8217;s stolen collection. It was certainly a space with a quaintness befitting a peasant more than the lavishness rained upon the queens.</p>
		
		<p>In fact, Joanna had quite a nice suite upstairs with the others. She had a large bed and a writing table, and her own washroom with a copper bath. The only thing she did not have within those upper levels of the castle, was peace. She had learned to take her tormentors&#8217; antics in stride, coming when called and staring passively through their mocking. She found it had done more to irk them that nothing they did seemed to bother her. After all, she had an eternity for them to grow tired of treating her like a servant. For those days and hours that she wished to be left alone, she had her secret room, known only by a few.</p>
		
		<p>Tonight, she was fortunate that most of the queens that cared to disturb her would be out on the hunt. However, she had still slipped downstairs while the sun was high, cleaning and dusting her abode, and replacing her flowers with the fresh bouquets that Ayla brought from the town gardens. As young as Joanna was, she could not yet face the sunlight without earning blistering burns for her effort. By the time the sun had set, the woman was back at her desk, quietly writing by the lanterns that served as her only light source.</p>
		
		<p>To a human, Joanna was as lovely and perfect as any of the females in the coven. She possessed fair skin and thick, golden hair that she kept in a braid down her back. Her face was heart-shaped, her lips full and pink, and her green eyes were large and rimmed with thick lashes. Although she was thin, a human would have thought her beautiful, but it was only the gift of her curse that made it so. The illusion did not fool her sisters. Her eyes were a little too far apart, her nose just a little too big, and when compared to the beauty of the other brides, she seemed much more the mortal — or toadish, as some helpfully pointed out. Joanna did not help her own cause. She made no effort to twist her waves into the lovely spiral curls that were the fashion, and she seemed happy with the selection of the three simple gowns she rotated through.</p>
		
		<p>She wore the peach muslin dress that evening. It hung over her shoulders and was accompanied only by a single, black velvet ribbon tied around her throat. It was the only concession to fashion that the woman seemed to make, although that alone had been by chance. She had been wearing the same ribbon since before she had been sired, and it had begun to tatter wear. Joanna did not seem to mind that, either.</p>
		
		<p>Dorian wound his way down the familiar musky hallway that was buried in the belly of the castle. He&#8217;d advised, more than once, that the area should be cleaned out and lit at least with a torch. It was mostly for his concern for the woman moving around in the darkness like a mole underground than for his own comforts. Joanna had listened and smiled in that particular way she had and then proceeded to ignore his suggestion. Most of the time he didn&#8217;t know if to shake the woman, ignore her, or put her over his knee for the spanking a rebellious child might deserve, for all that he was an elder in this family. But the thought of putting Joanna across his knees stirred responses in him that were far from paternal, and he&#8217;d made it a point to try not to think about her as a woman. He was rarely successful in his efforts. For her part, she was the bonded wife of his sire, and a young bond, at that. Lian&#8217;s song would be so powerful in her blood, that Dorian would never be more than pleasant company, viewed much as an uncle or brother might be.</p>
		
		<p>He didn&#8217;t bother to knock at the door to her hideaway. So few even knew of its existence that she would not be anything but welcoming to those came through it. That it was be him would be the only surprise. It had been a while since he had come, as he wrestled with the struggle that his response to her presence had become. He was not particularly good at hiding his sentiments, and his concern was growing that Lian might become aware of them, even if Joanna would likely remain in the haze of the cocoon that Lian&#8217;s song wove around her. There were times he almost resented his sire, almost, for his abandonment of the treasure that he had hidden away and forgotten in the corner of his garden. Joanna deserved so much more. She deserved to be treated like the queen that she was, to be showered with indulgence and attention, and a decent bloody wardrobe.</p>
		
		<p>That last thought was on his mind as he ducked his dark head under the slightly lower than normal door frame to intrude on her peace. &#8220;I come bearing gifts if you will only spare me the lashes I deserve for staying away so long.&#8221; It would be his greeting, a safe release from the turmoil of the thoughts knocking around in his chest. His gaze touched over the well-worn peach muslin that he swore had a patch somewhere in it; though it was hidden well enough. His lips pinched tighter. He had never put her on the spot by pointing out the obvious deficiencies in her wardrobe.</p>
		
		<p>Joanna&#8217;s golden head lifted. While she often wore that far more neutral mask, there were a few whom she smiled for; Dorian among them, now. "Ah, Dorian," She had lived in England for well over a century, but it seemed as if through sheer willpower alone her telltale French accent had remained intact.</p>
		
		<p>&#8220;You are a radiant light in this dark misery of a hole as always, Joanna.&#8221; His movements were born of habit, now. He tossed her offering with less care than Raven might have preferred onto the surface nearest the door, while he veered away from her, avoiding the temptation to touch. The bed was the longest bit of furniture in the room, and Dorian preferred to stretch out while he was here.</p>
		
		<p>Finding a seat on the edge, Dorian began to work off his boots so that he could hoist his socked feet up onto the quilted surface. He snagged the pillow to serve as a prop against the head on the bed, crossed his ankles, and finally deigned to let his gaze rest and remain on her person. &#8220;If Raven&#8217;s displeasure that I took it is to be the judge, it will be well worth your time to enjoy.&#8221; It was a brutal sort of self-flagellation that he had made her bed his home away from home, but it was his own torment to endure.</p>
		
		<p>&#8220;Already made your rounds upstairs have you?&#8221; It served as her greeting as she pushed from her desk to collect the treasure of his gift. &#8220;I have not heard the howls of cats in heat. You must be losing your touch.&#8221;</p>
		
		<p>&#8220;You are fortunate that I am entirely too comfortable to look for something to throw at your head,&#8221; Dorian replied idly, rolling his own toward her on the pillow. His arms lifted and crossed behind his head. &#8220;I am not to be blamed for the fact that the rightful Lord of the Cats does not surface enough to scratch their itches.&#8221; His gaze turned thoughtful, and he lifted his brow slightly as he regarded her. &#8220;I do find it interesting that you noticed, however.&#8221; That escaped on a nearly serious note that was chased almost immediately by a retreat into the safe zone.</p>
		
<p>Joanna&#8217;s expression softened, although she distracted herself with glancing down at the pages of his gift. She did not treat books gently. She bent them too much, leaving cracked spines and crinkled pages in her wake, even if she did not write in them. The poetry he had brought her was only afforded marginally better treatment when she split it open because he had mentioned Raven&#8217;s name. &#8220;Of course,&#8221; she replied, finally. &#8220;If you lose your touch, I am afraid you have few other qualities that you would share. And then where would we be with the cats bored of you?&#8221; She tsked.</p>

<p>&#8220;My heart&#8230;&#8221; Dorian managed the murmur of feigned distress for her repartee. Her stinging wit was only one of the many things that he enjoyed about her company. Everything about her made him feel alive.</p>

<p>&#8220;It will recover, no doubt. Thank you for the poetry.&#8221; Her smile grew a little brighter, and she folded the book closed again to hold against her chest as she sat back at her desk. &#8220;I will not scribble in it.&#8221; If only because she knew that Raven was more than likely to be aware of who had brought the collection to her. Otherwise, those stolen treasures would have already endured the mark of her thoughts.</p>

<p>&#8220;You were busy in town, then?&#8221; she asked. Joanna had noticed how long he was gone. She kept an arm looped around the book, the other elbow propped on her writing desk so that she could rest her chin on her hand where she had turned to face him. &#8220;Was it for business or pleasure?&#8221; A beat. &#8220;And if you have nothing exciting that kept you away, you may make something up, <em>oui?&#8221;</em></p>

<p>He had no qualms about being less than truthful about the reason for his absence, and fortunately, Lian had provided a perfect alibi with his recent visit. &#8220;Town, for a bit of both. Evidentially I have been careless in making preparations for my impending demise. Lian was quite salivating at the idea of inheriting all of my fortune and none of my bad luck.&#8221; He paused a beat. &#8220;Accompanied Lian to the races and had a spot of trouble on the ride back. Nothing we couldn&#8217;t handle.&#8221; His expression gentled some. &#8220;What of you Joanna? Have you found a stake with which to spear the witches yet? I wish you would say something to Lian. He would have no tolerance for their machinations. You are his chosen as much as they. It bothers me to see you treated as little more than a servant to satisfy their need for power over someone.&#8221; His brow was furrowed, now. He was useless for hiding his displeasure with the whole situation.</p>

<p>&#8220;I do not mind them so much, honestly. Better the devil I know than what might come of sending Lian after them, in any case.&#8221; Dorian was right. Their proper Lord was not around often enough and were there to be any repercussions, Lian would not be there. For all that Joanna seemed to care little to act the part of a lady, she was not unwise to the depths of their deviousness when they felt spurned. She let her eyes drift over Dorian in quiet study before her smile warmed. &#8220;And you should not be so bothered on my behalf, although I am appreciative for it.&#8221; She lifted her shoulders. &#8220;That besides, what else would I have to fill the span of eternity?&#8221; Only poetry and books until she could face the sunlight again, and there was only one aside from her who seemed to share that interest in her writing.</p>

<p>Dorian scratched his scalp and managed not to exhale the breath of frustration that threatened to escape. In the end, it was only Joanna who could determine the course she must choose to ensure the most comfortable life for herself. He was not here to help her, nor was Lian. There was nothing for it but to endure it seemed, and eternity was a long time to endure unless she somehow managed to find her voice someday. The situation was beyond his power to fix and not being a man who enjoyed staring at impossibilities. He often redirected his thoughts elsewhere. Her voice drew him out of his distraction.</p>

<p>&#8220;The days blend together already,&#8221; she murmured. &#8220;I forgot it was today that Raven was going shopping. I filled my book and needed a new one.&#8221; She lifted the page she had been writing on. &#8220;I had to start on loose parchment. I would much rather my thoughts be bound in one place.&#8221; They were harder to scatter that way.</p>

<p>&#8220;A journal is your request, my Lady? A journal you shall have.&#8221; He narrowed a look her way, studying her attire with a mind for the summer night that was fast encroaching. &#8220;The sun has set, and you look to be in need of fresh air.&#8221; Given she could get little of it in the daylight. He swung his legs off the bed, reaching for a boot. &#8220;It might surprise you to know, m&#8217;Lady Poet, that I myself am not disinclined to jotting my thoughts down on paper, though I must admit that mine are nearly so artfully done as your own.&#8221; The words were out of his mouth before he could contain them.</p>

<p>It took Joanna a moment before she seemed to realize what he meant. For a few heartbeats, her expression remained unchanged from the gentler contentment in his company. &#8220;My Lord is too kind,&#8221; she offered, almost in a tease. It seemed to dawn on her, finally, that they were meant to leave, and she straightened in her chair with a furrowed brow. &#8220;Oh.&#8221;</p>

<p>Stop. Now. That would be Dorian&#8217;s conscience ringing a peal through his blood with a flood of contradictory anticipation. Why the hell should he? It wasn&#8217;t like he planned to seduce her. He would bring her right back, and plant her back into her miserable obscurity, just as she wanted. But just for a while, a short precious while, he could lift a summer rose from the hot house and enjoy her unique fragrance.</p>

<p>&#8220;I have a short collection of unused, bound journals at home. I shall be happy to spare you one. We can ride there by the forest trails, retrieve our prize, and be back before anyone even knows that we are gone,&#8221; he said it, almost carelessly, as if he were not proposing the theft of a bride from the castle of his Lord. He wouldn&#8217;t be able to use the carriage. To leave and then return in the larger vehicle would arouse more questions than he cared to have to answer, and it would be impossible to hide that he had taken Joanna with him. They could saddle the mounts without drawing attention and keep to the forests to ensure they avoided the hunting party. The riskiest part of their venture would be emerging from the tree line to gain access to the driveway of his mansion on the outskirts of town. He stamped the second boot into a comfortable fit.</p>

<p>&#8220;Come, Jo, I&#8217;ll not take no for an answer, I know there&#8217;s a bit of game in you somewhere.&#8221; There was a ghost of a tease to his voice. &#8220;You&#8217;ll need a riding cloak&#8230;&#8221; for the chill, and for the hood to cover her features. That would be their greatest challenge of the moment.</p>

<p>Joanna had her smile again, though it had seemed hesitant to emerge, at first, for those steady warning drumbeats of her heart. She held the book tighter to her chest as if it could quiet them. &#8220;You will let me to my room,&#8221; For the cloak. Even if he had not said so, she knew the reason would not just be the chill. &#8220;And I can slip from the kitchen courtyard to the stables.&#8221;</p>

<p>There were a few of the brides who she knew she would not care to be seen by. Those who would care enough to punish her later, however, had not all left the castle. For that reason, she was pleased to play the game of intrigue.</p>

<p>She paused a beat, then offered him a sheepish smile. &#8220;Please. If I am not quick enough to help you put the saddles on the horses, do not use the side saddle for me. I cannot ride aside.&#8221; Her smile grew, briefly. &#8220;But I will hurry to help.&#8221; It had been a long, long while since she had ridden or saddled a horse, but she could remember. Those mortal years of her life had been spent among animals on a family farm. Even as a housewife, she had helped outdoors. Joanna began to rise and only stopped to pinch at the fold of her skirt to lift it some. The length would do for riding astride. As if to cover the motion, she dipped into a ladylike curtsy and hurried out the door.</p>

	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="4-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter IV.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="6-link">Chapter VI. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
