<div class="row">
	<div class="col-xs-12">
		<h1>Chapter XIX.</h1>
		<hr>

		<p>A short distance away within the boundaries of the castle gardens, Lord Vaughn&#8217;s mood and music was as dark as his sire&#8217;s was bright. It threaded through the bond that laced like an invisible strand of a spider&#8217;s web between them, dancing under the remaining resonance of the Elder&#8217;s music with broody, somber notes. His own sour composition was even more noticeable for the palpable shift that he had heard and felt in Lian&#8217;s song. That the Lord of the Castle had taken the time to weave a song with one of his brides while he was on the premises was more than evident, at least to him — and probably to everyone else. There were few who still drew the depth of feeling from Lian that it would take to create the ripples that had washed over his soul within that last hour, and some part of him had the grace to be pleased for the elder queen who had been favored. At least someone had been.</p>
		
		<p>A muscle ticked in Dorian&#8217;s jaw, and he focused the tension felt rising again in his body into the effort and concentration required for loading a ball into the barrel of the Baker rifle gripped between his knees. A black, cropped riding-coat reached only to his hips and fell unbuttoned over a simple drawstring white shirt and dark breeches so that he could reach with ease into the custom-made belt at his waist. It carried a series of pouches that he had made to carry the primer, flint, powder, balls, and patches that he would need to make use of the new delivery for his weapons collection. That he had taken this long to acquire a privately-owned version of the military weapon was a testament to the current environment of war that still lingered on the continent. Working weapons were much more in demand on the battlefield than mounted in a young lord&#8217;s collection. He adjusted the grip of his boots around the stock of the rifle where it rested on the grass of the lawn and set a patch and ball into the muzzle tip. A reach to his hip secured the starter, and it did not take much pressure to force the ball into the barrel.</p>
		
		<p>What in the hell had happened? He hadn&#8217;t abandoned Joanna as their sire had been guilty of doing all too often with his brides — at least until the recent, surprising change in his behaviors. They had spent what he thought was a pleasant evening together during the summer past, had enjoyed several more visits over the passing months, and then just in time for the bloody holidays, she had coated herself in so much ice toward him, that she had made Celia appear a sun princess. He drew out the ramrod and jammed the ball down through the barrel with a series of vigorous strokes; easily, given his preternatural strength. She had received his Christmas present with a polite and distant thank you and had had none to offer in turn. It was not his right to expect one of her, he knew that, but he had enjoyed the&#8230; whatever it was that he had thought was there, that he had felt blossoming between them. He had believed that she had felt it too.</p>
		
		<p>Lian was distracted with his mortal and with rekindling songs in the coven, there had never been a more perfect opportunity to&#8230; do whatever the hell it was they had been doing. Instead, she had withdrawn into a shell of misery that he could see as clearly as if she&#8217;d held up a sign to announce her suffering, and had refused to give him the time of day to relieve it.</p>
		
		<p>&#8220;Hell and Damnation,&#8221; he muttered the curse as he hoisted the rifle to his shoulder to test its balance, weight, and grip. He saw why it had become the weapon of choice for the army. Even for a mortal, it would have sat comfortably in hand; the round sweep of the trigger guard almost a cradle. He lowered the weapon to his hip and reached for his primer horn and powder. There was nothing for it. He would give Joanna what she wanted: which was evidently to be left alone to wither in peace.</p>
		
		<p>Today, she had not even stepped out of the doorway to permit him into the bower. That would be the reason he had set up a target practice instead of spending time in her company. He closed the frizzen, adjusted the rifle to the fully cocked position against his shoulder, and covered his target marker some one hundred yards away across the lawn. The weapon was supposed to be more accurate than the flintlocks that had preceded it. He would put those claims to the test. &#8220;Bloody woman,&#8221; He breathed it out as he locked the weapon. Then he stilled for the squeeze of the trigger as he braced himself for the recoil that he knew would come upon firing. It fired easily, a cloud of white smoke momentarily clouding his field of vision. The sound of the shot reverberated across the premises, bouncing back and forth off ancient stone walls and openings, before causing a gentle rustle in the trees for vibration. Dorian winced. He had forgotten how loud it could be. No doubt he had drawn the attention of the one he was most inclined to avoid for this visit. It wouldn&#8217;t be a problem in the future. He intended it to be his last for a while.</p>
		
		<p>With a smooth lift of the rifle to rest it over his shoulder, Dorian began the walk across the grass to check the target. His eyes had scarcely begun to move over it when he felt and heard the mellow strings of his sire&#8217;s song approaching. Lian stopped where Dorian had crouched to shoot, his hands slipped into his pockets and his eyes set upon the Castilian&#8217;s back. Although Dorian had already discovered what he needed to from the target, he found it difficult to turn to face the man to whom he owed his life, and his eternity. When had living suddenly become so bloody complicated? And yet, the weave of Lian&#8217;s song in his blood, as relaxed as his own storm was in its blowing, was as impossible to ignore as it had ever been. He remembered again, why the hens even bothered with their fighting. Everything that Lian was completed them. It should complete Dorian, but suddenly it was no longer enough, and the thought brought a note of melancholy into his song. So he was not immune for his sex to the growing emptiness that could come in their gilded cage.</p>
		
		<p>&#8220;I would have half-expected Eden to be out here,&#8221; Lian offered in place of a greeting. The girl would have enjoyed watching, if not begging to try shooting the rifle herself. She seemed to go out of her way to be as contrary to her sex as she could be. That she was not out already was a testament to the fact that one did not need to hear that darker song to know Dorian&#8217;s mood. Lian lifted his hand and skimmed a finger over the shell of his ear. &#8220;Of course, you are quite deafening me. It may be possible that she hears it too.&#8221; He was not speaking of the rifle shot.</p>
		
		<p>&#8220;My apologies for the disturbance,&#8221; the Castilian responded. &#8220;It&#8217;s been too long and memory failed. I fully intend to flee before Eden realizes that I managed to entertain myself without her.&#8221; He found, somewhere inside of himself, the ability dredge up the habitual smile, a twist of lips, and he retraced his steps toward the Elder.</p>
		
		<p>Lian dropped his hand back into his pocket, nudging his head toward the paths of the castle&#8217;s withered gardens. &#8220;I should like a walk, old man.&#8221;</p>
		
		<p>&#8220;I&#8217;d think there were fairer faces than mine to take on a stroll, my friend,&#8221; Dorian was at the man&#8217;s side. &#8220;A pleasant visit, I presume&#8230;&#8221; It was hard to miss that it had been.</p>
		
		<p>There was no answer. Not in the moment, and not when Lian had turned with Dorian at his side to walk toward the garden. Lian had had his fill of false smiles to last him a few centuries more, and he wore only the calmer veneer of a mask as they strolled. There had been no one to tend the garden in centuries. The paths were covered with dried vines that hinted of just how overgrown it would be in the summer; if the brown weeds and plants that blurred the garden edges were not indication enough. In the winter, at least, the paths were walkable.</p>
		
		<p>&#8220;Aziza quite kindly informed me that I am a man who thinks like a man, which in the context of the moment was no doubt meant to indicate that I know little of how to handle a woman. Even less do I know how to handle you,&#8221; Lian offered, after that long silence. &#8220;I daresay I cheated you, Dorian. I should like to imagine that if I had been privy to your feelings sooner, I might have been inclined to act.&#8221; But he would fool no one, least of all himself. He knew that in the apathy he had been experiencing, there would have been nothing to be gained from knowing the secrets of his brother&#8217;s heart.</p>
		
		<p>That his sire had discovered of those secrets in the end, did not surprise Dorian. He knew himself to be an open book in the spaces of his soul that he could not mold into the conformity of his will. His music would never lie, and Lian held the key to the very instrument that he played; as he did Joanna&#8217;s. It had been a folly to even try at pretense. Silence reigned between them as he searched for the right words. &#8220;One cannot be cheated of what was never one&#8217;s own to possess,&#8221; he admitted, finally. &#8220;And it was my own cowardice for not speaking that can be blamed for things being what they are.&#8221; His toned shadowed grimmer. &#8220;We have not built what we have on half-truths or lies. For that&#8230; I am sorry.&#8221;</p>
		
		<p>Lian shook his head, his hand lifting as if he could stave off the apology given. &#8220;No,&#8221; he said. &#8220;Dorian, there is no consequence for honesty. I need to know: Is it Joanna that you would wish to court?&#8221;</p>
		
		<p>&#8220;Court&#8230;&#8221; Dorian breathed it out. &#8220;So unnatural a sounding word, for what we are.&#8221; And how they claimed. Theirs was a darkness far from the polite traditions and rigid formality of society&#8217;s dictates. &#8220;I can speak to you of my wishes, but they are nothing in the face of her own.&#8221; He shoved his free hand into a pocket and adjusted the rifle on his shoulder as he walked. &#8220;All I have ever wanted was to be free to be around her and know that I am welcome.&#8221; He fixed his gaze to the death in the shrubbery around them. &#8220;There was a time I had a hope, that perhaps that was a possibility, but I fear the window is closed.&#8221; The twist of lips surfaced again, this time in self-deprecation. &#8220;She will have no more of me, and I would not seek to impose an unwelcome presence on her.&#8221; He looked over at Lian&#8217;s profile. &#8220;Even if such a courtship were possible.&#8221; Joanna was Lian&#8217;s bride, his bond, and there was little to change for that. &#8220;She welcomed my company once. Now, she prefers her own.&#8221;</p>
		
		<p>&#8220;I fear the fault of such falls to me,&#8221; Lian admitted, slowly. &#8220;My loyalty is ever to you more than one of the children, however much I may have favored them in a season. I would not touch her knowing how you felt. Nor have I given her more than a few words, despite the attentions the others enjoy.&#8221; Lian lifted his hand to rub the space between his brows. &#8220;It was an easier path and a cruel one. She is too young in my song for me to have treated her so.&#8221; Even if there had been no small measure of relief when she had finally stopped coming among the others.</p>
		
		<p>Dorian was conflicted. For the sake of Lian&#8217;s cruelty to Joanna, he felt the first stirrings of anger, but it was interwoven with the favor he felt bestowed for the Elder&#8217;s respect for his feelings. It could only be a bitter irony that the very actions meant to prop a door open had sealed it shut. His words when he spoke, were careful. &#8220;It was&#8230; unkind, when she could not know the reason for your choices.&#8221; Evidently, she had made up her own mind. &#8220;It will take more than assuring words and permission, to heal those wounds.&#8221; It would not be up to Dorian to assure Joanna that it would be safe, and welcome that she explore her sentiments freely. &#8220;You are her bond, Lian. Yours is the power to free her from the burden of guilt, and misery.&#8221; He knew that Joanna was suffering in her self-imposed isolation. &#8220;I will not approach her again, lest I can be assured by her own hand that this is her own desire as well.&#8221; Joanna was not a bit of horseflesh to be bartered. That Lian no longer wanted her, did not mean that she was Dorian&#8217;s to collect. &#8220;Hers will be the choice.&#8221; Insofar as welcoming his company for the moment.</p>
		
		<p>Lian stopped massaging the bridge of his nose. &#8220;Of course.&#8221; His glance was sidelong, through his fingers. &#8220;If it is she whose company you desire, then I will let her know that she is not being punished for her own song, and that you await her convenience for a visit.&#8221; He had not been unaware of those pangs of guilty resonance in Joanna&#8217;s melody. "It will remain to be seen if she can overcome being mortified for how her treatment has darkened your music." There was a subtle tease, there about the sensitive nature of the fledgling he had come to care for. There would be no courtship to be had of a runaway bride.</p>
		 
		<p>Dorian turned a sharp look in the Elder&#8217;s direction for the tease, but it was no more than a moment before it relaxed into the twitch of a smile that curved his lips. Lian was right. His biggest obstacle now, would be Joanna&#8217;s own sensibilities. The Elder&#8217;s voice interrupted his thoughts, again.</p>
		
		<p>&#8220;I know now what shall be done, to begin to make things right,&#8221; he said. There was a beat of silence. &#8220;Rather, Celia continues to hold a wisdom far greater than my own.&#8221;</p>
		
		<p>&#8220;Celia&#8230; Ah.&#8221; It was a murmur of acknowledgement from the Castilian. So, the hearts of the elder queens had again come to mold the perspective of their Lord. Dorian&#8217;s smile was wry. "You would have done well to have found your satisfaction in them both." He meant Celia and Aziza, for her own influence. &#8220;Between them, is a wisdom that may well have spared us all a world of trouble.&#8221; But he knew. Their songs had not been enough. And he would not have met Joanna. &#8220;What is it, that our Celia has advised that so changes our fortunes?&#8221; His and Joanna&#8217;s at least. Aziza had already ushered in a season of bounty for his garden.</p>
		
		<p>&#8220;That which you yourself have recognized,&#8221; Lian answered. Except now, the Elder found that he had the will and a reason for which to pursue the course that would result in the upheaval of his family. &#8220;There will be brothers, as I can find them,&#8221; the blonde added. &#8220;I cannot release the bonds to my song&#8230;&#8221; He hesitated on the words, and it was a more thoughtful look that found Dorian. He could release Dorian&#8217;s, he knew. Dorian and Celia alone were two of the eldest in his coven and a bond that old could be a fragile thing. They were also the two he knew it would be the most painful to lose, even if he could make peace with consigning them to his own, silent fate. &#8220;Later,&#8221; he said as if Dorian could know those thoughts. His hand shifted to wave the idea away. &#8220;It is not impossible to find love and forge further bonds. If it is not Joanna, then you are free to seek companionship among the others. It will be Celia alone who will hold the place of Queen.&#8221; That had not been Celia&#8217;s doing, although he had not shared his decision with her, yet. &#8220;I will not count them as brides. I have no doubt they will be pleased, if not for your company then for that of their new brothers.&#8221;</p>

		<p>Dorian wasn&#8217;t sure what he had been expecting, but it had not been that Lian would be prepared to dissolve the status of his claim to all of his coven brides, save one. &#8220;Celia is, and will be a worthy Queen,&#8221; he responded to that bit of the news. The queen deserved it, and had earned it for her patience through the centuries of his searching. He paused, thinking over all that had been said. &#8220;If Joanna is willing, it is there that I will seek to build a bridge,&#8221; he admitted. It was not that there were not others whose company he enjoyed. With time, he could cultivate new bonds if it was his desire. He found in that moment, however, that it was not. Reclaiming what he had lost with Joanna, discovering if it had really been there at all, had become his foremost priority. A thought came to him that caused his brow to furrow. &#8220;If she does not desire to see even darker a mood, she would do well to be as unavailable to her new &#8216;brothers&#8217; as she was for me,&#8221; he grunted. And he could feel the rise of a predator&#8217;s possessive claim in his blood. &#8220;When will you begin?&#8221; To seek out or to make those brothers, he meant.</p>
		
		<p>That there was silence when Dorian asked that question earned Lian a second look. The smirk on the blonde&#8217;s face appeared almost too satisfied, and that was before the chuckle escaped. It was all Lian could do to press his hand against his brow, looking up as if to stifle the threat of further laughter. &#8220;My word,&#8221; he managed finally, his hand shifting to clap Dorian on the back. &#8220;How you must have wanted to wound me at times.&#8221; Particularly since Dorian&#8217;s song was singing of a dark possessiveness of the woman against brothers who did not yet exist.</p>
		
		<p>&#8220;Not wound&#8230;&#8221; Dorian did not try to quell the wry twitch of his own lips that answered Lian&#8217;s unusual levity. &#8220;But I have entertained the notion of a boxing match a time or two over lifetimes.&#8221;</p>
		
		<p>&#8220;Regardless&#8230; As soon as I find suitable men who might survive being hurled among the women, I will make brothers. It will have to be at least two, to start.&#8221; Lian dropped his hands back into his pocket. Their talk was all but done, as he gave no indication that he intended Dorian to follow when he turned back toward the castle.</p>
		
		<p>&#8220;Dorian,&#8221; Lian turned a glance over his shoulder as he offered his parting words. &#8220;They will be staying at your house.&#8221; </p>
		
		<p>Dorian wanted to wound him.</p>


	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="18-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter XVIII.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="20-link">Chapter XX. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
