<div class="row">
	<div class="col-xs-12">
		<h1>Chapter I.</h1>
		<hr>
		
		<p>Maggie Hansen did not want to die. Not that she hadn&#8217;t almost managed to do so on more than one occasion in the past, but all things considered, those situations had been entirely her fault. Tonight, for once, she was a mostly innocent party. The light drizzle that had begun to fall in the fog rolling in off the Humber caused the already thin muslin of her gown to cling to the ample curves of her body. The brunette clutched the small, worn purse that held the key to her rented room closer to her chest. There would be safety at the house of the bawd, surrounded by other women who had been luckier than she at finding paying company for the evening. She was at the last of her coin, and after tonight she would not even be able to afford the rented room. In the morning, she would be reduced to the streets, a common hackney whore. That was assuming she survived the night; because as it was, Maggie was quite certain that she was being followed.</p>
		
		<p>She was not sure just when she had become aware of the shadow following her through the gaslamp-lit side streets of Easthaven. The darkness was there and getting closer, though never stepping into the light to show its face and never making a sound. Every terrifying story that she had heard told by the women of her profession came to mind. Surely, if her stalker was looking for the rewards of honest pay, he would show himself. What gain was there to be had in remaining hidden? Women had disappeared in Easthaven before, never to be heard of again. Few cared for the loss or absence of a common country whore. Maggie could feel her heart racing and the trickle of rainwater running down her face and between her breasts like perspiration. She needed to get out of the dark. She needed the safety of light, even if there was no one to see her. On the other side of the street, a street lamp beckoned, dimmer for the rain and mist in the air. Beyond it loomed the tall dreary faces of older townhomes, securely buttoned down for the night. Between herself and relative safety? The wide empty expanse of the street. Throwing caution to the wind, Maggie dropped her hands down to gather up her skirts and began to run.</p>
		
		<p>The shadow fell onto her path, like a bird of prey swooping down upon a little field mouse. Just when Maggie was in reach of safety, she was caught. One strong arm clamped around her stomach to draw her into the hard chest of a man, and one hand flew to her face to stifle her scream into his palm. Without thinking, she began to twist and kick in his hold, flailing her legs in a tangle of skirts against the unyielding strength of his body.</p>
		
		<p>&#8220;Gentle, gentle, gentle&#8230;&#8221; the man&#8217;s voice was young, throaty, and rough as he breathed the words above her ear. The hand that clamped against her mouth was broad and soft as an aristocrat&#8217;s with long fingers that dug into her cheek.</p>
		
		<p>&#8220;Be gentle, now,&#8221; he continued. &#8220;I will be as gentle as you are, sweet one.&#8221; The whispering lips on her temple curved into a smile against her skin. &#8220;Do not scream. My ears are just! — so! — sensitive!&#8221; He jerked her backward, punctuating each word with a drag of her body deeper into the darkness of the alleyway from where he had come. &#8220;Should have stayed out of the rain, sweet. There are only monsters who come out on nights like —&#8221;</p>
		
		<p>Whatever the man had meant to say was broken off into a grunt. There was no sign of a second assailant, nothing that might cause him to go flying. Yet suddenly, her attacker sailed through the air and Maggie along with him. He rolled on the ground, releasing her to fall into her own heap on the cobblestone, and snarled, &#8220;You —&#8221; the man froze, his gaze fixed in the direction of the end of the alley. He himself was only a shadow: a tousle of black hair, the fine cut of a black suit. His eyes, bright as two polished gold coins, widened for what he saw there. The man scuffled backward on the grimy, cobblestone pathway to scramble to his feet. &#8220;Apologies,&#8221; he mumbled, dropped a bow, and pivoted on his heel to flee into the darkness.</p>
		
		<p>The new arrival was a silhouette at the opening of the alley, standing quietly over Maggie Hansen. He spoke in a voice that was gentle, like a parent soothing a frightened child after a nightmare, &#8220;It is alright. You are safe from him&#8230;&#8221; Her rescuer extended a hand, inviting her back to the light beneath the security of his umbrella. &#8220;Are you hurt?&#8221;
		She shook her head reflexively as if she had no thought or choice other than to answer her savior. Words formed in her mind but could not quite make it to her lips. It was all that she could do to gather her legs under her to try for a rise as she clung to his hand. Some part of her mind wrestled with the way in which her attacker had been bested and with the respect that had been meted out to the man who had saved her from almost certain death.</p>
		
		<p>&#8220;No,&#8221; she managed a word, finally. &#8220;You stopped him before he could do his worst.&#8221; There was the faintest hint of worship in her tone.
		He held her hand, as cool to the touch as the shadow had been, and led her to the streetlamp. Even in the safety of the light, however, he kept his fingers curled around hers. His face was chiseled and pale like the marble from which it seemed to have been cut. Although darkened by the moisture in the air, his blonde crown might as well have been woven from gold. He wore an expensive suit, black, double-breasted with golden buttons atop a silk vest; a vest that matched the storm-blue of his eyes when he looked at her.</p>
		
		<p>&#8220;There&#8230;&#8221; He lifted his hand, his umbrella balanced on the crook of his arm, and touched long fingers to her chin. Turning her face up to examine her, he offered a small, polite smile. That close, she smelled a scent of age like old books from him. &#8220;Safe and sound,&#8221; he said. &#8220;But not for long in this weather and this darkness.&#8221;</p>
		
		<p>He let his fingers drop away from her face, and keeping his hand on hers, he bent forward in a half bow. &#8220;It would please me to escort you to my home. I can spare you the rain.&#8221; His blue eyes lifted to hold hers.</p>
		
		<p>Maggie was lost in his eyes. They seemed to go on forever in depth, so perfect a match for features almost divine. She was so lost for the staring that she almost didn&#8217;t hear his words. &#8220;Me?&#8221; Her fingers fluttered to rest on the fullness of her bosom. &#8220;You&#8217;re wanting me?&#8221; She almost seemed surprised by the fact, and then, as if the very indecent proposal finally sank in to remind her of who and what she was, she stood a little straighter. He was not some dashing lord who had been swept off his feet by the damsel he had rescued from a fate worse than death. He was a man like any other, walking the darkness of Easthaven&#8217;s streets looking for the pleasures he could pay for.</p>
		
		<p>&#8220;I&#8217;m not cheap, I&#8217;ll have you know,&#8221; she looked him dead in the eye. Who knew the next time she would land an offer from a well-padded noble such as he appeared to be. She would have to make tonight pay for as many more days of boarding as she could eek out of it. &#8220;And I don&#8217;t do those strange things. No whips and such. Just a toss, but I&#8217;ll make it one you won&#8217;t soon forget.&#8221;</p>
		
		<p>The man nodded, extending his hand into the darkness. &#8220;My Lady. My carriage is not far. Please. I assure you, my intention was far more humanitarian.&#8221; He leaned in close to offer a quiet murmur, &#8220;But I am sure you will not be disappointed by my wealth.&#8221;</p>
		
		<p class="text-center">***</p>
		
		<p>The carriage ride swept them from town, nearly a half an hour into the heart of the surrounding forests before the trees began to clear. In that time, the man afforded Maggie polite, if distant, conversation, sitting alongside her as the carriage rumbled off the beaten path. By the time the mud and dirt of the forest gave way to the tamed length of a courtyard, the rain had picked up to a thundering pace.</p>
		
		<p>He stepped out first, splashing into a puddle that had gathered on the cobblestone. &#8220;Mind your step, Maggie,&#8221; he cautioned, offering his hand to help her vault over the water. Before them, standing like a white-armored sentinel in the fog, was a castle. Its walls and spires reached skyward, disappearing into the rain, seemingly without an end.</p>
		
		<p>Maggie had never seen anything so grand as the castle before them. She had heard in town that such a place might exist, but no one seemed to have ever actually seen it. Most had only heard of the woman in black who sometimes rode into town and out again. That woman never shopped or did anything else that might indicate that she was a housekeeper for the place others whispered she came from. There were none in town who claimed to work there, and surely something so big as this would need a small country of servants for management.</p>
		
		<p>The woman was distracted as she settled into the escort of her company for the evening. No, she was not disappointed by his wealth at all. Fortune had at last shone on her with favor. The first stirring of excitement turned in her stomach. She might be working tonight, but this golden god was by far the most beautiful man she had ever seen. For the gentleness of his touch, she knew that he would be, if nothing else, a satisfying ride. All things considered, she was feeling like a princess being invited to a ball, and she found she could not wait until the dancing began.</p>
		
		<p>Maggie&#8217;s escort led her beyond the large front doors, through the gilded halls, and past tall paintings and Roman-styled sculptures on white pedestals. With a hand against her back and the other still curled lightly around her own, he encouraged her deeper into the castle. Finally, they arrived in a white-paneled room, trimmed with gold. Plush, high-backed chairs of blue velvet and comfortable sofas and chaise lounges seemed ready to house a multitude of guests. The walls themselves were bare, save for a large mirror that hung above the fireplace, reflecting the entirety of the room. He stepped between the arrangement of seats, leading her directly across from the fireplace to the back of the room where the longest sofa waited. </p>
			
		<p>&#8220;The ride and the excitement left you weary, Maggie,&#8221; He helped to ease her down into the gold embroidered pillows. His hand left her back to touch her cheek instead, lifting her face to his, and his eyes found hers again.</p>
		
		<p>&#8220;Oh, I&#8217;m not at all ti —&#8221; Maggie began the polite denial of the blonde&#8217;s suggestion that she needed rest, but it faded away into a hesitant and confused silence as she found herself lost in his blue-eyed gaze again. Suddenly everything about her body felt soft and heavy as if she could not quite control her own movements. She wanted to sit up straighter but found herself leaning into a recline.</p>
		
		<p>&#8220;It is alright,&#8221; he assured her, resting her head on the pillow and tucking her arm across her middle. &#8220;You can sleep now.&#8221;</p>
		
		<p>&#8220;Yes&#8230;&#8221; she murmured. &#8220;So very tired. Maybe just a little nap&#8230;&#8221; And after? She found that she was having trouble remembering what was meant to come next. Her gaze fluttered, a beat of wings, as she tried to fight the power that his eyes alone seemed to hold over her. She managed to raise her hand toward his face. <em>&#8220;Beautiful&#8230;&#8221;</em> It was a softly spoken slur before she gave way to the encroaching darkness.</p>
		
		<p>Fifteen minutes under normal circumstances might mean any number of innocuous things. It could be the amount of time remaining before the bell for dinner might sound, the duration of a musical performance, or the precise time that it might take to complete two dances on one&#8217;s dance card. In the case of the not-so-honorable Maggie Hansen, late of 10 Whitting Alley of the town of Easthaven, it was the amount of time it took for the last drop of her life&#8217;s blood to be drained from a body as sadly shrunken in death, as it had been ample in life.</p>
		
		<p>The low neckline of her gown was stained a rusty red, the round column of either side of her throat showing puncture wounds: some neat and clean edged and others bearing evidence of a more jagged savagery. Part of the bodice of her dress had been torn away and the round fullness of one breast had been likewise punctured in a grotesque echo of a lover&#8217;s kiss. The length of rounded arms bore witness to an onslaught with wounds peppering her thick wrists and forearms. For all of this seeming savagery, however, there was frozen into the face of the woman, an expression of ecstatic pleasure, sealed there with her last breath in a macabre tribute to the price that had been paid for the theft of her future. Maggie Hansen did not want to die, but she had died in a haze of pleasure.</p>
		
		<p>Whoever, or whatever, had consumed the prostitute appeared to be no longer gathered around her lifeless form. That someone, or several someones remained, was evident in the interweaving scents of various feminine fragrances that hung in the air of the room. It seemed, for the sheer volume of the marks that Maggie bore, that not all who had contributed to her demise were present. Only four bodies remained in the room save for the deceased and the one whom had provided her.</p>
		
		<p>The sound of a hushed, melodic voice quietly reading could be made out over the low crackling of the fire. A fine-boned woman with hair the color of honey that fell almost to her calves was seated on a footstool at the side of a larger, occupied armchair. Only these two seemed to be otherwise engaged, disinterested in either the bloodied remains of the meal or the Lord who had so graciously provided it.</p>
		
		<p>A single name in a honeyed croon broke the near silence: &#8220;Lian.&#8221;</p>
		
		<p>The nature of the game was simple. To the bold went the night&#8217;s spoils, and Angelica had never been anything less. She had the face of a young woman, as rounded and sweet as her namesake with large brown eyes and a mound of raven curls already unpinned for the night. Her thumb lifted to sweep across the bottom of her full lips, wiping away the remnants of blood. She sucked the tip of her digit, sauntering closer to where the Lord sat. &#8220;You are soaked from the rain,&#8221; she breathed, letting her hand escape from her mouth to reach out for his face.</p>
		
		<p>Lian, as silent as he had been since the ladies took their prize, did not move. He was still beneath the stroke against the crest of his cheek, only watching Angelica&#8217;s face through thinly veiled apathy.</p>
		
		<p>&#8220;I could warm you,&#8221; she offered, letting her fingers thread into the damp tendrils of his hair.</p>
		
		<p>&#8220;Enough.&#8221;</p>
		
		<p>&#8220;Enough, enough, <em>enough,&#8221;</em> Angelica sang, pulling her hand back to rub it dry against its twin. "I am afraid I do not know the meaning. Keep your wet clothes on if you like, then." She dropped in puff of red fabric, kneeling before his chair and lacing her fingers atop his knee. She lifted a mulish, coffee-brown gaze to his impassive features. &#8220;I can work through them just as well.&#8221; It was said with a pout, as she leaned forward to accent the pale spill of her bosom beneath the ruby and gold choker she wore. &#8220;You are being dreadfully cruel to me, Lian.&#8221;</p>
		
		<p>A sharp laugh interjected over the fretful croon of the younger woman, offered by a tall, stately woman whose beauty was tarnished by the harsh glitter in an aquamarine gaze. The weight of her chestnut hair fell freely, provocatively over the low neckline of her midnight-blue gown, but Shar seemed to be either unaware or careless of the picture that she presented. She had known Lian long enough now to know when the hunt would bear no rewards, unlike the kitten at his heels who was naive enough yet to think that he could be coaxed from his dark humor in this mood.</p>
		
		<p>&#8220;You have known little of cruelty in your life, sweet Angelica, and have much to learn about the flow of seasons,&#8221; she added. Eternity was a long time to try to hold the attentions of the Golden Elder who had wooed them all into his forever. An eternity, it seemed, that he was doomed to walk in solitary darkness, despite his best efforts to collect drops of light and pleasure to light sparks of momentary brilliance and beauty along the way. Six hundred years was a long time to play at treasure hunting. Especially when one failed to find the one true light, the one true song that could drown the silence for ever. Shar could sympathize if Lian&#8217;s fickle appetites had not meant that she too was doomed to an eternity of solitude. For one brief season, she had been the reason Lian had remembered what feeling and living was like. For those moments, she had felt as if she had reached the pinnacle of her life&#8217;s ambitions: to hold the heart of a king in her hands and know that by her love or loss, he would live or die inside. It had been intoxicating, addicting, and temporary.</p>
		
		<p>She had not been his first treasure, and she was not his last. Perhaps she would have been better suited to learn from the lessons of the queens who had come before her, but arrogance and the fragrant aroma of love were enough to make blind fools of any gifted with a season in Lian&#8217;s sun. She had learned the lesson, and well, as she watched him pluck flower after flower, from one century to the next; only to cast them aside when a more fragrant, more living, more beautiful bloom came into season. Angelica had been the last, and it had been over one hundred years since Lian had even feigned at anything other than a polite and dutiful upkeep of his garden. He kept his blooms fed and watered, and occasionally turned the sun of his face to one, or another, in search of a flickering ember of the light that had once blazed, in search of a song to quiet the suffocating silence of the dark in his soul.</p>
		
		<p>Shar moved from her place at the window, a goblet of blood wine in her hand. &#8220;Perhaps our Lord is inclined toward a more aged blend, tonight.&#8221;
		It was not often that Lian turned his attentions her way. Hers was not a song of comfort, warmth, or seduction. Theirs had been a war of wills and passions, and she had found that the darker his mood, the deader his darkness, the more inclined he seemed to be to sample of her cold, bitter cup. A punishment? She wondered at times. But of whom? Her or of himself? Whatever the cause, she did not often fail to take advantage of the opportunity to draw him into the darkness of her distorted melody. &#8220;Leave us&#8230;&#8221; The directive was to the woman at his feet, as if by sheer willpower and seniority she could sever whatever ties might bind the two, to establish her own.</p>
		
		<p>&#8220;I would hope&#8230;&#8221; The cool, gentle, and yet somehow implacable voice spoke from the armchair before the fire and above the woman reading, &#8220;&#8230;that your directive is not intended to include me Shar&#8230;&#8221;</p>
		
		<p>The ghost of dry amusement glimmered in the steel-gray gaze of the pale, silver-haired beauty who sat enthroned, dressed in the black darkness of a widow&#8217;s night. Celia cared little for the more modern styles that the women of the coven so willingly took up, especially when she was in the privacy of her home. Her hair was a wrapped crown of silver braids, interwoven with diamond pins that shone like stars in a milky way. &#8220;I am quite enjoying being read to by Nadine and have little inclination to leave my comfort.&#8221; Her gaze drifted over Lian&#8217;s posture, thoughtful. &#8220;I am sure Lian appreciates my sentiment.&#8221;</p>
		
		<p>Celia knew, as much as Shar did, the poison that was in the cup Shar intended to offer. She had little hesitation about casting a stone into that particular carriage wheel. She let the weight of her gaze rest on the man who had stolen her heart and her life. Of them all, she understood best the meaning of the seasons, had paid the highest price, and despaired the most in waiting with him for the treasure that could save them all.</p>
		
		<p>Angelica turned her head from Shar to Lian, as if his carved marble features might have changed at all considering the older queen&#8217;s command. She could not keep the pleasure of a feline smirk from her lips for the sight of his passivity. After all, it was a curse only when turned <em>her</em> direction. That Shar seemed incapable of drawing him into her song, that Celia had intervened, was reason enough for the brunette to curl her fingers tighter into the damp folds of Lian&#8217;s clothing.</p>
		
		<p>He seemed to realize the extent of her contact at that moment, and his leg shifted from its crossed position so he could sweep her hand from his knee. He did not appear to care that she was still sitting in front of him when he moved to stand, and the woman had little choice but to scoot backward in a most undignified way to make room for him.</p>
		
		<p>&#8220;Keep your comforts,&#8221; Lian said, stepping toward the couch where the corpse lay in repose. &#8220;I have no desire for them tonight.&#8221;</p>
		
		<p>He hooked one arm beneath the back of the late Maggie Hansen, the other under her knees, and drew her into his chest as if her weight had been drained from her along with her blood. Maggie&#8217;s head rolled backward, the arm not pinned to Lian&#8217;s chest dangling limply — a bloodied pieta.</p>
		
		<p>&#8220;You treat the menu better than you treat your brides,&#8221; Angelica whined, shaking her slim shoulders like a toddler during a tantrum. &#8220;I doubt the royal cook would even say the same.&#8221; She threw her hands into the air before letting them smack against the varnished floor. With a huff, the woman unfolded to a stand and smoothed down the red front of her dress. &#8220;You have no heart, my Lord.&#8221; She hooked her fingers around her choker, but was careful to keep her eyes lowered when she spoke her next words, &#8220;No wonder your weaker women have been driven away.&#8221;</p>
		
		<p>Sighing dramatically, Angelica lifted her jaw and pivoted on her heel as if her escape from the room had more to do with the offense the Lord might have caused. &#8220;Go sulk, then. I am pleased to wait until your next visit.&#8221; That she avoided the gazes of her elders was plaintively denied later.</p>
		
		<p>Lian took a measure of care in ensuring he took the opposite door from where Angelica had fled, back into the darkness and the storm without a word to the other three. There could be no fire pit for the rain, and so the remains of Maggie Hansen were gently consigned to the River Humber.</p>
	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="cover-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Cover</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="2-link">Chapter II. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
