<div class="row">
	<div class="col-xs-12">
		<h1>Chapter XVII.</h1>
		<hr>
		
		<p>A fortnight in the Redmond mansion had tripled, and the chill of fall had given way to the freezing cold of winter. Per Henry&#8217;s suggestion earlier in December, Lian had made sure that there were ample Christmas decorations with which to brighten up the halls of the manor. As the final weeks of 1810 began to count down, the crypt that the Lord had kept for a home became trimmed with red and green, boughs of holly, and little ceramic angels nested on many of the surfaces.</p>
		
		<p>Once it had become clear that Delilah would, in fact, be staying, that Lian took to leaving on the weekends. He never admitted that it was to see his brides, to smile and kiss them, and weave songs with the bold or the favorites among them. He would never have been able to explain it, not when the harmony he made with them felt like so much of a betrayal to the mortal woman living within his walls. What he did instead, was be sure that on her days off when she wished for his presence (and sometimes when she did not), he was there. That Lian was gone on the weekends also happened to coincide with Delilah no longer being off work those days, had likely been purely coincidental.</p>
		
		<p>On three of the four Mondays, since he had begun to leave, he returned with gifts for Delilah. They were small things: silk ribbons for her hair, a new pair of gloves, and once, however he had found it, a pink rose. There had only been one week where he returned empty handed. His mood had been dark that day; so much so that he had disappeared into his quarters early in the morning without a word and not appeared again until the next afternoon. Shar&#8217;s song had clung to him for days after, although he forced himself to be as sociable as he could be until Delilah managed to tease and prod him back into better spirits. He even helped her trim the tree that night.</p>
		
		<p>Christmas day had finally arrived, and blessedly so. Lian had a tolerance for most of the Christmas traditions, it seemed, if only for Delilah&#8217;s sake. However, he did not enjoy carolers or the wassailers. He interrupted more than one song as the days of December passed to place money in the singers&#8217; mittens, trying to send them on their way before Henry caught wind of their presence. The old groundskeeper had more love for Christmas in his little toe than anyone in the manor combined. That he, Alice, and Delilah were the only servants remaining on the property for the holiday had not kept him from requesting a large breakfast.</p>
		
		<p>Lian had been pleased to accommodate the man, both in ensuring that Alice had all the necessities to meet Henry&#8217;s requests for Christmas breakfast and going so far as to allow the groundskeeper the impropriety of quite acting as if he were the father and head of their little family. Although the Lord did not accompany the three to the morning&#8217;s church service, he came out to greet them again when they returned early in the afternoon and helped the women down from the carriage.</p>
		
		<p>It was not until later in the evening, when gifts had been exchanged and the old retainers had retired to their room, that Lian remained in the Great Room, content to sit in the high-backed armchair in Delilah&#8217;s company. &#8220;I do think any more of the Christmas spirit,&#8221; he offered finally, managing to sound amused, &#8220;And dear Henry might have burst.&#8221;</p>
		
		<p>Delilah was sitting in the most unladylike position on the floor before the fireplace, as if in all the rooms of Lord Redmond&#8217;s manor, there were not enough seats for her to find a proper place. But that would have made it more difficult to roast the chestnuts that were heaped in a bowl at her side. The length of the tongs and the low cracking flame were enough to make sure that she was not roasting along with them, but there was a flush to her cheeks that had arisen only in part for her pleasure and enjoyment of the day.</p>
		
		<p>She was a vision in pink and white, her gown purchased as one among many, with the suspicious spike in her pay that had begun during her fortnight of decision making. Not that she would accuse Lian of attempting at bribing her into staying with a raise, but it had certainly not hurt. She had remembered his desire that she have a newer wardrobe. Those trips to the seamstresses with pattern books, had been undertaken with an almost childish delight and appreciation for the taste of the finer indulgences that had been so long denied her for her estate, and it had become quite the contest among the dressmakers to woo her trade when it became evident that she was building a wardrobe. There had been one strange incident where one of her new walking dresses had been inexplicably delivered cut almost to ribbons, but upon receiving that report, two had been made as a replacement with profuse apologies and delivered safely. A few may have thought to wonder at who the mystery Lady was, but none turned up a nose for her coin.</p>
		
		<p>It was for their labors now, that Delilah was outfitted in what she had candidly described as her <em>holiday dress.</em> Her light pink open gown boasted a delicate overlay of a damask pattern that framed a textured, woven cotton skirt; warmer for that winter season. Its sturdiness was offset by the delicate lace trimming that edged her low, scoop-necked collar and the cuffs of gently puffed sleeves. Her underskirt too was trimmed in lace, and thin, pink satin bows accented both her hem and the nest of her cleavage. She had disposed of the matching lined damask cloak that had finished the outfit for her attendance at the church that morning, and had somewhere along the way lost her shoes, although her legs were quite tucked away and warm under the layers of the fabric of her dress.</p>
		
		<p>Time had helped to heal most of her wounds for the objectivity that came from being away from the heat of her passions. If she found the weekends unbearably long for his absences, and restless for dreams that her imagination insisted on providing, she had used the time to occupy herself under Alice&#8217;s direction with the significant tasks that seemed to somehow always fall to those days. There had been an almost hesitant return to the exploration of the budding communion that they shared. If Delilah had felt a measure of disappointment for the control that he seemed to exercise not to touch her beyond that required for polite society, and had been secretly greedy for more than the kisses brushed to her temple of an evening, she had managed not to express it. If Lian was keeping to his end of their unspoken agreement, she surely could as well.</p>
		
		<p>Thus, it was a lighthearted tease of an answer that responded to his jest, as another shell broke under the heat of the flames. &#8220;And he&#8217;s not the only one&#8230;&#8221; Her smile softened her features if that were possible, and her lavender eyes danced with humor. &#8220;I have never had quite so wonderful a Christmas. I hate for it to end.&#8221; As it would when the great clock chimed midnight, eventually. &#8220;I do think he was about to stand guard at the doors to ensure you did not chase the music away. It is all that we have had for it&#8221; She canted her head. &#8220;I should have tried for playing, but I&#8217;m afraid that I did not take too terribly well to the lessons when I had them.&#8221; She twisted to detach the latest toasted victim. &#8220;There, that will do I think, and plenty to spare for the morrow.&#8221;</p>
		
		<p>&#8220;I would have thought you more of a one for sugarplums than chestnuts,&#8221; he said as that last, loud crack punctuated the air. &#8220;In that bottom cabinet,&#8221; Lian added and lifted a hand to point toward the oak hutch that dominated the northern wall of the great room. &#8220;On the right — There is a decorative bowl to put the chestnuts in. I am sure Alice will be more inclined that they be in the open for Henry&#8217;s snacking.&#8221; It went unsaid that Henry would appreciative.</p>
		
		<p>Delilah uncurled from her position, and took a moment to shake out and then smooth her skirts. &#8220;I will have you know, my good sir,&#8221; she said with a feigned sense of insult, &#8220;that not everything about me is sugar and spice.&#8221; She knew herself well enough to know that he was very almost right. &#8220;I&#8217;m as tough a nutcracker as any.&#8221;</p>
		
		<p>There was an impish dance to her gaze for those almost scandalous words, that was replaced almost instantly by the demure mask of a society lady as she sailed past his chair in a gentle puff of rose-scented air. She moved toward the hutch. &#8220;And it is quite acceptable to admit that you shall steal a one or two to enjoy as well.&#8221; She did not buy his reluctant cheer. She could tell that he had enjoyed the festivities almost as much as she. She paused before the hutch and opened the door that he had indicated.</p>
		
		<p>Nested within the cabinet was not a decorative bowl, but a large box wrapped in brown parcel paper and tied with a pink ribbon. Delilah stared at the oversized box, and at its wrapping for a few beats before tentatively reaching out to touch the ribbon. She glanced back over her shoulder, hesitant suddenly for her uncertainty. She did not lift it or even move to claim it, although there was an unspoken question in her eyes.</p>
			
			<p>&#8220;It&#8230; is rather too large to be a bowl I think,&#8221; she said.</p>

			<p>&#8220;Rather shaped the wrong way too, I daresay.&#8221;</p>
			
			<p>&#8220;Is it for me?&#8221;</p>
			
			<p>&#8220;Yes.&#8221;</p>
			
			<p>Her expression gentled. She reached into the hutch and lifted the box out. It was surprisingly heavy, and she found herself increasingly curious. What on earth had he gotten her? &#8220;Oh, Lian&#8230; You shouldn&#8217;t have,&#8221; her protest was soft. She lifted the box back to the place that she had been sitting, and much like any child on Christmas morning knelt to begin the careful process of unwinding the bow and trying not to tear the paper too much. Her impatience eventually got the better of her. It was moments later that she had his offering open to view.</p>
			
			<p>The rosewood box was polished to a shining finish and still bore the faint scent of roses for the oil that contributed to its sheen. It was deeper than a gift box. Hinges on its back, along with a small, golden keyhole indicated it could be opened from the top, as well as the drawer in its base. Delilah gasped softly for the beauty and sheen of the box, her hands drifting over its surfaces as she looked for the means of its opening. Neither the top or base, however, gave way immediately to her touch. There was no key in sight among the wrapping.</p>
			
			<p>&#8220;I cannot find the —&#8221; Her admission was cut off by Lian, who revealed just where it was hidden when he reached into his front breast pocket to fish out the little golden key. It sat on his palm, and he held it out for her to take.</p>
			
			<p>Delilah stared at the key in his palm for a moment, and her lips curved into a shy smile. He was really being, quite unbearably romantic. Without a word, she uncurled to her feet again and closed the distance to his side. She reached out and let her fingertips touch to his palm, lingering a heartbeat before she closed them around the golden object and returned to the box. Carefully, she slid the key into keyhole atop the gift that she already treasured for the moment alone, and then she turned the key.</p>
			
			<p>The internal mechanism unlocked smoothly with her touch. It opened to reveal a lithograph of flowers and birds in the center of its lid. The interior of the box was divided into three segments. The topmost held thirty small blocks of watercolor paint, each with a relief of rose blooms embossed upon it. The middle segment had a heavy marble palette with three circular impressions for mixing paint. At either side of the palette, shallow, crystal water glasses rested within the wood. The third, thinnest section had a large brush, and a small quill brush for painting, as well as a small box of pen nibs. Within the bottom drawer was a flat china palette and bone handled drawing and drafting tools, along with a block of charcoal and a box containing charcoal sticks.</p>

			<p>Delilah would not be able to help the soft, stunned gasp of pleasure that escaped her for the unveiling of the gift. Her fingers traced over the lithograph, a breathless &#8220;Oh, Lian. It&#8217;s so beautiful,&#8221; escaping her. She was almost at a loss for words. &#8220;How did you know?&#8221; that she aspired to be an artist, that she had ill been able to afford the supplies for proper equipment. &#8220;It&#8217;s too much&#8230; I&#8230;&#8221; She felt it then: the prick of emotional tears that were welling up to sting her eyes. Her gaze shone with unshed water when she found his eyes again. &#8220;I don&#8217;t deserve this,&#8221; she said huskily, &#8220;&#8230; all of this&#8230;&#8221;</p>
			
			<p>She meant more than the box. She meant access to his home, his company, the luxuries of life that he had afforded her, and all for little more than her existence in his surroundings. She was not so naïve not to know that she had freely received what many a woman of less fortunate circumstance paid a much steeper price to receive. A tear spilled onto a lash and she dashed it away instantly. &#8220;I&#8217;m sorry. Now I&#8217;m being silly, and emotional, and I don&#8217;t know why. I&#8217;m just so&#8230;&#8221; Happy. She did not dare the word. &#8220;Thankful.&#8221; She sniffed a miserable little sound that was at odds with the way she was reverently touching over the contents of the box again.</p>
			
			<p>Lian shifted in his seat and slid slowly down to a cross-legged sit on the floor alongside her. He held his silence, watching her face. &#8220;I am happy you like it.&#8221; He brushed the back of cool fingers across the crest of her cheek. &#8220;Happier you are not crying that the gift was wrong. I was quite unsure what one might need to make more drawings for the house.&#8221; It had not taken long to discover the D.F. on the artwork in the music room had belonged to her. He lowered his hand back to his lap, his smile softer.</p>
			
			<p>Delilah could not help the chase of her fingers to the place where his fingers had brushed her cheeks, before letting them fall to her lap again. &#8220;No&#8230;&#8221; she said softly, &#8220;It&#8217;s&#8230; perfect. I could not have asked for something more perfect.&#8221; Her gaze lifted to search his face. &#8220;You must promise to forgive me if my own does not quite meet the mark. I will not be offended if you do not like it.&#8221; That she had had to save for the gift would be self-evident, but at least part of it had been of her own labor. &#8220;But we shall have to move for the getting.&#8221; Her fingers reached out to lace into his own, and she brought him to a stand along with her.</p>
			
			<p>Lian kept his hand in hers and lifted her own to place a lingering kiss on her wrist, just below her thumb. &#8220;That you thought of me," he said, softly, "Means I will like it.&#8221;</p>
			
			<p>Delilah blushed for that contact of a kiss, but she did not pull her hand away — even if it made her heart skip a beat. She distracted herself with focusing on her mission again. She headed for the small four-foot tree, mounted upon the coffee table in the room&#8217;s center so that it appeared larger. It had been lavishly decorated by the retainers with candy, paper cutouts, glass and other colorful ornaments in a gloriously haphazard display. It was easy to miss during the day,: the small box that looked almost like another ornament tucked into the very heart of the tree. It was a circular gift box, clearly designed for that purpose, and almost thirty years old for having been made in 1780. Delilah had found it in the dusty corner of a thrift shop and thought it ideal for her purpose. The name of the box maker, Francois Nicolas Chevance, betrayed its French origins and had been scribed neatly into its base. The box was pretty enough to be a gift all on its own, she had thought upon purchasing it, but the true offering was inside. She encouraged Lian hesitantly, &#8220;Open it&#8230;&#8221;</p>
			
			<p>She had to endure several quiet moments of watching him study it, despite her admonition. He kept his hand on hers, his thumb tracing over the lid of the box where it was nested upon his palm. It seemed almost as if he was nostalgic in some way for a time that he seemed too young to have possibly been alive for. Finally, he released her to ease the lid from the box.</p>
			
			<p>Sitting upon a bed of thin tissue lining, the enamel painted lid of a spring-hinged, hunter-case pocket watch would be visible. In a seeming contradiction of its purpose and intended possessor, the design of the artwork was softly feminine. The gilded gold and navy blue engraving created a hedge of protection around a gently flowering bouquet of flowers that boasted pinks and lavenders. It was an echo of Delilah&#8217;s personality and coloring. &#8220;I know it&#8217;s too pretty for use&#8230;&#8221; she interjected softly. For a man, anyway.</p>
			
			<p>&#8220;As if I would mind that,&#8221; he said, suddenly, plucking the watch from the box. It was so very her, and he knew that he would not at all mind to use it or keep it close.</p>
			
			<p>&#8220;But it&#8217;s what&#8217;s inside, that&#8217;s the real gift,&#8221; Delilah suddenly felt shy, again. &#8220;I remembered what you said&#8230;&#8221; about his desire to have her close to his person. He seemed as much a child on Christmas himself, then, for the fact that he thumbed the watch open without a moment&#8217;s hesitation.</p>
			
			<p>When the lid sprang back, it revealed what to all intents and purposes appeared to be the quite typical inner workings of a watch. The hour stared back at him from the base. Within the lid, however, her heart&#8217;s offering lay. It had been difficult to manage it to such a fine scale as was needed to nestle into the lid, but it was a self-portrait of Delilah that lay there in profile. Her head and shoulders were visible and her hair was tucked away into a bonnet that bore three small rosebuds in miniature. She had captured the roundness of her cheeks, the curls of her bangs and the faraway expression that she sometimes bore when she was thinking of things that she should not, on that face.</p>
			
			<p>&#8220;There&#8230;&#8221; she breathed and chanced a hesitant smile. &#8220;Now I shall only be as distant as you desire I should be.&#8221; The watch was, to her mind, a picture frame.</p>
			
			<p>Was it too much? Too personal for the tenuous ground on which they stood? It was the best she could think to offer; a small piece of herself since he seemed entirely so fond of it. &#8220;Merry Christmas, Lian&#8230;&#8221;</p>
			
			<p>He answered her worry and her Christmas wish with a movement that was almost too quick. In one instant, he had been looking at her portrait, and in the next, his lips had found hers.</p>

			<p>His kiss softened there, as he had delivered it so quickly as not to give her a chance to draw away from him. Now he lingered and his free hand lifted to cup her face.</p>
			
			<p>Lian was kissing her. Delilah realized it moments after his lips had found hers. He suddenly filled her senses with his presence. For a moment, she was frozen as if distracted by the very fact that the moment was happening, and then she felt her heart melt. She knew everything about herself had begun to soften into an invitation that let him know that she did not mind his closeness. Her hands betrayed her, lifting to rest against his vest, more in the search for support, that for any effort to draw him closer. She could feel joy, rising on an ecstatic tide to flood her soul.</p>

			<p>He could have sworn in that moment that he heard the dancing of piano song through his blood. She was warm against him, and as suddenly as he had kissed her, he pulled back. His hand remained, though, drifting to brush her dark curls back from her face before he offered that second, more familiar kiss to her brow.</p>
			
			<p>&#8220;Merry Christmas, Delilah.&#8221;</p>

	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="16-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter XVI.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="18-link">Chapter XVIII. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
