<div class="row">
	<div class="col-xs-12">
		<h1>Chapter VII.</h1>
		<hr>
		
		<p>The brick townhouses were all beginning to look alike in construction: rectangular, large, and pinched together in a tight cluster in the center of Easthaven. Mr. Morgan Curry possessed one of the larger homes on one of the nicer streets in the town. While it might have been attributed to a successful business in law, any of his more well-to-do clientele knew that his fortune was more deeply tied to his willingness to compromise his ethics.</p>
		
		<p>Mr. Curry leaned forward at his desk. He was a thin man with thinning hair and a shining dome of a head. Married three times himself, he had seven children who accounted for most of the background noise that echoed almost nonstop through his house.</p>
		
		<p>While helping to create marriage certificates of a questionable nature was likely among the least shady of his business dealings, he found his new client was more than willing to pay a pretty penny for the documents. Mr. Curry was just as pleased to accommodate charging more to help the young Lord. Such was the reason that a larger weight was added to his side of the scale.</p>
		
		<p>&#8220;I daresay it seems as if you are trying to swindle me,&#8221; his client offered. Despite his complaint, Lian Redmond reached into his wallet and dropped two guineas on the scale. It tipped the balance in his direction, and before Mr. Curry could say anything, Lian lifted his hand. &#8220;It does not matter. I only wish the papers signed so they can be taken to the courthouse.&#8221;</p>
		
		<p>&#8220;Of course,&#8221; Mr. Curry smiled. &#8220;And your bride&#8217;s name?&#8221;</p>
		
		<p>The sound of crashing from the children grew louder.</p>
		
		<p>&#8220;Celia.&#8221;</p>
		
		<p>&#8220;And her maiden name?&#8221; asked Mr. Curry, looking down at his papers and frowning for the chaos that no doubt seemed to be exploding in his home. &#8220;I apologize, Lord Redmond. We have a nanny to tend the children, but —&#8221;</p>
		
		<p>There was a louder, resounding crash accompanied by the sound of glass breaking. It was followed by a long, childish feminine wail, the hoot of triumph of a male voice and then the thundering of several pairs of feet running down the hall outside of the door of the office.</p>
		
		<p>&#8220;Edward Morgan Curry!&#8221; The exasperated voice of a mature female was heard rising over the mayhem. &#8220;You will return your sister&#8217;s frog — AT ONCE!&#8221; The chortle of delight from the young male voice that answered her, appeared to indicate that he would do no such thing.</p>

		<p>&#8220;Pappa, Pappa, Papaaaaaaaa!&#8221; The pitch of each cry from the younger feminine voice grew louder with each cry. The last was belted out with the power of an operatic virtuoso precisely at the moment the office door exploded open to reveal a girl of about six-years-old. A head full of wild, springy red curls was the neatest thing on her. The pretty, puffed-sleeved yellow day dress she wore had been spoiled by the spreading dampness of what appeared to be water and rust-colored mud. &#8220;Eddie kilt froggieeee!!&#8221; She sobbed, her mouth wide open and tears streaking down an otherwise dainty set of features.</p>
		
		<p>&#8220;I did NOT!&#8221; The stubborn rebuttal was accompanied by the sudden appearance of another redhead over her shoulder, similar enough in appearance to be a male twin or brother. &#8220;See? He&#8217;s right here!&#8221; He grasped a large bullfrog between his hands, holding it aloft into the room past his sister as evidence. A squirt of liquid, likely urine, escaped from the frog for that motion and landed squarely on his sister&#8217;s cheek. She began to wail again in earnest.</p>
		
		<p>The noise appeared to startle the creature. A kick of legs procured an escape in a flying leap that landed the frog squarely in the middle of the room. It began hopping, a heavy, slime-slick hop toward the nearest shelter, which happened to be Lord Redmond&#8217;s highly polished boot.
Edward Curry darted into the room. &#8220;I&#8217;ll get him! Here, Froggie!&#8221; He was on all fours crawling likewise in the direction of the young Lord&#8217;s person.</p>

<p>The mayhem seemed to reign for an eternity. However, it had not even been one minute from the time that the office door had been flung open, that the warden of the escaped rascals appeared in its opening. The expression in her wide, startling lavender eyes was horror stricken. The dusty-rose color of her muslin day dress was a slight shade darker on its puffed-sleeves and modestly scooped and ruffled neckline where it settled over her bosom. It seemed that she had suffered for the spill that had ruined her ward&#8217;s own ensemble.</p>

<p>The high waistline of her gown, cinched with a drawstring, gathered the material around her petite form to emphasize the neatness of her ribs and waist. It likewise betrayed that most of her five-foot-three-inch height seemed to be made up of legs that were not quite visible through the sheer muslin of her gown and its shift beneath. The peaches and cream complexion of her skin was broken only by the single, silver necklace that she wore, weighted by a hammered and delicately engraved heart-shaped pendant between the rise of pleasantly full breasts. It was an almost girlish piece of jewelry for a female who had clearly reached and surpassed the age of maturity. Her thick hair, a deep, chocolate brown in color, had been tamed into a mountain of spiral curls and piled high on her head to be held there by an army of invisible pins. A few had escaped their prison for Delilah&#8217;s scamper after the children and had fallen to kiss the nape of her neck, and to frame the softly rounded features of her forehead and cheekbones.</p>

<p>At any other time, one might have found themselves distracted by her beauty. The only thing distracting about her in the current moment, however, was the mad scramble she made to try to repair the irreparable damage. &#8220;Mr. Curry, I&#8217;m so very sorry. There was glass and I had to tend to — Mae, love, please don&#8217;t cry.&#8221; She lowered to a squat to look at the girl at eye level, swiping her thumbs across the child&#8217;s wet cheeks. &#8220;I&#8217;ll get him for you. Eddie, do STOP!&#8221;</p>

<p>Her exasperation was evident. Delilah hitched her skirts to free her knees to the ground, exposing a smooth length of ankle and leg as she began to crawl in the direction of the boy and the frog — Mostly the frog. &#8220;Eddie, I&#8217;ll shoo him toward you, be ready to catch him yes?&#8221; That this order was given practically from between the legs of her boss&#8217;s client seemed to escape her notice until she lifted her head and a pair of lavender eyes met storm-cast blue. &#8220;Oh&#8230;&#8221; Color flooded her cheeks, and she held up a single index finger in the universal sign for &#8216;one moment, please&#8217;.
"Now Eddie!" She slapped her palms against the polished wood of the floor. Froggie cooperated and hopped right into the chest of the red-haired culprit.</p>

<p>The woman made a whispered sound of triumph and backed up on all fours to a place where it was safe enough to unfold to a stand. One of her long locks had escaped and awkwardly dangled near the small of her back. The rest of the pile seemed to have slipped off balance to the side of her head, and she looked as if she were wearing a hat fashionably askew.</p>

<p>&#8220;There, we&#8217;re sound now, aren&#8217;t we children?&#8221; She finally looked her employer in the face. &#8220;I do apologize.&#8221; It was said as politely as if a disaster of epic proportions had not just unfolded before her. But she could feel the gathering storm. Damn Edward Morgan Curry to the blazes.</p>

<p>Mr. Curry&#8217;s pale face began to color, as too did his ears and the entirety of his balding head to the point the red hue surpassed his children&#8217;s hair in intensity of color. The only thing left of Mr. Curry&#8217;s pale features seemed to be the pinch of skin where his lips had drawn into a tight, thin line. &#8220;Apologize?&#8221; He repeated. With the release of that one word, the floodgates opened. &#8220;No, no. I apologize — pardon, Lord Redmond —&#8221; He pushed to a sudden stand, and Mae&#8217;s tears threatened to burst anew. &#8220;Rooms!&#8221; One hand shot to point a finger at the door while the other banged a fist against his desk. &#8220;Rooms NOW — both of you!&#8221; They obliged with their flight.</p>

<p>Delilah tried, but could not constrain the flinch that manifested for the raising of his voice and the impact of his fist. She settled for letting her eyes close for a few moments against the rising tide of rage that she could feel about to be released her way.</p>

<p>&#8220;Is it so difficult?&#8221; Mr. Curry asked, a thick, purple vein pulsing in his temple. &#8220;What else have you to do with your day except to keep them from entering this single space? They could have the run of the bloody house if they do not kill themselves before their mother makes it home. It has been a month of you floundering the one damned task you were hired for!&#8221; His voice raised to a shouting volume, his fist hammering again on the desk. &#8220;And here I stand embarrassed in front of my client for your incompetence — <em>Again!&#8221;</em></p>

<p>Delilah stood straighter beneath the torrent that washed against her. She knew by the second sputtering sentence that it was over for her. There was nothing that mattered to Mr. Curry more than the favor of the Elite and the prestige that he could garner by making himself indispensable to them. That the story of this incident might be told and retold in social gatherings to his detriment must be burning a hole into his black, cheating soul.</p>

<p>She folded her hands into fists at her side, as if that act alone would give her the self-control not to belt out her rebuttal in turn. What had she to lose? She had already lost her position, and without a reference, she was as good as unemployable. She could not return to her cousins. They were the ones who had shuffled her off to the Curry&#8217;s once they had determined that she had not taken on the marriage market. At twenty-two she was now solidly on the shelf, all hope lost for making a respectable match without a guardian to present her or a fortune to lure a husband if all else failed. A poor orphan ward of new money merchants with no inheritance of her own was not going to land the sort of fish that her cousins wanted to lure into the family.</p>

<p>It was not that she had lacked for offers, but they had mostly come from youths who had been smitten by her with calf love. Those young lords who would have been her only hope for honorable establishment were herded as far away from her as their mothers could manage, once it was determined that she was not a match who would improve their estates. The older lords, who had little need for an inheritance as a lure, were often already burdened with wives and were seeking a mistress. Delilah had heard of such women, had even seen them in passing on her evenings in society during the year of her come out. They were recognizable for their stunning beauty, and a certain carelessness for the dowagers of society that she rather envied. Yet, she had seen in the eyes of some, a deeper, secret regret and emptiness that had left her feeling sorry for their fate. They would never know what it was like to be valued as the most important woman in the life of the man that they loved. Delilah had not been willing to settle for that estate. Not when she was nineteen and still had a hope for fate to send her the knight who would save her from the darkness threatening to consume her life. How naïve she had been.</p>

<p>Now, as the thundering storm of Mr. Curry&#8217;s rage poured over her, she felt the first grip of dread squeeze on her heart. She was an unemployed female, independent and without skill beyond that which might be used to educate and tend the children of the nobility. It was very likely that she would now be unable to find employment in that area with anyone who was reputable and to be trusted. She knew well the world in which she was living, and the fate that loomed around the corner.</p>

<p>Mr. Curry breathed in through his nose, his wide nostrils flaring as he roared, &#8220;You are DISMISSED, Delilah!&#8221;</p>

<p>The blood drained from Delilah&#8217;s face when he spoke the words of dismissal, and the soft fullness of pink lips trembled a few heartbeats before she firmed them to a steadier line. She would not let him see her break. All she had left was her pride.</p>

<p>&#8220;You will not expect a letter of reference for the poor sod who might think to pity you agai —&#8221;</p>

<p>&#8220;Vitali,&#8221; Lian interrupted, his expression unchanged. Delilah almost startled for his interruption. She seemed to have all but forgotten that he was there for his statue-like stillness and silence. It was she who had held his attention, in the quiet study of grey-blue eyes that drifted over her face and neck.</p>

<p>&#8220;What?&#8221; Mr. Curry spat.</p>

<p>&#8220;Vitali. The name.&#8221; Lian lifted a hand to indicate the documents on the table. &#8220;If you will kindly finish signing the paperwork, Mr. Curry.&#8221;</p>

<p>&#8220;I —&#8221; Mr. Curry frowned and seemed briefly confused. For a moment, he looked lost in a haze. Then the color drained from his face, and he lowered back into his chair to pick up his quill. &#8220;&#8230;Of course.&#8221;</p>

<p>Delilah watched the Lord for a moment. All that she could recall of him was that he had had the most piercing blue-eyed gaze of anyone that she had ever met. That he was used to authority and had little care for theatrics could not be more evident than in his return to the business at hand, as if he had not been privileged to a show of the highest drama. That he had borne witness to her crawling on the floor like a parlor maid, that she had found herself scandalously positioned between his knees, and that he had just been entertained by the spectacle of her dismissal was almost more than Delilah could bear. There was something about the man that made her beyond embarrassed for the degradation that she had displayed and experienced before him. It was no wonder that she had not been taken on the marriage mart. She had no sensibility for how to go on around a gentleman. He must have thought her a veritable loose hat.</p>

<p>Mr. Curry had made it clear enough that he had no further use for her, and his client had turned the matters at hand back to business. There was nothing for it now but to leave, both the room and the premises, she supposed. She had exhausted her charity welcome. Delilah uncurled her fingers and slipped them into her skirts, preparing to lift them to aid in the swiftness of her departure.</p>

<p>She had taken all of two steps toward the door when Mr. Curry&#8217;s client spoke her way, &#8220;And I should like you to wait a moment, if you please.&#8221; Lian&#8217;s tone was gentler, a poor match for the solemn composure of his expression. For all the power he could have used to keep her rooted to the spot, he made only the polite request, chased with what was meant to be a reassuring: &#8220;It seems you have no more pressing matters to tend for the household.&#8221;</p>

<p>Delilah brought herself to a confused halt. It was so unexpected that she had to turn back to look him in the face to be sure that he had in fact been speaking to her. She didn&#8217;t know if to be more offended that he had seen fit to address her directly without introduction as if she were some mere servant and not a hired governess who was still considered a lady, by society&#8217;s standards, or that he had been so insensitive as to publicly speak of her dismissal with no respect to her private shame. For both, Lian had a stormy lavender gaze directed to his own, before she lowered them respectfully to indicate her submission to his greater authority and power over her person in the circumstances. An even spoken, &#8220;m&#8217;Lord&#8230;&#8221; would be all he had at first, even for the gentleness of his observation and request, but she stood still, awaiting his attention for whatever purpose hers was being sought.</p>

<p>The Lord turned his attention back to Mr. Curry, who had begun to complete the documents with a mechanical sort of rigidness. &#8220;Once the paperwork has been taken to the courthouse and a notarized copy delivered to my mansion, I will be pleased to send a monetary expression of my gratitude for your&#8230; professionalism.&#8221;</p>

<p>Lian spent a moment watching the lines of ink dry before he offered, seemingly to the air in front of him, an unhelpful, &#8220;Your dress is wet.&#8221;
Delilah stared for a few moments at the profile of the blonde noble. Had he quite lost his mind? He was handsome enough to avoid being locked away, if so. That must be why he was still wandering around conducting business with the likes of Mr.Curry — which, by the by, had not raised him in her esteem in the least. The lawyer was a sham artist and all the world knew it.</p>

<p>&#8220;I&#8217;m aware, sir. Young Edward broke the reptile habitat. We are fortunate it was only the frog that escaped.&#8221; There had been a snake in there. &#8220;There was water&#8230; and mud,&#8221; for obvious reasons. &#8220;I do hope we spared the finish on your boots an assault.&#8221; There may have been a hint of the facetious, there, but Delilah felt reckless. She was no doubt about to be cast out onto the street, what harm was there to be had in making sport of the young blood?</p>

<p>&#8220;It does suit that there would be a reptile habitat in this home,&#8221; Lian said. His eyes were on the paperwork, but he felt the storm rolling from her. &#8220;I believe I can spare the boot.&#8221; He had not even thought to look at it, so far and away was his care.</p>

<p>With Mr. Curry&#8217;s final, flourishing signature on the paperwork, the Lord unfolded to a stand. Finally, Delilah had the full of his attention, and he studied her as if they were alone in the room. His gaze traveled the soft lines of her face only and came to a lingering rest on her lavender eyes.</p>

<p>Delilah had barely avoided taking a step back as he unfolded. He was so tall. His clothes fit perfectly and showed a lean but toned body off to perfection. As she observed the features that seemed to be cut like marble, she found herself thinking that out of his clothing he would not be far removed from the beauty of Roman sculptures. His hair was almost shining, like a golden halo above the depth of his blue eyes; eyes that traveled over her own features with such an intensity of focus, that it was almost like the touch of a hand on her skin. Without thinking, she reached up to brush at her cheek to whisk away the feather of his touch that her mind instigated.</p>

<p>&#8220;I apologize,&#8221; Lian continued. &#8220;I am inclined to curtness.&#8221; Particularly when leashing the authority his words could have. He was out of practice for niceties. He dipped his head in a slight bow. &#8220;I had no intention to cause offense.&#8221;</p>

<p>Well, he had a very nice manner when he put himself out to try, Delilah supposed. She offered him the ghost of a curtsy, and a polite, &#8220;None taken&#8230;&#8221; in a blatant lie. Despite the grimness of the hour, the impish humor that had smitten more than one young lord caused her lavender eyes to dance. &#8220;Although you are inclined to curtness,&#8221; she said, blithely. &#8220;It is not at all the thing to point out to a <em>lady&#8230;</em> her faults.&#8221; She immediately spoiled the soft emphasis she had placed on the word &#8216;lady&#8217; with a quiet curse when she discovered the length of a weighty lock brushing against her waist. &#8220;And I used a devilish number of pins too.&#8221; She had all but forgotten the Lord, now, in her efforts to wrestle her hair back into order.</p>

<p>Lian lifted his head, and it was the moment that blue met lavender again that he heard the first, soft trill of a wooden flute rising in his blood. The sensation was gone as quickly as it had emerged, leaving nothing to show for it but a pinch in his brow, faint though the shadow was. His eyes narrowed, and for a moment he seemed to be glaring. He let his study lower from her face, trailing down her neck to the glint of her silver necklace, while she set about righting her hair.</p>

<p>&#8220;I am, unfortunately, less than well-versed in how to avoid causing further offense,&#8221; Lian offered slowly, speaking to her locket for the distraction the silver offered. &#8220;I am in possession of a large estate, and my housekeeper has been asking for an assistant. I understand it might be presumptuous on my part&#8230;&#8221; He caught himself, lifted a hand to his brow, and then shook his head.</p>

<p>&#8220;&#8230;This is not how this done. Please,&#8221; He lowered into a deeper bow. &#8220;I am Lian Redmond. The excitement has rather thrown me off, I am afraid. I should like to apologize properly if you would be inclined to join me. There is a small restaurant not far from here. I am sure your dress will have time to dry from here to there in the carriage ride if it would suit you, my Lady.&#8221; He turned slightly to draw his leather portfolio from Mr. Curry&#8217;s desk. &#8220;Our business seems concluded, in any case.&#8221;</p>

<p>&#8220;Yes, Lord Redmond,&#8221; Mr. Curry said, sounding as though his tongue had grown three sizes in his mouth. &#8220;I will have the papers sent to you.&#8221; Then, as if struck by a moment of clarity, he finally acknowledged the woman. &#8220;Delilah&#8230;&#8221;</p>

<p>If he meant to say any more than that, a sharper look from Lian seemed to cut him off again. &#8220;If not to the restaurant,&#8221; the Lord continued. &#8220;I will be as&#8230; pleased to escort you to your destination.&#8221;</p>

<p>Delilah tried to follow the man&#8217;s conversation. First, there was a job offer and then a meal offer. Wasn&#8217;t that bordering on scandalous to be seen alone in public with a man who was not her husband? But who was she afraid of offending? What hope had she for any traditional alliance at this point? And if she had needed any reminder of how dire of a situation she was facing, it came in the moment that she realized she would have no destination to which she could be escorted. The closest place that she could rent a room that was not in a house of ill repute, would be the post-coach inn, and she could ill afford more than a night or two before it became obvious that she had not purchased a ticket for travel. She was, frankly, out of options.</p>

<p>The employment that Lian Redmond seemed intent on offering was the only thing that would keep her off the streets. If that meant suffering the disapproval of a society she no longer needed to impress, then so be it. She didn&#8217;t know why he would want to employ her after the disastrous spectacle that she had put on display. The almost too quiet to be heard whisper of her conscience contradicted that claim. There were very few reasons that handsome, well-to-do gents would employ a woman without references, especially after witnessing what he had seen. Was this to be the beginning of her end, then? If she left this house with Lord Redmond, she knew beyond the shadow of a doubt the stories that Mr. Curry would tell. It would be the end of her place in respectable society. The fact that Mr. Curry fell back into silence after only a look from the Lord served as a final reminder of whose will and desires would carry the most weight in the scenario.</p>

<p>&#8220;I&#8217;m very pleased to meet you, Lord Redmond,&#8221; she responded, &#8220;I am called Delilah Flowers&#8230; And I assure you that I had no choice in my own last name.&#8221; She had been teased mercilessly over the years for how very countrified and unsophisticated a name she bore. It was nowhere near as elegant as the society names that spoke volumes of the pedigree and money behind their lineage.</p>

<p>&#8220;I shall be honest, sire, in admitting that when I leave these doors, I am quite without a destination to head to, save a coach house, and it would be quite inappropriate for me to be taken up into your carriage, much less accompany you to a public eating house alone.&#8221; Her lavender gaze searched his face, briefly, curious. Surely, he knew these things? Or was it perhaps only a world of manners drilled into the women of society. Men had little care for the rules, she found. It was up to the woman to preserve her own reputation.</p>

<p>&#8220;I suppose it would be safe to say, that the only way I could decently accompany you from this residence, would be as a member of your employ,&#8221; she finished. &#8220;So if it is acceptable to you, sir, and your offer is sincere, I should much rather be taken directly to meet with your retainer, and to discuss the terms of my employment.&#8221; She met him directly with a look, then, as if daring him to try to take the last vestiges of respectability that she had from her grasp. Delilah was certain that Curry would make it his business to destroy her reputation anyway, but it was worth the try to salvage what she could for appearances.</p>

<p>Lian was still watching her as he had with that quiet intensity through the whole of her speech. He was silent as if listening for something hidden beneath her words. If he found anything, it did not show on the neutral expression he wore, but he slowly offered a faint twitch at the corner of his lips, like a smile.</p>

<p>&#8220;I suppose you are correct, my Lady.&#8221; The rules seemed to grow stiffer as the centuries passed. For all the brides he had taken, few, if any, had been claimed under any sort of guise of social etiquette. &#8220;I was quite sincere. I am sure Alice will be pleased to have the assistance&#8230; and you will find my household free of children and frogs.&#8221; As if those were perks of employment. Lian frowned and cast a brief glance to the desk before he addressed Delilah Flowers once more.</p>

<p>&#8220;&#8230;Madam, it occurred to me that you might have some belongings to collect. If there is anything that you might wish to carry with you for the trip, please do so. Should the terms of your employment be acceptable, I will be pleased to send a carriage to fetch the rest at a later time. For now, I will have my carriage brought to the door for you.&#8221;</p>

<p>He dipped into a bow again and extended a hand to encourage her to the door. &#8220;I fear I had one last matter of business with Mr. Curry that has come to mind, but I should not be much longer than a minute.&#8221;</p>

<p>Delilah dropped into a deeper curtsey. That she had found so fortunate a turn of luck given the situation seemed nothing less than miraculous. Certainly, if by nothing more than appearances, Lian Redmond seemed to be exactly what he appeared to be: a godsend in the nick of time. &#8220;I do not have much more than can be packed into two bags, my Lord,&#8221; she answered. &#8220;I will see to packing those and saying goodbye to the children. Then I am pleased to leave with you.&#8221; It was not the fault of the children that they were so terribly without training. With only a quick look back in Mr. Curry&#8217;s direction, Delilah made her escape from the study, and, it seemed, from the lawyer&#8217;s employ. What lay ahead for her, she could only guess at, but at least there would be no frogs.</p>

<p>Lian watched her go, or, more accurately, watched that swinging curl bounce down her back as she left the room. He turned his attention back to Mr. Curry. What business was attended to and whatever was said, was left behind those closed doors when Lian made his own exit. The only thing that seemed assured was that Mr. Curry never spoke a word against his former nanny once she had left his employ.</p>

	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="6-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter VI.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="8-link">Chapter VIII. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
