<div class="row">
	<div class="col-xs-12">
		<h1>Chapter VI.</h1>
		<hr>

		<p>A pair of shadows moved through the moonlit trees at a lazy pace, almost as if they would rather not be walking at all. A large, black stallion with a single white sock that seemed to flash an alert to the world around him walked a shoulder&#8217;s length ahead of a smaller bay mare; each with their rider comfortably, if in the case of one of them, inappropriately, astride. The quiet murmur of conversation and the occasional burst of soft laughter had been the only sounds beside the crunch of twigs and leaves underfoot that disturbed the peace of the early night as the moon rose past the horizon to brush the canopy of the trees. The gradual thinning of the forest was almost imperceptible at first, but soon enough it was impossible not to notice the wide emptiness of the coach road as it meandered through the countryside toward Easthaven.</p>
		
		<p>The first golden twinkling of the warmer gas and lantern lights began to replace the stars in the distance, growing denser the deeper into the town that could be seen. Out here, however, on the fringes of what might have been called the town, there loomed only the solitary shadows of larger estates: many of them the country homes of the wealthier London set. It was for this reason, more than any other, that most of the homes were shadowed in darkness. The estates were locked up while their owners enjoyed all of the social delights the town had to offer. There was one, however, that was clearly occupied. Soft light filtered through the ground floor windows, and a lazy slipstream of smoke drifted from one of the gothic-styled chimneys.</p>
		
		<p>Dorian drew the reins of his mount in, bringing the stallion to a stop at the side of the road. &#8220;How are you holding up, Joanna? I&#8217;ll admit it was a longer ride than I was anticipating&#8230;&#8221;</p>
		
		<p>&#8220;I have survived thus far.&#8221;</p>
		
		<p>He flashed a faint smile. He was used to the carriage pace and ease of access. The forest trails had been slightly more treacherous to navigate for lack of use. The way had been winding; enough so that they had been out, he was certain, for well over an hour. It would take just as long to get back unless they chose to ride the coach road. The first whisper of unease tugged at Dorian&#8217;s mind before he ruthlessly submerged it beneath the memory of his enjoyment of the ride. It had been worth it for the experience alone. Joanna filled his senses, taken as she was, out of the shadow of the hothouse. Her pale skin had been almost translucent in the moonlight, and her eyes as bright as the stars for her enjoyment. He&#8217;d had to stop himself from watching the fullness of her lips as she talked, and had spent most of that ride trying to find ways to make her laugh. Mostly, she&#8217;d just laughed at how unfunny he was. She never quite appreciated his flamboyant flirtatiousness the way others did. But now, she was about to cross into his territory, the place that he had made his home. Her presence there, alone, was close to unsettling.</p>
		
		<p><em>&#8220;Regarde ça!&#8221;</em> Joanna&#8217;s exclamation escaped the moment that her eyes found his manor. Distracted, she let her gaze drift over the spires and those designs from an age and country that she had left long ago.</p>
		
		<p>&#8220;We won&#8217;t be long,&#8221; Dorian said. &#8220;In and out, unless you need a cup of something to warm you up a bit.&#8221; The shadows of the forest and the cooler winds coming off the river meant that without correct riding gear, it would be easy to get chilled. &#8220;I should have a sachet of tea in there&#8230; somewhere. William won&#8217;t abide a residence without tea, even if I rarely sit to table.&#8221; Why would he? To enjoy solitary dinners and breakfasts? No. He&#8217;d made his peace with being a regular at the various eateries and restaurants in town. He was a favorite in most of them, and it made for easy hunting when the sting of his deeper thirsts needed to be quenched.</p>
		
		<p>In and out, he said, and Joanna&#8217;s smile faded slightly for the brief flutter of disappointment. For as quickly as that emotion had risen, she felt the slow, solemn rise of the older song in her blood to remind her that shame was likely the more appropriate feeling. He had mentioned tea, but for a moment he had to endure the quietly passive expression that she wore around the others. Tea.</p>
		
		<p>&#8220;Ah.&#8221; She shook her head and lowered her hand from the reins to the puff of skirts bunched between her thighs. That she could not ride sidesaddle had meant a journey through the night with her legs bared to the elements. If she had noticed the cold at all through their ride, she had been too distracted by her present company to worry for it. Aside from discomfort, she had little to fear from being chilled. Truly, there was no need anything to warm her up, and she did not admit that tea had never ranked high among her beverages of choice. In the end, however, the woman turned her smile on him. &#8220;I could do with tea.&#8221;</p>
		
		<p>Nudging her mare forward, Joanna offered a quieter assurance, &#8220;I have not seen the houses out of town.&#8221; The homes of the wealthy, so far from the general populace, were not hunting grounds. There would be no fear, at least in her mind, that they would be seen by the queens about town. &#8220;Your home&#8230; The style is from France.&#8221; Even if she had never seen the cities of her homeland in person, she knew something of its architecture, and that it had birthed the gothic style. &#8220;One day, when I can see the sun, I would like to go to Paris.&#8221; She glanced over her shoulder his way. &#8220;For now, I will watch you make tea.&#8221;</p>
		
		<p>Joanna smirked, &#8220;Or find it. If it is only somewhere.&#8221;</p>
		
		<p>Dorian wouldn&#8217;t be able to help the grin that flashed white in the moonlight as he nudged a knee into the ribs of the stallion in response to her answer. &#8220;There are only so many places a sachet of tea could hide; even in so inhospitable a residence as my own. You have my assurance that if it cannot be found in a reasonable time, we shall dispense with the nicety.&#8221;</p>
		
		<p>The stallion stepped forward onto the road and paused long enough for the mare to come abreast. The two crossed the emptiness of the coach road side by side and then turned aside to begin the walk up the gravel drive to the front door of the house. &#8220;I had not realized it was a French style in origin,&#8221; he admitted belatedly and openly, despite it showing his lack of knowledge. &#8220;I have tended to follow the Italian and Spanish sensibilities in the past.&#8221; For obvious reasons. He glanced over at her with a slight smile, then. &#8220;But I am finding there is much to be said for the French. They produce masterpieces. I shall endeavor to pay closer attention.&#8221;</p>
		
		<p>Looking away, he gave her no time to respond to his comment and swung down off his mount in a single graceful movement. &#8220;Here we are. Allow me to help you dismount.&#8221; Not that he thought she would not be able to manage on her own, but his desire for an excuse to hold her closer than permitted was not to be denied. At the side of her mount, he reached out a hand and rested it lightly on her hip in anticipation of supporting her while she navigated both legs to his side of the horse.</p>
		
		<p><em>&#8220;Merci&#8230;&#8221;</em> Joanna murmured, sliding her feet from the stirrups. It took her a moment to adjust the folds of her dress, hiking the hem up over her knee so that she could lean forward and swing her leg over the mare&#8217;s rear. Her hood fell away to reveal the concentration on her face with the movement. A moment later, she slipped into Dorian&#8217;s support.</p>
		
		<p>Dorian suddenly wasn&#8217;t sure why he had thought helping her dismount was a good idea. The soft roundness of Joanna&#8217;s hips was in his face and then against his chest as he reflexively brought his second hand onto her waist to hold her steady. Then, he was lowering her in a slide down his body that was a much a torment as it was a pleasure. &#8220;Easy does it,&#8221; he murmured. He was almost unaware of the moment when her boots touched the ground, distracted as he was by the glimpse of the column of her throat. Her blonde hair seemed to be shining silver in the colorless night, and her perfume - orange flowers and vanilla - wrapped him in a snare that was almost impossible to resist. Lust slammed him in the gut like a sledgehammer, and he felt his fangs elongate slightly for his sudden, impulsive desire to claim her.</p>
		
		<p>Joanna had thought nothing of the dismount beyond reaching the ground, until the moment that her back was against his chest. His heartbeat was a quiet, steady percussion, echoing through her beneath the course of Lian&#8217;s song in her blood. It was Dorian&#8217;s tempo she felt quicken, along with a sudden, instinctual awareness that a rabbit might have for crossing a fox&#8217;s den.</p>
		
		<p>Dorian let his hands fall away, barely controlling the urge to jerk them back as if burned. She was not his to claim, and that realization was another hammer blow to his mind and heart. He turned away toward the house, so that she could not read the betrayal that would be etched into his features. &#8220;We shall want to be quick about it. The night is escaping us.&#8221;</p>
		
		<p>The last thing he needed was to have Joanna in his company all night. There would be no explaining that one away. &#8220;You can leave the horses. I&#8217;ll have William tie them off.&#8221; The Butler was only a bell tug away, day or night.</p>
		
		<p>Joanna pretended, convinced herself, that she had only imagined what she felt. The rise of the song in her blood washed over her disappointment and left only the sense of guilt for what she had, in that moment, wanted to be true. She felt her blood rushing to her temples, leaving a panging in her head that caused her expression to pinch. She hid her face against the coarseness of her mount&#8217;s neck and slid her hand against the bay&#8217;s muzzle. She distracted herself with praising the horse in French and touching her nose to the velvet beneath her fingers. Once she felt steadier, she offered it an easy going, "You heard the man. <em>Attends ici."</em> With that, she turned on her booted heel to fall into step.</p>
		
		<p>For a moment, her eyes were on Dorian&#8217;s arm, before she decided against the more feminine urge to loop her own, there. &#8220;You said it was inhospitable&#8230; It cannot be so,&#8221; she said, as she folded her arms in front of her where they would be safe from her own inclinations. &#8220;Although I admit, if there were to be place for our kind to settle, Gothic architecture all but screams it.&#8221; A beat. &#8220;You do not have guests often?&#8221;
&#8220;Mortal women, sometimes. Long enough to feed and pay them well enough for the service.&#8221;</p>

	<p>Joanna&#8217;s smile retreated to the neutral mask of passivity. Of course, there were mortal women. For all the grandiose charm she had ever been pleased to call him out on, there would be mortals melted by it. Warm bodies to fill those needs that a man had, even beyond what their curse demanded.</p>
	
	<p>Dorian didn&#8217;t know why he had said it: perhaps in the effort to distance himself from the potency of what he was feeling, and in frustration for what he could not have. He was not without his share of lovers amongst the barmaids and servants whose honesty he could appreciate more than the plastic façade of the matchmakers&#8217; daughters. It took no certain measure of skill to avoid being trapped into an actual marriage when you were young, as rich as the devil and in possession of a certain &#8216;something&#8217; that made the damsels shiver just to look at your features. He&#8217;d had that one as a quote from a reliable source. It had been easier, and safer to play the game among those who had no expectations of ever being truly loved or wedded. If Dorian had ever felt a sense of shame for the habits, they had faded over the centuries. A man had needs, and he had no bride to claim for his own.</p>
	
	<p>The thought produced a pang of regret for the tone that he had taken, and he qualified his response further. &#8220;&#8230;The occasional card party, and Lian comes by when he gets tired of having to be polite.&#8221; That last was a drier observation. &#8220;But I have never been averse to my own company.&#8221; He glanced her way. &#8220;Or yours.&#8221; He could be that honest, at least.</p>
	
	<p>She met his honesty with a quieter smile and lowered her head to distract herself with the brooch pinning her cloak to her.</p>
	
	<p>The door swung open in near silence, and Dorian reached for the servant bell pull, offering a single tug that would no doubt startle William awake from the depths of the servant&#8217;s quarters. &#8220;I can take your cloak,&#8221; he offered. She would be too warm inside to keep it on with the low fire still going.</p>
	
	<p>&#8220;Too kind,&#8221; she said with the ghost of a tease as she drew the cloak from her shoulders. She kept her fingers curled around the brooch but handed him the fabric.</p>
	
	<p>Almost as quickly as Dorian had pulled the bell, William made his prompt appearance, managing to look at once as if he had been aroused from slumber, and yet somehow presentable to take on his duty.</p>
	
	<p>That his butler had appeared within moments of being called, somehow dressed in enough layers for service, struck Dorian as amusing. &#8220;Surely, I have not reduced you to sleeping fully dressed with my nocturnal habits William,&#8221; he teased.</p>
	
	<p>The butler held an extended arm to receive their outer garments as they came off. &#8220;Not at all, sire,&#8221; he answered blithely. &#8220;Were you already abed I assure you I should have been entirely less prepared to spring to your service.&#8221; The two men had an informal relationship, for all that William knew of his master&#8217;s secrets. &#8220;But the carriage had not yet returned. My evening does not begin until yours ends. How may I be of service m&#8217;Lord?&#8221;</p>
	
	<p>Dorian answered promptly &#8220;Tea, William, is how you may be of service. We have been in the elements for some time and have a need to warm up. And see to the horses, we are uncertain of how long we will be staying.&#8221;</p>
	
	<p>William cast a curious look Joanna&#8217;s way. The woman was quite obviously a lady and not one of his master&#8217;s usual fare for visits at this hour of the night. But who was he to judge? &#8220;Certainly, my Lord. And where do you desire service?&#8221;</p>
	
	<p>&#8220;My study. Thank you, William.&#8221; That was where the journals were located, and that was, after all, what they were here to retrieve. &#8220;My Lady&#8230;&#8221; That was his polite invitation to fall in at his side to be escorted to the study, even as William melted out of sight with a final bow.
&#8220;He moves more quickly than I do,&#8221; Joanna observed dryly. She remained at Dorian&#8217;s side as he led the way to their destination but broke away almost immediately to occupy her hands with exploring his space. Whatever knickknacks she found there she had little shame in touching, even if she was just as careful to put them back in the same place she had moved them from.</p>

	<p>Dorian was glad for the distraction of searching for the journals. He stood behind his desk, shuffling papers aside in a drawer as she explored the room, and reached in to withdraw two leather bound journals tied together with a red ribbon. That they were bound together as if already prepared for a gift, was not something that he would give voice to, or to the fact that they had clearly been designed with a feminine owner in mind. It was there in the gilded trim and ingrained design of a sprawling oak tree. That Dorian had purchased them as a gift for her, that he had never found the boldness to finish the exchange, and that he had never written in a journal or diary in his more than half a millennium of life, he would never admit.</p>
	
	<p>It seemed as if she had forgotten the journals were the sole purpose of the visit since she was willing to let Dorian go digging for them while she occupied herself with his belongings. She rolled a glass paperweight between her palms as she looked over his desk. The gift box, although buried beneath a stack of paperwork, gave her pause. She&#8217;d had to ask Ayla to pick up a box in town for the collection of loose poetry she gave him. &#8220;You enjoyed them?&#8221;</p>
	
	<p>She caught him by surprise in discovering the gift box. He&#8217;d forgotten that it was in this room. Looking at it reminded him of Lian&#8217;s visit earlier in the week.</p>
	
	<p>He cleared his throat as he emerged from behind the desk. &#8220;Yes. I enjoyed them&#8230; continue to enjoy them. I find myself revisiting them often as my mood dictates.&#8221; He closed the distance to her side. &#8220;Your new journals, m&#8217;Lady, delivered as promised. You should have little need for another for a while.&#8221; He had selected the books for their high leaf count.</p>
	
	<p>&#8220;Thank you, Dorian!&#8221; She placed the paperweight down and extended her hands for the gift. She held the journals up, touching one embossed cover to her lips to breathe in the scent of parchment. It was not quite the same, aged scent that seemed to cling to the older of their brood, to Dorian, but it was a scent she loved. She did not question the ribbon. It was a gift; although her assumption was that it was <em>from</em> someone to Dorian went unspoken. The thought made it easier to retreat into the safety of the melody in her soul. &#8220;They are beautiful journals. I will try&#8230;&#8221; She lowered them, and although she did not unbind them, she spent a few heartbeats letting her fingers run over their edges. &#8220;&#8230;try not to crack the spines.&#8221; She hesitated, glancing toward the window. Tonight, of all nights, Lian&#8217;s song was doing less to comfort her.</p>
	
	<p>&#8220;Did you&#8230; know," She felt as if she had to hold her head above the chorus of solemn violins in her blood just to free the words from her throat. She huffed and seemed to find herself again, and that soft curve of a smile was more familiar when she looked his way. &#8220;The night sky is in love with the moon?&#8221; There was a brief crack of pink lips that showed a flash of white teeth before she reined the expression in. &#8220;Or, is in the poem I began. Of course, the sun and the moon in those old stories are always in love because they can never be together. I prefer it if the moon and the sky are lovers.&#8221; She tilted her head. &#8220;It will be the first poem in this book. Only&#8230; I have not figured out the words to their own tale yet.&#8221;</p>
	
	<p>&#8220;No, I did not know that the night sky was in love with the moon.&#8221; He smiled, the barest curve of lips. &#8220;But I can see why it would be,&#8221; he conceded. Joanna was as radiant in her muted way, as a moonlit reflection of Lian&#8217;s sun. That the sun and the moon were not lovers in her tale, he found to be more than acceptable.</p>
	
	<p>William entered the room at that moment, with a tray carrying a steaming teapot and two chinaware teacups on saucers. There was also a small pot of golden honey and a few sliced wedges of lemon. &#8220;Tea is served, m&#8217;Lord. Will there be anything else?&#8221; William sketched bow, setting the tray down on a side table that sat between two overstuffed upright armchairs near the fireplace.</p>
	
	<p>&#8220;Nothing else this evening William. You may retire. I shall tend to my own needs hereafter.&#8221; That those needs did not include bedding the pretty Lady was not information that Dorian felt obligated to share. What he did with his nights and with whom, had always been his own concern.
&#8220;Very well, m&#8217;Lord. Goodnight, Miss.&#8221; William had not missed the absence of a wedding band on Joanna&#8217;s finger. He withdrew as silently and efficiently as he had come.</p>

	<p>Joanna bowed her head in that quiet farewell, affording the butler a soft <em>thank you</em> in French.</p>
	
	<p>Dorian turned toward the chairs and tea and extended a hand to invite Joanna to be seated. He lowered himself to a seat once she was settled, and contented himself to let her play the role of hostess. &#8220;I am sure that it will be a marvelous collection and I expect to receive a signed collector&#8217;s edition.&#8221; He was teasing again, the tensions of moments past forgotten. He might not have tomorrow, but he was pleased to enjoy the night.</p>
	
	<p>&#8220;Ah, of course. I shall bind the clean manuscripts myself and steal a book with a nice cover from Raven&#8217;s collection. And&#8230; you will visit sooner to collect them.&#8221; Joanna had a way of making those demands, softening them with a smile even if she seemed to expect that her wishes would be followed. For all that she was a young, forgotten bride, there was some stubborn part of her that could act the queen. At that moment, she was a queen who was slipping down into a chair to enjoy what time could be stolen with Dorian — and ignoring those warning beats in her soul.</p>
	
	<p>The moon rose higher in the night sky, and the fire inside the country home grew lower. One cup of tea became two, and one topic of conversation became more than could be followed. In the depths of the night, the lilting melody of an accented voice reading poetry drifted around the room, and at one point all that could be heard was silence. Stolen moments could last only so long however, when their enemy was the dawn. Eventually, just as the moon passed the halfway mark of its descent into the eastern horizon, two shadows slipped from the entry of the house to find their mounts, and ride in silence along the empty coach road toward a gilded garden. Words were no longer necessary.</p>

	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="5-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter V.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="7-link">Chapter VII. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
