<div class="row">
	<div class="col-xs-12">
		<h1>Chapter XVI.</h1>
		<hr>

		<p>Lian&#8217;s song was heard throughout the coven even before the rumble of his carriage pulled into the castle courtyard. He bore no gifts for his brides tonight. The melody he played was no doubt an improvement from the solemn oboe that had indicated his slow withering of soul, but it brought with it a storm of apprehension that descended upon his brides. If it had been his choice, he would not have left his manor. If it were true that he only had a fortnight left of Delilah&#8217;s presence, he would have spent it all with her. Instead, he stepped out before the grand doors of his castle, his hands in his pockets. He hesitated only briefly outside of the doorway to compose his features. He could not control his song, but he could at least present a patient face when setting the boundary that would come. It would all but seal that he had taken a special interest in the servant whom Angelica had harassed, but there could be nothing for it except to be sure that they all heard the command for what it was. He entered in silence.</p>
		
		<p>The queens began to stir within the castle walls. Even in the basement where Joanna had tucked herself away, she could feel the call rising in her blood. She wiped her quill dry and placed it back upon her stand. Gooseflesh lifted on her skin, and she lifted her hands to rub her arms. Whatever the nature of Lian&#8217;s visit, he was not pleased. She could hear it in his song.</p>
		
		<p>On the small bed in Joanna&#8217;s hideaway lay another queen. Her hazel-green eyes widened as she stared at the ceiling. &#8220;Oh dear&#8230;&#8221; she murmured, pushing herself up into a sit. Her auburn hair had loosened from her upswept bun for her position, and along with the almost girlishly demure style of her muslin gown, her expression hinted at a youthfulness of mind.</p>
		
		<p>&#8220;His music is unpleasant,&#8221; Joanna said quietly as she rose.</p>
		
		<p>&#8220;It&#8217;ll be alright,&#8221; Noelle said, sweeping to her feet. She plucked up Joanna&#8217;s hand to offer a reassuring pat and then laced arms. &#8220;Come, let&#8217;s go. I&#8217;ve missed him terribly. Perhaps he&#8217;ll stay awhile this time.&#8221; Four days had hardly been enough time for all Lian&#8217;s queens to bask in his sun on that last visit, so long ago now.</p>
		
		<p>They were among the last of the brides to filter into the drawing room. For all that Lian&#8217;s song was thrumming and alive within their veins, he sat in his high-backed armchair with a familiar neutrality that spoke of the withering seasons. He did not rise to greet any of them, but his storm-grey eyes tracked each of the beauties as they arrived. They were a veritable garden, each one having once garnered far more than the distant affection that he carried for them now. In that moment, he regarded them as a weary father.</p>
		
		<p>One dark-haired bride came sweeping into the room. She had been an opera singer in her first life and remained ever the diva in her second. If she heard the warning of Lian&#8217;s song, she did not hesitate a moment before dipping into a low curtsy that revealed the pale expanse of her chest. &#8220;My Lord,&#8221; she offered, her red lips curving into a sharp smile.</p>
		
		<p>&#8220;Enough, Eva-bird,&#8221; Eden warned. She was in her underclothes again, watching the room from an upside-down position where she dangled her head over the end of a chaise lounge. Her legs were folded over the lap of the ebon-skinned queen. &#8220;He&#8217;s a little wrathy, in case you can&#8217;t tell.&#8221;</p>
		
		<p>Eva scoffed at the girl. &#8220;Well, then!&#8221; she huffed, lifting from her curtsy so quickly that the feathers of her turban began to flap as if they meant to fly away. Her attention shifted back to the blonde Elder. &#8220;It does none of us any good at all, Lian, to be so neglected by you unless we act the part of petulant children. We may get the idea that it is the only way to convince you to visit us.&#8221; If that attempt at humor had been meant to soothe him, she found herself faltering beneath the steady, blue-grey gaze that pinned her in response, and lowered into a seat.</p>

		<p>&#8220;Told you,&#8221; Eden sang.</p>
		
		<p>&#8220;Eden,&#8221; Lian&#8217;s voice was quiet.</p>
		
		<p>&#8220;Well, I did. And apparently, I was right. Bleedin&#8217; mad as a March hare, you are.&#8221;</p>
		
		<p>Efe stirred from beneath Eden&#8217;s lap and patted the girl&#8217;s knee as if she needed the assurance or at least the reminder to be quiet in the face of Lian&#8217;s warning. Efe&#8217;s darkness was in direct contrast of Eden&#8217;s paleness; they made an odd match upon the couch. Although the African had resigned herself to western fashions, she wore ropes of thick, beaded jewelry around her neck and wrapped her hair in turbans whose bright colors matched her gowns. Eden only grunted beneath the motherly shushing, and satisfied, Efe&#8217;s attention returned to her sire.</p>
		
		<p>Shar made it a point to be the last to arrive. This encounter was, after all, a moment of near triumph. It had been her subtly planted seed of an idea that had led Angelica to breach the sanctity of Lian&#8217;s boundaries. The Elder himself would be the only other who would have access to that knowledge, and then, only if he actually bothered to search it out in her mind. She found that she did not care if he did. She almost desired the pleasure that would come from knowing that he was aware that it was she who was behind his torment. But Ayla was right: a war was never won on a first salvo.</p>
		
		<p>The queen had only expected to create a rift between Lian and his bride for the intrusion into his domain. She had delighted to whip Angelica into a frenzy of desperation for the thought that her season was finally over with tales of the beauty of the hunt — even if that reality had long been in effect, despite the girl&#8217;s denial. The fact that the trophy he had been showing off on the hunt was in residence beneath his roof as a servant, had been a delicious bit of news that she had not expected. The &#8216;Lady&#8217; was a whore and not quite dead for the queen&#8217;s antics. Annoying, but it only meant that she remained a tool with which Lian could be tormented. From the sound of Angelica&#8217;s report, the younger queen had done as much as could be hoped in the situation — even more than Shar might have been brazen enough to do. She had always preferred a subtler approach in her games with the Lord.</p>
		
		<p>It would do Lian good to be reminded, or to be made to realize and acknowledge that for all his absence and detachment, he had given over quite a bit of autonomy to his brides. With those weaker bonds, especially among the eldest of his coven, Lian could only expect to be met now with near equals, rather than submissives; the result of the cooler and more distant relationships that had been established. It was that coolness and distance that Shar intended to exploit.</p>
		
		<p>There might be only one of Lian&#8217;s older brides who might prove impervious to the seduction of Shar&#8217;s game of the mind and heart: Celia. She seemed to be satisfied to reign as a matriarchal co-equal, treating Lian almost as a relative and the younger brides as her handmaidens, if with that icy, distant tolerance. Celia could prove an obstacle, and a major one, to her plans, but Shar had always loved a challenge. However, that was a battle for another day. This moment was for enjoying the fruits of her labor. When she crossed the room, she did not look in Lian&#8217;s direction, or at any of the women who were rising like blooms to unfurl petals of attention his way. Shar took a seat in silence and waited.</p>
		
		<p>Angelica hovered by the entryway. It was telling that she waited until Shar sat to find a seat near the older queen. Whatever comfort she took from her position, whatever protection she felt, her expression had shifted into one of quiet irritation — like the petulant child whom Eva spoke of. She gathered the folds of her gown in tight fists, as if it were a soft shield, before smoothing her skirts down again. She had no gift for hiding her expression, nor the sharp rise of woodwinds in her soul&#8217;s melody that called out a shrill defiance. He deserved nothing less than what she had done. That he would find a new toy, that he would abandon her after stealing her life, meant that she was within her rights. He deserved for that girl to be run off into the night so that he might rot alone in that damnable mansion.</p>
		
		<p>Once they all settled, Lian began. &#8220;I wonder if you all might indulge me a question.&#8221; He paused, as if half-expecting a response to his own, then continued. &#8220;I spare no expense. I give you jewels and fine dresses, a library, and gardens, a music room filled with instruments from across the world. I give you an entire castle and the run of the town to play at whatever games you might wish. Do I not give you all that is in my power to give, wrapped in eternity and youth everlasting?&#8221;</p>
		
		<p>Celia would be the one with the confidence and the lingering depth of bond strong enough to risk answering despite his displeasure. Her voice was as cool as the ice she resembled but carried no hostility. If anything, there would be an almost deliberate effort made to reach deep into her blood, for the oldest music Lian had known. It may have lost its power to move him to passions, but it was eternally familiar and an old friend for those years. &#8220;You give us everything the mind and body could ever need, Lian&#8230;&#8221;</p>
		
		<p>She had secured for herself a seat in one of the single armchairs slightly closer than the remaining furniture in the room to the place that Lian had chosen to sit; a fitting position for his first and oldest queen. Nadine, like a favored kitten curled at Celia&#8217;s feet, leaned with her slender, ethereal beauty against one armrest, and the older queen idly threaded fingers through the girl&#8217;s honey tresses.</p>
		
		<p>The silver-haired queen continued, evenly. &#8220;It is the one thing you cannot give us, that is coveted most.&#8221; Her steel-eyed gaze remained steady upon him.</p>
		
		<p>Lian frowned. &#8220;Yes&#8230; you are correct.&#8221; As Celia always seemed to be. He knew all too well that there was only one in the room to blame for their current state. They were all of them broken promises and his selfishness, placed in the gilded cage of his eternity. &#8220;I cannot give the heart which you desire. The fault falls to none of you,&#8221; he admitted, evenly. It was his curse that he had given them. &#8220;There is a measure of care to ensure that you want for nothing else. I have given all that I am able, but what I will not suffer is surrendering the single boundary that I have made. None in this room are welcome into my home without a direct invitation. I expect the same respect for Dorian&#8217;s manor.&#8221;</p>
		
		<p>Eden laughed, &#8220;Well, there is much to be said for independence.&#8221; Her knees slapped together.</p>
		
		<p>Lian&#8217;s attention shifted from Joanna, who had suddenly found a patch in her dress to be entirely too interesting at the sound of Dorian&#8217;s name, to Eden. &#8220;I know the want for freedom.&#8221; As he knew all too well that it was not worth the price. He settled, the ominous song echoing through his blood returning the mellower, winding stream of strings. &#8220;Such is why I will not tolerate an intrusion of the one space I have kept for myself. Even less will I suffer harm or the tormenting of the humans under my protection there. It is the only warning I will give.&#8221;</p>
		
		<p>&#8220;Of course, you would make such a decree, my Lord,&#8221; Angelica&#8217;s tone was all the sweetness that it had always been, but her face seemed harder for it. &#8220;When our new sister is still so warm within your walls. Whenever were you planning to introduce her to the family?&#8221;</p>
		
		<p>Celia lifted a brow and turned a slightly harder look to the younger queen. &#8220;You are young enough to be forgiven much, Angelica, but the disrespect of your Lord and our bond is not counted among that number. You would be advised to hold your peace, at risk of earning discipline.&#8221;</p>
		
		<p>&#8220;And who died and enthroned you Queen, Celia?&#8221; Shar bit out the counter-response almost as quickly as the silver-haired Elder had issued her correction. &#8220;We are bonds, not slaves. Angelica raises a valid question and we deserve a direct answer.&#8221;</p>
		
		<p>&#8220;This shyte,&#8221; Eden groaned, throwing her arm over her eyes. &#8220;It gets so old.&#8221;</p>

		<p>&#8220;Enough,&#8221; Lian said, but the word he spoke might well have been lost to the sudden slam like a wooden mallet against a gong that rang through their blood. &#8220;I have made my expectations clear, and they will be followed. As of now, I have no intention of bringing you a new sister. I have learned quite well that the only end to that path is another eternity of misery for all of us. Keep away from her, and be thankful you need only tolerate a mortal&#8217;s lifespan.&#8221;</p>
		
		<p>There was a moment of heavy and speaking silence after the Elder spoke those words, though if it was for the words he had spoken, or for the literal reverberation of his music that had caused the equivalent of ringing ears in his brides, was not clear at first.</p>
		
		<p>It was Sophie who uttered the thought that was likely in every mind. &#8220;So, she&#8217;s different&#8230;&#8221; The woman had almost said special. What was it about this mortal, that Lian would contemplate the giving of his attentions and comforts while taking no price in return? It was an opportunity that they all in their seasons would have given their very lives for. They had.</p>
		
		<p>&#8220;I am tired. I cannot give you what you like. Surely no one desires another in this castle. I am not unaware of what sentence I have given. If it is less a miserable eternity for all of us, then I would take it. That one might have my attention for a season and die an old woman, I thought would be a blessing. Such was a foolish thought. We can all remain miserable together, then.&#8221;</p>
		
		<p>Shar could scarcely keep her expression steady. Fool. Fool. Fool. He had just given her the very blade she needed with which to sever his throat. She offered no words, however, merely studied the blonde where he sat on the ashes of his kingdom. How little he knew of women, for all that he had constructed a garden hothouse of them.</p>
		
		<p>It was a soft sound, almost like a purr from somewhere behind the Elder that finally broke the silence that threatened to stretch on beyond comfort. Aziza&#8217;s presence would be revealed to Lian as much by the latent power that she exuded, as by her smoky voice when she spoke. &#8220;As our Lord has made clear, so shall it be done.&#8221; She was old enough in her own right to speak for them all. Lian required an acknowledgment of his decree, and now it had been given. The brides were bound by a mutual covenant of submission to their sire. &#8220;Now, if we are done with the &#8230;pleasantries of the day. I should very much like to remind myself of the reason I so willingly gave my eternity into your hands&#8230;&#8221; </p>

		<p>Aziza&#8217;s sinewy grace was almost serpentine. The dark tones of her skin shimmered as if it had a natural oiled luster and sheen to it, and the jade green of her eyes was a stunning contrast to that darkness. The coiled weave of her crown of hair, and the sensuous confidence with which she moved betrayed her age.</p>
		
		<p>Between Celia and Shar, there had been she of Egyptian blood. She had been a living mystery, royalty in her own right and all but stolen from her world, for the power of the notes she had evoked. Even now, hundreds of years later, the smoke and spice of the desert song flowed out of her soul to pluck at answering chords in Lian&#8217;s. &#8220;We have missed you&#8230; You tease us with your absences.&#8221; Long fingers trailed over the nape of his neck. They slid along his jaw, and a thumb skimmed his cheek. &#8220;My blood sings for you. I weary of these trifling games of the mind and would not waste these precious moments.&#8221; She lowered her head to touch her cheek to his. &#8220;Send them away.&#8221;</p>
		
		<p>Lian turned his face so that his nose skimmed her cheek. His hand lifted to capture one slender arm. Aziza. He could feel the promise of her song dancing beneath her skin. She smelled of spice. He remembered how she tasted of the wildness from which she had been stolen. Her song was just as chaotic: wild winds across desert dunes. It was not a song that he often indulged in past her season&#8217;s end, but he could feel his heartbeat synching to the tempo of her own. &#8220;Go,&#8221; he said to the others, speaking through the length of ebon hair that fell from the coils. He held her as the room cleared, his thumb brushing against the pulse he could feel in her wrist.</p>
		
		<p>&#8220;Aziza,&#8221; he murmured, once they were alone. He pulled back from her then, his hand lifting to skim a gentle touch to her jaw and his thumb brushing the fullness of her lips. For a moment, he was silent. &#8220;I cannot.&#8221; His blood was all but humming along with her wildness, but his heart was given to and craving another song. Delilah. He would not be the cause for her tears again, and he could not betray her, even for the short time that might be left. His smile was faint when he lowered his hand. &#8220;But I can assure it is not for any loss of allure or temptation that you weave.&#8221; He knew she did not need the reassurance. If there were any among his brides who had fully embraced her second life and the beauty and power that came with it, even apart from his song, it was his desert queen.</p>
		
		<p>Aziza didn&#8217;t need the assurance, no, but she had not lived the rhythm of his song for centuries to be so easily set apart. It was an easy, fluid movement that had the queen and her tangle of long limbs lowering into his lap. It was not an intentionally seductive motion, but there was little about the desert queen that did not drip with allure. </p>
		
		<p>&#8220;You are a man, Lian&#8230;&#8221; Her voice was still heavy with desert spice, &#8220;&#8230;and you think like a man. We are to be forgiven for the occasional urge to remove your head from your shoulders.&#8221; Aziza rested her brow against the Elder&#8217;s. &#8220;Be still, now, and do not speak. Turn your ears to wisdom.&#8221; Her long, dark fingers reached up to cradle his jaw. &#8220;You have made a terrible mistake, my bond.&#8221; The worry and affection she bore for him resonated quietly in her tones. &#8220;And it is the reason why I chose to claim you so very publicly.&#8221; Her breath skimmed his temples, followed by the touch of her lips.</p>
		
		<p>&#8220;The only peace we have in our shared suffering is knowing that there is something of you that is still our own. We have endured the ends of seasons, for the hope and knowing that there is a part of you that needs what only we can give. We are equals, your brides, in our pleasure and our suffering.&#8221; Her lips drifted over the sensitivity of his earlobes and she was distracted momentarily by a nibble. &#8220;The mortal. She is different&#8230; she will be different. She will share our pleasure and none of our pain. She will have enemies.&#8221; The queen lifted her head and looked him in the eye. &#8220;And she will have more if she is the reason that we can no longer hope for the one joy we have left.&#8221; She leaned forward and rested her lips against his. There was the ghost of sadness, in her kiss, and the spark of a desert fire under the stars.</p>
			
		<p>&#8220;You will cost your mortal her peace, Lian if your queens believe that all in your family have been cast aside. Were it not I, but another you had refused this night, it may have already begun.&#8221; She closed her eyes. &#8220;I knew that you would refuse me&#8230;&#8221; Her season had long since passed. It was the way of things. &#8220;But there are those in your bosom, as a viper, who would seek to turn the natural, to the unnatural, and use it to tear our family apart.&#8221; Her expression became suddenly intense. &#8220;If it is true&#8230; if she will be different, to keep her safe, Lian, you must take a queen again, for a season. More, if it can be borne. The coven must understand that the value of our eternal bond has not been diminished.&#8221; She grew quiet. &#8220;Do you understand what I am saying to you, Lian? To keep her safe, you must betray your heart for her.&#8221;</p>
		
		<p>It seemed a contradiction, what she advised, but with everything in her, she knew it to be true. If Lian wanted to keep his mortal, he would have to turn his face again, to a queen for a season. &#8220;Your song will find the one.&#8221; The queen in his garden, to whom he could turn his light. &#8220;And I am ever yours to command.&#8221;</p>
		
		<p>Lian wound his arms around her waist. &#8220;I hear you,&#8221; he said softly, breathing the words against her skin. His eyes closed and he let himself rest his head against the softness of her breasts. She had been a heat and a fire once so long ago. His second queen, the enigma stolen from the desert who in those quiet moments could remind him of why he had loved her for her season. Even now, despite how he resisted, each touch, and kiss, and nibble of fangs had sent his song flaring. He could feel it, as much as he could feel that love for her, for her wisdom, and for the warning and honesty with which she spoke against him. &#8220;This heart of mine has been undeserving.&#8221; It still was. He touched his lips to her chest, over her heartbeat, and shifted his hand so that he had hooked his fingers beneath her knee.</p>
		
		<p>There was a betrayal coming that he resigned himself to the moment that he lifted his bride into his arms. That he had to push the thought of Delilah from his heart to make room for the symphony of harps and lutes and the wild pulse of drums, he would never speak of. The two did not make it to a cushion before the elder vampire let an answering peal of violin breach his blood.</p>


	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="15-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter XV.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="17-link">Chapter XVII. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
