<div class="row">
	<div class="col-xs-12">
		<h1>Chapter XIII.</h1>
		<hr>
		
		<p>The grandfather clock in the foyer had barely called its second, sleepy gong through the manor when a shadow slipped through the old servant&#8217;s door. Angelica seemed for all the world like the lady of the house who had lost her way in the pantry, coming home from some regent&#8217;s ball. She was glittering gold and red silk in a gown trimmed and patterned with golden vines. She wore her golden choker, inlaid with large rubies rested against her skin like a preciously slit throat, matched by a pair of large drop earrings and a weaving of rubies and gold pinned throughout her coiffed mane. She breathed in. Lian was not home. She could feel his distance in the gentle course of music through her blood. It suited her. She had come a long way, breaking from the brides&#8217; hunting party. That the queens were left to their own during their hunts, that their chosen chaperone kept track of them only so far as ensuring they arrived and left as safely and discreetly as could be managed, had been turned to Angelica&#8217;s advantage.</p>
		
		<p>No one stopped her from quietly disappearing into the shadows, just as no one stopped her from slipping through an entrance that she remembered all too well. She took another breath, padding silently down the corridors. Much had changed in the century since she had served as a maid, but she knew the way. Her shawl slipped from her shoulders to the crook of her arms and was abandoned on the stairwell as she closed the distance to the Lord&#8217;s room.</p>
		
		<p>There was a scent that caught her in a pause. Mortal blood, old as if it had been sitting for days, and yet her nostrils flared for the potency of it. It made her even more aware of the hunt that she had abandoned. She had been told of only one who might have had cause to be bloodied around Lian, one quiet whisper of a woman, a Delilah Flowers, who had been paraded before a hunt in the sun. Angelica&#8217;s jaw tightened and the soft pink of her tongue poked free from between her lips. Surely such a woman would not be here. Not in Lian&#8217;s home. That had been Angelica&#8217;s place. As she turned to slip down the hall to the guest rooms, she became increasingly aware that her place had been impeded upon in more ways than one. A hundred years ago the west wing had belonged to servants. One room for her parents, another shared between her and her sister. That it had changed over the course of a century could be accepted. What she could not accept was the lingering smell of blood coming from behind <em>her</em> door.</p>

		<p>It was all she could do to still the burn of tears that threatened when she drew the door open. The room was larger than it had ever been, and the bed was not in the same place she had once kept it, but that tell-tale lump of the comforter was not hard to find. Angelica breathed in, forcing her shuddering breath to quiet as she pulled the door closed with a soft click. It was as she had been told, she realized, and her heart twisted in her chest. The seasons came and left, brides were found and forgotten. Her moment was slipping from her fingers and she knew, gazing over the sleeping face of the woman who rested in that bed, that she was as doomed to the hell of Lian&#8217;s eternity as all the others.</p>
		
		<p>Her shadow was right at the bedside, and she stood not but a foot away from her replacement. There had been no exaggeration when she had been told of the new flower. This one had hair as dark and full as Angelica&#8217;s own, and a round face still as soft with youth as hers. Angelica&#8217;s fingers drifted to touch her own cheek before lowering to hook into the choker. This one lived here. Her damned rose scent and blood were all over the room. Not a mistress. Not in these quarters. This one was a servant, as much as she had been once upon a time when she was Lian&#8217;s song.</p>
		
		<p>Her fingers lowered, trembling, to touch the woman&#8217;s hair, and it was all she could do not to tear it out. Instead, she lowered into a sit in the armchair by the bed.</p>
		
		<p>Delilah stirred slightly under the touch that brushed her hair. For a moment, her sleep fogged mind thought that it may have been merely the wind that had stirred her awake, but slowly, some inner intuition teased awareness into her soul that she was not alone. She knew that it was night, or by now early morning. There was no one who would have cause to be in her room, to be touching her unless&#8230;</p>
		
		<p>&#8220;Lian?&#8221; The drowsy murmur escaped her even as her lids were slowly fluttering open. The room was completely dark, save for the light of the moon filtering through the sheers, but even in that limited, cold blue light, she could make out the form and outline of a woman. The wink of jewelry was evident in her ears and upon her throat, and from the silhouette, her hair was styled in a fashion preferred by the ladies of social standing. Delilah didn&#8217;t have to see her dress to know that it was an example of finery, and the scent of perfume that clung was feminine and alluring. This was a woman of means and almost a certain stranger in Lian&#8217;s home. Delilah felt an incremental increase of tension. Could it be that someone had taken on the guise of finery in a mask to rob the manor unnoticed? Surely someone had heard her come in? The smile that she could make out in the kiss of shadow and moonlight, did little to appease her worry.</p>
		
		<p>Slowly, Delilah adjusted her arms under the covers, using their leverage to sit up higher against her pillows, then she gathered the thickness of her pink coverlet more securely into her waist. She did not reach out for the lamp. There was a part of her that did not want to see what she was certain, with a strange knowing, would be an unwelcome mystery yet still cloaked in the shadows.</p>
		
		<p>&#8220;What do you want?&#8221; Her voice managed to be steady as it escaped her. It was a strange first question, but Delilah did not expect that a criminal would provide a truthful answer to the other, more natural &#8216;who are you?&#8217; And so, she went for the jugular. The woman was here for a purpose, they may as well get around to sharing it. In the back of her mind, she wondered at how best to alert the household to the fact that they had an intruder. Hanging from the side of her bed, Delilah was all too aware of the bell pull that could and would rouse Alice and Henry, no matter the hour of the day or night.</p>
		
		<p>&#8220;I was coming to see my husband,&#8221; Angelica offered, with words as blunt as they were thick with honey. &#8220;His last visit home was so short&#8230; Only four days. I thought I might surprise him.&#8221; She tilted her head, the rubies catching what little light was in the room in a red glitter. &#8220;You called his name&#8230; pretty maid that you are&#8230; Are you expecting him in your room?&#8221; She laughed: a sweet, bell-like sound. &#8220;I cannot say I blame you if it is a case of calf-love. Lian is rather beautiful, isn&#8217;t he?&#8221;</p>

		<p>Delilah heard the words that the woman was speaking. Everything after the word husband registered to her only as sounds, and her heart suddenly slammed against her ribs with enough violence to cause her nightgown to shiver with each beat. It took a moment for the noise in her head to quiet enough for her to form a coherent thought. Even then she did not speak, or make a sound save for her breathing. Even to the natural hearing, it evidenced some shortness of breath for the visceral kick to her heart and soul that she had experienced.</p>
		
		<p>She still did not reach for the light, yet, though she knew that she would. It was a sordid sort of desire for self-flagellation, to see the woman who had just ended her pretense at a dream. Married. Of course, he was married. Why wouldn&#8217;t he be? As rich and handsome as he was. It was not unheard of for men and women of society to live in separate accommodations, and Lian had been gone those four days that she could vaguely remember as part of the haze of the beginning of autumn. She could feel the wellspring of grief and loss begin to rise, threatening the anguish of tears, frustration, and denial that would inevitably come. But not now, not here in front of her.</p>
		
		<p>Delilah knew enough of the ways of society to know that to show weakness in the presence of a predator was an invitation to slaughter, and the knife that she had taken to her heart was all of what she felt prepared to endure tonight. Lady Redmond had all but branded her a whore, by the words of her mouth, and Delilah knew that she could have only herself to blame for speaking Lian&#8217;s name. Were it not for that, she could have attempted at passing herself off as exactly what she was. The twist of bitterness in her soul was visceral. She had trapped herself with her own hopeless fantasy. There would be nothing for it but to face the music. She would have to figure out the rest later.</p>
		
		<p>Slowly, quietly, she leaned over and extended an arm to turn on the lamp. Immediately, a bath of warm, golden light flooded one-half of the room and she could take in the full glory of the raven-haired beauty who was seated in the armchair that Lian had occupied not hours before. Lian, of the awkward politeness and offers to purchase her new gowns. Lian, of the lack of sensibility to visit a maid alone in her room. How long had he been going to wait until he made his indecent proposal? Probably until she was well and truly in love with him; until she could deny him nothing. He had so very nearly succeeded. She could feel the numbness beginning to secure its grip on her heart, and she welcomed it. She would need the numbness now.</p>
		
		<p>&#8220;I was, yes&#8230;&#8221; she answered, almost evenly, speaking the blatant lie. &#8220;It is about the hour that he joins me.&#8221; If she was to be taken for a whore, then she would enjoy the benefit of offering even the least bit of pain in return for that which she was suffering now. Not that it appeared that the beauty seemed anything other than amused by the idea that her husband had taken a lover and preferred to remain away from home for months on end. &#8220;If you know your husband at all, Lady Redmond,&#8221; she said softly, and there would be no help for the huskiness that came upon speaking the words. &#8220;You are more than aware that Lian has little interest in calves&#8230; or cows.&#8221; Let her take that as she would.</p>
		
		<p>Angelica&#8217;s smile seemed unaffected by the woman&#8217;s words. She tsked gently and lifted an index finger to tick it back and forth. &#8220;I was a serving girl before&#8230; Here. This was my room.&#8221; She tilted her head and pointed to the opposite corner of the room, &#8220;Oh yes. My bed was&#8230; right there. This wall faces the Humber, and it grows dreadfully cold during the winter. Of course, my sister might as well have been a fireplace in her own right, we shared a bed too.&#8221; Her eyes turned back to Delilah, and there was that about her expression, sweet as her smile was, that shadowed with cruelty.</p>
		
		<p>&#8220;I was always terrible at sharing&#8230; So just imagine my surprise when I was told by a little bird that my husband had another woman on his arm through the year&#8217;s hunt. Now I see, though. He had a taste of how sweet those of us below his rank taste&#8230; And just look at your hair.&#8221; She leaned forward, her fingers brushing her jawline to indicate the spiraling curls that fell there. &#8220;We&#8217;re so much alike. Isn&#8217;t it so like a man to want to recreate the chase?&#8221;</p>
		
		<p>Angelica lowered her fingers to touch her choker again, lifting her head as though observing the room in full. &#8220;&#8230;He takes you in the guest room? Pity. I remember the first time I was naked on his sheets, still just a serving girl, then. Satin. If he had not had such a hold on my hips I thought I might drown in them. I suppose I should be pleased that he keeps the bed I first bled in sacred&#8230; I think your fun is quite finished, however. If he has not paid you for tonight, let me kindly compensate your work. He will not be back until dawn, and I do believe we should all like to be spared the embarrassment of this&#8230; adventure.&#8221;</p>
		
		<p>Delilah was in a prison, one of her own making and from which it did not seem there would be any escape, at least not until Lady Redmond deemed to put her out of her misery. She had no choice but to hear the words, and to see the truth of them. Lian&#8217;s wife did look a lot like her. No, not like her, <em>she</em> looked like Lady Redmond. She was the one in second place in this race. Not that Lian had even offered her a bed, much less his hand.</p>
		
		<p>Confusion caused a terrible blankness and blindness in her mind. What words were there to be said in the face of such a horrible truth? Lian had done this before. He had wooed, courted, bedded, and wedded his servant, and for her youth, it could not have been so terribly long ago. How? How was it possible? What kind of heartless beast lay beneath his almost smiles and golden halo? If she did not stop thinking about it, she would be at a loss for air to breathe.</p>
		
		<p>And yet, she could not help but think of the picture that Lady Redmond had painted; of darkness beneath Lian&#8217;s pale body, and of his long fingers held tightly around full hips. Against Delilah&#8217;s will, she could hear the echo of sighs and moans of pleasure. She could see the spread of dark hair against the pillow and the arc of a feminine body in pleasure. She could hear him call a woman&#8217;s name. <em>&#8220;Delilah.&#8221;</em></p>
		
		<p>In her bed, Delilah took in a shuddering inhale of a breath. It had not been Lady Redmond that she had imagined in the throes of ecstasy — it had been herself. She had seen what would never be, and the knot in her stomach was only in part for the flood of agony that she could feel battering at the shores of her heart, demanding to be released. How much longer she could hold on, she did not know. There had to be a way to get the woman to leave. Lian may have courted, bedded, and wedded one servant, but that all but guaranteed that there would not be a repeat of that chase, if it had indeed begun. That he was courting her, was evident. That he had not bedded her was only God&#8217;s mercy. That he would never wed her, was obvious by the evidence sitting so smugly in the lamp light, twisting the knife.</p>
		
		<p>&#8220;Lian takes me wherever he bloody wants&#8230;&#8221; she said huskily, deliberately using that coarser word for its connection to Lady Redmond&#8217;s own utterance. &#8220;Nothing is sacred to him.&#8221; She managed that in a clearer voice. That she felt those words to a depth that almost burned her throat to say them, was not allowed to register on her face; although there was no denying the brightness of her lavender gaze, dilated slightly for the lamp light. &#8220;And I&#8217;m afraid you misunderstand, Lady Redmond. I am not paid; this is my pleasure, not my work, and it matters not if I wait until sunrise or a few days hence to see him again.&#8221; She busied her fingers with smoothing out her bedding. &#8220;This is my home, and Lian lives here&#8230;&#8221; she paused, &#8220;&#8230;with me. You may not be satisfied to share, but it appears that on this occasion you must.&#8221; She looked up again, her expression empty of life or feeling. &#8220;You are welcome the days he deigns to give you. But he will, as is evident, come home to me.&#8221; She offered a tight smile. &#8220;There is nothing so cold as the title &#8216;wife&#8217; to keep one warm at night, don&#8217;t you find?&#8221;</p>
		
		<p>Delilah thought of the bell cord. If it was an embarrassment that Lady Redmond desired to be spared, then there was only one certain way to end this audience. She reached out, as if for the lamp again and at the last moment redirected her fingers to wrap around the pull. She did not yank it, yet.</p>
		
		<p>&#8220;I&#8217;m afraid, Lady Redmond, that it is <em>your</em> fun that has quite ended. I believe that I should like very much for you to leave my room, or I shall be obliged to ring for Henry to have you escorted out. I&#8217;m certain that would not please Lord Redmond greatly to have to explain.&#8221; Delilah managed to keep her tone polite, and quiet for those words, but there was no hiding the slight trembling of her fingers on the pull. Lady Redmond had hit her mark and well. That was not to say that she would not yank the bell pull as if her life depended upon it if Lady Redmond chose not to co-operate.</p>
		
		<p>Delilah did not think that she could endure much more of the encounter.</p>
		
		<p>Angelica quieted, her eyes on the bell cord as if for a moment, she was considering the consequences of it being pulled. Finally, however, she answered, &#8220;No, sweet. Nothing is sacred to him. I see that now.&#8221; She pushed herself up to a stand, smoothing her hand down the front of her dress. &#8220;Do not fool yourself into thinking you matter. I don&#8217;t. You don&#8217;t. At least you have the freedom to leave.&#8221; Angelica offered only one final look back once she had reached the door: &#8220;You should be thanking me for trying to save you&#8230; As much as I quite hate you.&#8221; If her goal had been to leave as quietly as she had come, Angelica ruined it by slamming the door closed behind her. It would not matter when Henry came to be sure that Delilah Flowers was safe and sound. Angelica was gone.</p>


	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="12-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter XII.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="14-link">Chapter XIV. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
