<div class="row">
	<div class="col-xs-12">
		<h1>Chapter XXI.</h1>
		<hr>
		
		<p>The sun had been visible over the horizon for just over two hours by the time Delilah had been dropped off at the farmer&#8217;s market in the South End of Easthaven by Henry, with a promised ride home within the hour. For centuries now, almost as if by magic, the dawn saw stalls and tents springing up in the middle of the town square, surrounded and overshadowed by the height of townhouses and permanent storefronts. The fresh fruits, vegetables, and homemade products brought into town by those who farmed the areas beyond it often lasted only as long as it took the bevy of servants and ladies maids to pour out of doorways while their employers were still asleep. The sounds of sales, exchanges, haggling and raucous laughter and flirtation were familiar echoes around the market square as the town&#8217;s commoners stole moments of enjoyment in undertaking their labors. After a while, faces and names became familiar, and it had been no different for Delilah Flowers.</p>
		
		<p>Her daily morning market trips had once been a favorite part of her duties at the manor, but that had ceased to be the case since the very first <em>incident.</em> There had been a series of <em>incidents,</em> as Delilah preferred to reference them now, that had been taking place over the last several months. She had been obliged to confess to Alice and Henry the mystery of her acquired enemy after arriving home one morning, covered in mud and with a torn dress after being run off the road by a speeding closed carriage during her walk back to the manor. Henry had been her driver and chaperone to the market after that. She had passed her troubles off as an ongoing dispute with another servant in town and had begged them not to disturb Lord Redmond with affairs of a controversy below his station.</p>
		
		<p>She had convinced herself that it was not at all a lie that her enemy was a servant. Angelica had been a servant, once, and must live in a town somewhere. It could only be she, Delilah had determined, who was behind her trouble. It made sense, in looking back, that one of the first signs of the woman&#8217;s interference had been the vandalism of Delilah&#8217;s new dresses. At the time, she had not realized the lengths to which Lian&#8217;s former lover would take her engagement with the woman she saw as her replacement. Although Delilah had been at her most attentive, she had never caught the woman in the act. If she were honest with herself, she would have to admit that she really did not think that Angelica would be caught dead milling the markets with the common folk. Be that as it may, there was no denying that the market was the base of her adversary&#8217;s operations, and so it was with a certain nervous edginess, that Delilah navigated through its bustle and cacophony.</p>
		
		<p>In the simple, high-waisted muslin gown that she had chosen for her rounds today, she was the promise of the spring that had erupted into bloom around the town. It was a muted cream in color, with puffed sleeves, a modestly ruffled scoop collar, and was accented with small brown diamond shaped dots. She had learned over time, that blending in with the crowd had increased her chances of escaping a trip unscathed. With a large basket in hand, she made her way to a stall on the outer edge of the market, closest to one of the streets that bordered it and the sleeping houses just beyond. Alice bought her tomatoes from only one source. That was where she would begin.</p>
		
		<p>Suddenly, Delilah was in the shadow of a tall, blue roan horse. Its rider was a woman even darker in hair and attire. She looked all of a lady widow despite the pale youthfulness of her features, and even more so the fact that she was disregarding all propriety by riding a horse in the middle of the market. The woman slid down in a smooth dismount, her fingers curling around the reins so that her horse was planted solidly between the end of the market and where she and Delilah stood. Ayla stood so close to the younger girl that Delilah could smell the scent of age like old books that came from her; that same scent that seemed to cling to Lian. &#8220;Please do not panic or flinch,&#8221; Ayla offered, quietly, in a voice just loud enough that Delilah could hear. Her free hand shifted to the clasps that held her spencer jacket closed and she began to unbutton it. &#8220;I am helping you. It will be easier to do if you are calm and do as I say.&#8221;</p>
		
		<p>Ayla moved, stepping casually so that Horse blocked the path at the end of Market Street, and had Delilah&#8217;s side. &#8220;There is a man with a pistol, and he has been watching you for a clear shot.&#8221; It went unmentioned that the only reason Ayla had seen him was because she had already been watching Delilah. She had added a detour to her own morning trips just to see Lian&#8217;s mortal. &#8220;He is the only one. It will not be difficult to get away from him. Leave your basket.&#8221;</p>
		
	<p>It was the words that the dark woman spoke, more than anything else, that caused the blood to drain from Delilah&#8217;s face and a sudden weakness to soften her knees. It would not do at all to faint in the public market. The thought, as irrelevant as it was in terms of the seeming danger of the moment, still whispered in Delilah&#8217;s ear, and she made the conscious effort to stand a little steadier as she turned to face the woman. &#8220;Who are you? And why are you helping me?&#8221; She did as she was instructed and set her basket aside as if preparing to lean into the tray of produce to gather some for purchase. Intuitively, she knew that this woman was connected to Lian, somehow. She even smelled like he did in some way. What was going on?</p>
	
	<p>&#8220;My name is Ayla,&#8221; the woman offered. &#8220;I know you can ride,&#8221; she drew her jacket from off her shoulders to hand it to Delilah. &#8220;It will not fool him if he is paying attention, but at a glance, perhaps it will be different enough. You will count to fifteen, and you will take Horse and walk up Market Street to Park Road. Do not ride her until you have turned the corner. You keep in front of her so that she is between you and the pistol, do you understand?&#8221;</p>
	
	<p>Delilah&#8217;s gaze found the dark spencer jacket that was being offered. Her fingers closed around the material and drew it into her body, some unconscious effort made to hide it from the unseen, would-be attacker. Who would want to shoot her? Surely, she had not caused so deep an offense in merely existing as to cost her her life? She could feel the rise of fear begin to threaten her ability to think and function effectively. She wanted to run, just drop everything and flee: from this woman, her horse and the danger in the shadows. Instead, she just nodded mutely that she understood. Fifteen and then the horse. The weight of the material in her hand reminded of its purpose, and she shook it free enough that she could slip first one arm and then another into the sleeves. It all but swallowed her smaller frame, casting almost half of her body into its covering darkness.</p>
	
	<p>Ayla tried for a softer expression, but she only managed to seem weary. &#8220;I will take the alley, and I will meet you at the garden entrance. Then I will take you home safely to Lian.&#8221; She lifted a hand, gently touching the back of a cool knuckle to Delilah&#8217;s brow in what was meant to be a reassuring little knock. &#8220;Do not be afraid. I know how he must treasure you. I will not let harm befall you. Go ahead and begin counting.&#8221; No sooner had she offered that command, however, than she slipped around the stall to disappear into the crowd.</p>
	
	<p>If Delilah was surprised by the sentiment demonstrated in Ayla&#8217;s actions, there was no time to dwell upon them. She heard the instructions as they were given, and suddenly, as suddenly as she had inherited her company, Ayla was gone, and Delilah had been left her horse.</p>
	 
	<p>She forced herself not to count too quickly, even as she gathered the reins of the gray into her hand and took her first steps forward. She made sure to keep its large body between herself and the direction of the invisible threat and began walking. &#8220;Please God,&#8221; she whispered, &#8220;If you&#8217;re not too terribly opposed to missing me a little longer, I do think I should rather not die today.&#8221; She wasn&#8217;t sure if He had time in his busy schedule to attend to her needs, and she had had a not quite maidenly dream about Lian not two nights past, but she was quite open to negotiation. She kept a count going in her head, even as she started walking, to help steady her nerves. "Twenty-three&#8230; twenty-four&#8230; twenty-five&#8230;"</p>
	
	<p>"Damn it," Seth cursed, jamming his pistol-bearing hand into the shadows of his jacket. It had been primed and ready; he needed only to line up the bloody shot. Yet the horse was moving and Lady Flowers was not there. But where had she gone? He felt the slow rise of panic sit like a hot rock in his throat. He could not lose her. Not today, not now. Angelica&#8217;s threat felt entirely too real, and it was as though his body was revolting already in anticipation of the punishment to come.</p>
	
	<p>Shuddering through the sudden cold sweat and nausea that had overtaken him, Seth scanned the crowd. There! In front of the blasted horse! Wearing a jacket, now, leading the mount, but he knew that mound of curls from the months of watching her. There was Lady Flowers. He hissed a curse beneath his breath. It was not too late. He could get in close and put the gun to her temple, and that would be the end of it.</p>
	
	<p>Ayla found him shoving through the crowd to tail the horse and the girl walking just ahead of it, his gun out and glistening. Those who he shoved took notice of the weapon, and slow ripples of panic began to spread through the market. They were mostly women, after all; maids and servants not paid enough to do more than duck out of the way of a man with a pistol.</p>
	
	<p>The flower Ayla was trying to preserve was still counting when Delilah felt the rise of panic begin to stir the market around her. He was coming. She knew that with every fiber of her being. Park Road was only a few more steps away, and then Ayla had said that she could ride. It was all that she could do to maintain enough control to follow her directions when she knew that the horse had more power to flee her predator than she ever could. She did not look back to determine where the shooter was, or how quickly he progressed. She rounded the corner, and the protection offered by the loom of the building that separated her from the market square.</p>
	
	<p>Ayla closed in on the hunter a moment after Delilah disappeared around the corner. Without hesitation or wasted words, she grabbed her mark by the scruff of his neck, and it was all the strength of her kind that spun him around to face her. There was that about his expression, the surprise, the understanding, and the sudden fury, that made her realize that he must have known what she was. That knowledge did not even garner a beat of hesitation in him. He lifted the pistol and pulled the trigger, just as Ayla slammed her fist into his temple. </p>
	
	<p>An explosion of smoke and sparks filled the air, but all that mattered to the vampiress was that she had felt the crunch of bone as it shattered beneath her knuckles from the force of her blow. He dropped immediately, the side of his head bearing an indention that was oozing blood into his hair and down his face. Ayla exhaled into the plume of smoke. The ripples of fear and panic in the mortals around them had blossomed into a hectic storm of hysteria, and she was left standing above the man&#8217;s twitching body with her hand pressed against her stomach. She breathed out again, closing her eyes beneath the furrowed stitch of her brows until she could move. Hers was a slow walk back toward the alleyway, no effort made to avoid or react to the attention that she was garnering.</p>
	
	<p>The sound of the pistol shot had reverberated throughout the market, sounding in the enclosed echo chamber of buildings as loud as a small cannon going off, as was reported later to the law by the gathered witnesses. Without looking back Delilah reached up and secured a hold on the side saddle that was set on the horse. She would likely not have a stable seat for not having the time to settle her dress, but she needed to ride. An unladylike hitch of the opposite side of her dress to expose her leg to the knee, and she was securing a foot into the stirrup and hoisting herself up with its leverage. Her bottom had barely fallen into the saddle before she was urging the horse forward into a steady trot. The garden, Ayla had said they would meet at the garden. She had not heard another shot, which she supposed was a good sign, and she could not feel or sense that her would be attacker had rounded the corner behind her. Where had he shot? It didn&#8217;t matter save for the fact that it had not been at her.</p>
	
	<p>Delilah crossed the iron gates into the town garden and waited for what felt like an eternity, even though it must surely have only been a few minutes. Where was Ayla? She sat up a little straighter, her lavender gaze anxiously scanning the tree lined and flowered paths that spread out from the entrance into the depths of the gardens.</p>
	
	<p>&#8220;There is a good girl,&#8221; Ayla&#8217;s voice lifted in volume just loudly enough to be heard as she emerged from the alleyway. She looked little worse for wear, although there was something just a little less perfect about her features. However, the darkened stain, shining as slick as an oil spill on her stomach told another story. She kept her hand pressed there as she closed the distance to the girl. &#8220;You listened well, and you were brave. Both of these things are admirable.&#8221; There was a faint smile on her face. &#8220;Moreso that you were not panicked into stealing my horse or my jacket. Are you alright?&#8221;</p>
	
	<p>Relief swept over Delilah like a cool wind on a hot day for the sound of her savior&#8217;s voice, and reflexively her body slumped into an exhausted and shell-shocked curl in the saddle. She could see Ayla making her approach, but answered her before the woman came into a fully focused view. &#8220;I don&#8217;t mind telling you that I very nearly did both,&#8221; she admitted wryly. &#8220;But it would have been most unkind of me, and I am quite certain that I should have fainted before making it but half the distance to the manor. I should not have wanted to be taken up for a horse thie —&#8221; Her nerve induced chatter cut off abruptly for the sight of the stain in the woman&#8217;s abdomen.</p>
	
	<p>&#8220;You are hurt! You are bleeding! You said nothing. Oh, OH! We must get help. I shall never live another day with myself if you die for trying to save me.&#8221; Distress was painted across Delilah&#8217;s features and she twisted in her saddle, tangled in her own dress skirts for the effort to dismount and reach Ayla. Her toe caught in the stirrup, and it was with a squeak of dismay and a furious flail of arms that Delilah Flowers fell from her mount. Again.</p>
	
	<p>Ayla&#8217;s arms were there to catch the girl. That Delilah had ended up with her foot caught in the stirrup and her torso in Ayla&#8217;s arms, hanging sideways from Horse might have made for a funnier sight were it not for the girl&#8217;s distress.</p>
	
	<p>&#8220;Be calm,&#8221; Ayla said, supporting her as easily as if she weighed as much as a child.</p>
	
	<p>A soft gust of breath escaped Delilah&#8217;s lungs as she realized that she had been spared what surely had been fixing to be another cracked head. She had enough on her plate figuring how she was going to explain all of this to Lian, without having arrived home with injuries on top of it.</p>
	
	<p>&#8220;I am going to put you back on Horse, now,&#8221; Ayla continued. &#8220;Do I seem to be hurt or suffering?&#8221; A firm hand splayed just on the side of Delilah&#8217;s ribcage, easing her back onto the saddle. Ayla&#8217;s hand remained on the girl&#8217;s thigh for a moment longer to ensure her steadiness.</p>
	
	<p>&#8220;No,&#8221; Delilah admitted, settling into a more comfortable and secure seat in the saddle. The woman didn&#8217;t seem hurt at all. There was a trace of confusion in Delilah&#8217;s tone for the realization of what she had answered. It must mean that it was not Ayla&#8217;s blood, although it had certainly stained as though it were. &#8220;Did he do harm to himself then?&#8221; It all seemed rather odd, but it was the only thing that seemed to make sense in the situation. &#8220;Thank you for helping me&#8230;&#8221; It came out softly, finally. There really was nothing for it now, she would have to admit to Lian what had been happening. Still, she hesitated yet for sharing her thoughts upon a suspect.</p>
	
	<p>&#8220;Of course,&#8221; Ayla answered, although whether it was for the thanks or the question of what had become of the man with the pistol, was difficult to tell. &#8220;Appearances are not everything. You had best keep my jacket on. I fear your lovely dress might be ruined without the buffer.&#8221; Ayla&#8217;s own dress was beyond scrubbing clean. Her hand had a red smudge that was briefly visible on her palm when she pulled it away to wipe it across the fabric of her skirt. Ayla only winced once as she crouched and began to tear her dress, along with the petticoat beneath it, up the side of her leg so that the black-silk drawers were visible just above her knee.</p>
	
	<p>Realization dawned on Delilah as she watched the woman&#8217;s preparations. &#8220;You&#8217;re going to ride astride&#8230;&#8221; She would have to if they were both to sit on the horse with its side saddle mount. &#8220;Do you know the way to Lord Redmond&#8217;s estate? It&#8217;s not too distant of a ride. I have just realized that Henry was going to collect me in the wagon at the market and will no doubt arrive to hear of all the mayhem if we do not intercept him before he does.&#8221; And perhaps to the discovery of her abandoned basket. &#8220;Oh, Please, we shall have to hurry if we do not want to cause further alarm.&#8221; She could only imagine poor dear Henry&#8217;s horror at the unfolding drama, given what he knew of her incidents.</p>
	
	<p>&#8220;We will take the main path to Lian&#8217;s estate. There is nothing to fear from your assailant,&#8221; Ayla offered. &#8220;If your Henry is on his way, we will meet him.&#8221; Standing slowly, the woman&#8217;s hand almost lifted again to press on her stomach before she stopped herself. Instead, she gripped into the fabric of the pretty dress that Delilah was wearing. Once she had an anchor through to the saddle beneath, she swung herself up in what should have been a graceful movement to plant herself behind Lian&#8217;s mortal. Ayla dropped a little heavier on Horse&#8217;s back, enough so that the blue stamped and nickered her protest.</p>
	
	<p>For a moment, the vampiress lowered her forehead upon Delilah&#8217;s shoulder and inhaled sharply against the skittering pain. Then, with a sigh, she straightened, reached around Delilah to take the reins and urged Horse forward and back onto the road.</p>

	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="20-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter XX.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="22-link">Chapter XXII. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
