<div class="row">
	<div class="col-xs-12">
		<h1>Chapter XXV.</h1>
		<hr>
		
		<p>Delilah was awake, which was not a state that was usually problematic, but it was almost three of the clock in the morning and she had barely slept a wink all night. The only cause she could think of for the matter was that she was missing Lian. It had been weeks since the nightmare that had erupted at the market, and it had taken almost the entirety of at least one of them for a certain proprietary watchfulness and concern to fade from his expression. It had taken the remainder of that time with the evidence of no further <em>incidents,</em> to finally be rid of the hackles that seemed to rise if anyone had even so much as looked in her direction too long as she went about her errands and duties beyond the manor. He had been so much her shadow that his absence now, left her feeling as if she were somehow naked and undressed to the world, without a covering.</p>
		
		<p>It did not help that during those weeks, the times that she had stirred or awoken in the night, she had had a knowing that he was awake too. A silly fantasy, she was sure, but it was as if her stirring had caused his own wakefulness, and she had laid there, all too aware of him being in his own bed some distance away listening for her, until she had drifted asleep again. Maybe that was why she could not sleep. The void left by his absence in the stillness of the night was as loud as an echo chamber, and the lullaby of his silent, imagined companionship was not touching her spirit tonight.</p>
		
		<p>Delilah huffed a breath that was close to a sigh of frustration and adjusted the softness of the covers that were piled around her, staring at the ceiling above her. It wasn&#8217;t working. Perhaps some warm milk would help; though it would mean a trek down the hall and down stairs to the kitchens to satisfy her cravings. She dragged her covers aside and shivered slightly for the coolness that always seemed to linger in the rooms of Lord Redmond&#8217;s sprawling mausoleum. Why ever did the man even need so much house? She determined to ask him when she saw him again, though he no doubt would have some entirely too ready answer for her query. In the dark, her lips curved slightly into a soft smile. Dear Lian, he was entirely too complicated a man for one woman to understand, but she would try.</p>
		
		<p>Hoisting herself to a seat, her legs swung over the edge of the bed, hidden for the fall of soft French linen all the way to the floor. The white underdress that she had worn to bed was trimmed with pink silk ribbon just below her knees, and dainty lacework etched the scoop of its neck line and wide straps. A small bow helped to secure the garment closed over her breasts. Tailored to complement and support the dress intended to be worn over it, she found it to be more appealing to the eye than her usual shift nightgown, and she had taken to wearing it to bed in place of the other. That she may have hoped it would be seen and appreciated by a certain Lord if cause ever permitted, was not something she would ever admit to, even to herself. She spared a thought for grabbing a robe and decided against it. There would be a fire going in the kitchen, and she would not be gone long. Crossing the room to the door, she made sure that it was silent in closing once she had stepped into the hallway. Then Delilah was the pale drift of a specter in white through the gloom to the stairs, the weight of her dark hair a shadow falling in a curtain of wavy silk to her waist.</p>
		
		<p>She turned the corner of the stairwell and came face to face with the shadow of a man whose eyes reflected like gold coins in the darkness. In the next instant, he charged upon her, a strong hand clamping against her mouth and the other grabbing the front of her underdress to yank her in closer. Despite her struggling, the stranger seemed to have a strength far beyond that of any normal man. In the blink of an eye, he pivoted behind her, pinning her against him with the vice-like curl of an arm around her chest.</p>
		
		<p>Delilah could barely breathe, and what breath she was taking was flushing with each stressed exhale over the knuckles of the man who had ensnared her. She wasn&#8217;t quiet in his hold. The sight of the unnatural golden glow of his eyes had all but put the desperation of the fear of death into her. She writhed like a serpent, seeking some gap in his embrace through which she might slip, and the motion caused a tear in the fragile lace of her collar. She felt it grow looser around her chest, and it was that, more than anything else that began to quiet her movements. The last thing she wanted was to lose her garments around the monster.</p>
		
		<p>&#8220;Gentle, gentle, Ms. Flowers,&#8221; was the quieter warning, spoken above her head. &#8220;I will be as gentle with you as you are&#8230; I don&#8217;t like the screaming.&#8221; He turned his head, murmuring quietly against the shell of her ear. &#8220;No matter what happens in the next few minutes, you&#8217;ll come with me tonight. If you scream, if you bring that old couple down from their beds, I&#8217;ll kill them both, and you&#8217;ll still come. It makes no difference to me, but you don&#8217;t want that, do you?&#8221;</p>
		
		<p>Delilah felt the sting of tears prick her eyes as she shook her head in the negative for her answer. Henry and Alice, she couldn&#8217;t do anything to put them in danger, and somehow she had a knowing that this man would not hesitate to hurt them, or kill them as he had threatened. No, she wouldn&#8217;t scream, and she knew that it meant that her fate was as good as sealed, whatever was to happen to her. </p>
		
		<p>Poor Lian. She was not able to stop the tears from rolling hot over her cheek to splash on her assailant&#8217;s hand over her mouth. She could not save herself, but she wished with all of her heart that she could spare him, and Alice and Henry, everything that they were about to endure for her sake. Delilah could feel her heart thudding against her ribs, and beating a pulse against the pressure on her lips. Who was he? And what did he want? It was unlikely that there would be answers forthcoming, she knew. All she could do was rest limp and silent in his hold, her physical indication of her willingness to submit to his demand.</p>
		
		<p>&#8220;That&#8217;s a good girl,&#8221; he smiled against her ear.</p>
		 
		<p>He eased her backwards toward the stairs where he drew her down into sitting a step beneath him. &#8220;You&#8217;ve brought the monsters down on you, you poor thing,&#8221; he continued, drawing his hand away from her mouth now that he had the assurance that she would be quiet. He kept one arm around her as he reached that now free hand to shuffle through his clothes. &#8220;Now, since we&#8217;re going to behave, you have a few choices. It&#8217;s more than you&#8217;ll get from anyone else tonight.&#8221;</p>
		
		<p>&#8220;You can drink a spoonful,&#8221; he produced a pewter spoon and a dark-colored vial filled with a liquid tincture. &#8220;Or I&#8217;ll beat you so you can&#8217;t run.&#8221; He turned his head, pressing the softness of his lips against the curve of her neck where he could feel that pulse fluttering like a hummingbird&#8217;s wings. He could already feel his fangs extending for the want of her blood. &#8220;I won&#8217;t stand for chasing you through the streets&#8230; We don&#8217;t have that much time to play. Your knight is the king of monsters, sweet, and you went and pissed off one of his queens.&#8221;</p>
		
		<p>Delilah was silent as she had promised she would be, and when his lips touched her flesh he would feel the soft vibration of the trembling that had taken hold of her body. She heard his words as if through a fog, and it was hard to focus, to understand what he was saying. He was going to beat her. No, he would only beat her if he did not drink what he was giving her. What was it? What if it was poison and he was forcing her to take her own death from the vial? Almost, almost she betrayed her friends with the swell of a cry of denial that choked her when she swallowed it down. They were going to the streets. She would not die. He wanted her quiet. The thoughts rattled around in her mind like so many glass beads with nowhere to settle.</p>
		
		<p>Lian. She understood that he was speaking of Lian, but none of it made sense. Lian was not a king&#8230; and he was not married. But there was no time for thinking: there was a choice before her. A lean of her body toward the spoon was followed by one last hitch of hesitation before she parted her lips and closed it around the spoon to allow the bitter tincture to spread across her tongue — Laudanum. She recognized the taste. It was a favored treatment for the ladies of high society given to cases of the vapors and hysterics. It was used to calm the nerves. She swallowed and remained still where she had been placed, though she used the motion of taking from the spoon to turn her head away from the contact of her lips against her throat. There was something horrifying about the way he kissed her there, as if kissing was not all that he wanted to do.</p>
		
		<p>She felt her body beginning to relax, and she fluttered her lashes in an effort to stay awake. In the darkness around her, it was getting more difficult to see the outlines of the walls and furnishings at the bottom of the stairs. A woman. She understood that much. It was a woman who was angry, about Lian. Lian. She could see his face in her mind as though through a haze. Her knight of the misplaced armor. How she wished he were here to hold her and assure her that it would all be ok. And then it was as if he were. She could feel the gentleness of his fingers upon her cheeks and the coolness of his lips upon her brow. Be brave. Ayla had said she had been brave in the market and he had been proud of her. She could be brave again, for him. &#8220;Lian&#8230;&#8221; She breathed his name on a soft exhale as the darkness took her.</p>
		
		<p class="text-center">***</p>
		
		<p>&#8220;Delilah&#8230;&#8221;</p>
		
		<p>Her name was a honeyed croon in the darkness, coaxing her back to the light, accompanied by the almost motherly brushing of fingers through her hair. She opened her eyes to a blinding white light. In a few, groggy blinks, it gave way to a flood of red that swam across her vision. Slowly, the outlines came into focus, and there, standing before Delilah was an all too familiar figure dressed in red.</p>
		
		<p>&#8220;Hello, Delilah,&#8221; Angelica purred, twisting her fingers through the curl she held to yank it. Delilah flinched, and as if her hair had burned Angelica, the other woman snapped her hand back. It fluttered down upon her choker, her thumb brushing over the rubies as she quieted. Her smile was as sweet as a cherub&#8217;s, but there was a cruelty glittering in her eyes. &#8220;You really are a queen now, you little whore. Look at your throne room&#8230;&#8221; With that, she stepped aside to let her captive have a look at the room around them.</p>
		
		<p>Delilah&#8217;s dilated eyes moved over the room, taking it all in. Around the women, the decadence that could be afforded by centuries of ownership and the wealth that came with a preternatural existence was on full display. Everything seemed to be some shade of red, or gold in what appeared to be an oversized suite, the majority of which was taken up with plush armchairs, chaise lounges and loveseats scattered about in such a way as to make it evident that a larger gathering was anticipated. Draperies hung over the walls, masking the windows and creating a cocoon like atmosphere that seemed to muffle sound, trapping it within that space. Oversized paintings were visible in places where the draperies were artfully parted to reveal them. As if on display, their erotic subjects were highlighted by the way the light fell from shimmering chandeliers at various points in the ceiling.</p>
		
		<p>Expensive rugs from the East lined the polished wooden floors, and on various side tables between the seating, crystal goblets empty of wine or any other beverage, caught the light to reflect it back in a sparkling display of wealth. The true centers of interest, however, were evident. On either end of the room, some of the seating present was arranged, as if for a spectator&#8217;s view of a staged show. One stage was a bed, round in shape and large enough, easily to hold as many as five couples. That it was a stage designed for pleasure was evident; every texture designed to enhance the experience of its occupants and by its very staging with curtains drawn aside in the theatrical style, a demonstration meant for public viewing. At the other end there was upon an elevated dais, a golden throne with plush purple lining; except that it was much less of a throne as it was a cage. Upon each armrest lay open, as if a maw, golden bracers that were meant to snap shut over forearms. And where the occupant&#8217;s head would be, lay a circlet of gold that would serve for a clamp to secure it to the plushness of the throne&#8217;s headrest. Gold link chains would serve for ankle bracelets, but there was no doubt for the looking, but that they were the chains of slavery and not of adornment. The royalty who sat upon this throne, would rule over nothing but the fear of helplessness.</p>
		
		<p>Through a haze Delilah struggled to make sense of where she was, and how she had gotten there. Why was Angelica here? There had been a man. A monster, with eyes of gold. Her tongue was thick and fuzzy in her mouth and she could barely form her lips to speak. &#8220;Where&#8230; am I?&#8221; That seemed the most pressing question, for some peculiar reason. She did not think that there could be any place so very full of sin in all the world. Had she died, after all? It would seem fitting that Angelica was a devil of the underworld, but she had not thought herself to be so poorly deserving of an eternal reward. </p>
		
		<p>&#8220;Why, in your new kingdom, your highness,&#8221; Angelica offered, in response to the first of the mortal&#8217;s inquiries. The vampiress lowered into a mocking curtsy. &#8220;Your subjects will be here soon to worship you.&#8221; </p>
		
		<p>&#8220;Who&#8230; was that man?&#8221; The devil with the golden eyes, and a grip the vice of death.</p>
		
		<p>&#8220;My sweet Victor,&#8221; Angelica straightened, twirling her wrist elegantly to indicate the golden-eyed man who lurked nearby. She stepped closer to him. &#8220;The only one left I can rely on&#8230; Since you had Ayla kill my dear Seth.&#8221; Her murmur was pressed against his throat with the stamp of a kiss, and she wrapped her arms around his throat. It was when he lifted an arm to hook around her frame that the glinting metal of the shears he held was visible.</p>
		
		<p>&#8220;I think this is going to come with a heavier price than we can pay, Angel,&#8221; Victor began, but was interrupted when she shoved him.</p>
		
		<p>For a moment, Angelica stood with her jaw clenched, trembling, before her smile returned. &#8220;Who will know?&#8221; She sang the words, extending her hand like a child expecting to be given a toy. He complied, pressing the shears there before he sighed and dropped back onto a nearby chair to watch.</p>
		
		<p>Delilah&#8217;s groggy gaze passed from Angelica to the man. Victor. That was his name, and vaguely she registered that she was trying to remember it for later if she survived this. The gleaming metal of the shears had summoned the return of the cold dread that she would not. Her gaze on Angelica was all of the wariness of an animal at bay, fearful of making a move that would trigger the fatal strike.</p>
		
		<p>&#8220;You took him from all of us,&#8221; Angelica continued, returning to crouch down before Delilah. &#8220;You stupid, human leech.&#8221; Suddenly she lifted the shears above her head, bringing them down just alongside Delilah&#8217;s leg. It tore through the chaise where she lay, plunging so deeply that Angelica&#8217;s fist was flat against the cushion. Delilah could not help the cry of distress that escaped her, and she was curling almost into a fetal position for her effort to avoid the blow. It was only then that she realized that she was bound. Knots around her wrists kept her loosely shackled to the chaise on which she had been laid, and her ankles had been secured to the armrest that was opposite to her head. She could not escape her captor&#8217;s venom, if she tried.</p>
		
		<p>&#8220;You can&#8217;t know what you even have. No, no, no, you can&#8217;t. Because he wouldn&#8217;t drag you down into this hell pit of an eternity that he sentenced the rest of us to. And why?&#8221;</p>
		
		<p>She lifted her free hand, grabbing Delilah&#8217;s face so that her nails dug into the woman&#8217;s skin. She jerked her head first to the left, then the right, as if the answer was hidden in Delilah&#8217;s face. &#8220;What makes you so special? Why should you get everything while the rest of us get scraps like swine? You gave <em>nothing</em> for it.&#8221;</p>
		 
		<p>As if the shaking of her head had loosened her tongue within it, Delilah finally managed words. &#8220;I don&#8217;t know what you&#8217;re talking about. I&#8217;ve taken nothing! I&#8217;ve been given nothing!&#8221; That Angelica spoke of Lian seemed to be evident, but she kept speaking of others and it made no sense. Delilah was beginning to fear that the woman had lost her mind.</p>
		
		<p>Angelica laughed. &#8220;Stupid, too.&#8221; Then, her voice broke, and she released her captive, drawing the shears from their sheath as she moved to a stand. &#8220;And the sweetest irony is, that in the end you are no better than any of us. Lian picked his Queen, and it was not me, and it was not you, and he will not come to save you because he has her on her back making his claim. You did this. You made everything change, and you&#8217;re not going to get away without paying your due.&#8221;</p>
		
		<p>It was that last that sealed the truth in Delilah&#8217;s heart. Angelica had lost gone mad. &#8220;You lie,&#8221; she breathed it out. &#8220;You&#8217;re a liar. You lied about being his wife. He told me what you did. Why can&#8217;t you accept what he has given to you and your family. Why must you be so cruel? He&#8217;s not with anyone else.&#8221; She said the words, but even as she said them, the memory of all those weekends that Lian had spent away from the manor whispered a rebuttal in her ear. How could she be sure? Why would the woman make up such a story? Lian. She felt the first shivers of uncertainty. She had no right to believe him hers, no matter the fantasy that they had woven behind closed walls. What if he had really chosen another for a lover? She wished, suddenly that he was here, to make it all make sense, to hug her and to look at her with that infinite patience he held for her naivety, and explain how it was all a lie.</p>
		
		<p>&#8220;Delilah, Delilah&#8230;&#8221; Angelica sang. &#8220;Your Lord is an old, old creature. He never lies, but he&#8217;s had long enough to know how to tell a whole truth without giving everything. Wherever do you think he&#8217;s been when he isn&#8217;t home with you?&#8221; She leaned in, that smile strung sweetly on her face. &#8220;He&#8217;s been with us.&#8221; Her smile dropped. &#8220;And now with Celia. It should have been me, you know. I was his last. He lived and died and took no other in my reign. Until you.&#8221;</p>
		
		<p>Angelica shook her head, as if shaking away the tears that threatened in her eyes. &#8220;You would have been safer to share in our suffering, but sweet little lamb, you&#8217;re nothing but food. We are more than you will ever be, child. Look at me. Look!&#8221; Angelica tore at Delilah&#8217;s hair, holding it high so that the woman had no choice but to look. The cold brown of her irises flooded with a bright red like fresh blood, and she opened her mouth in a smile that showed off the glint of fang. &#8220;Look what he did to me, our Lian. My family died a hundred years ago, human.&#8221; She yanked at Delilah&#8217;s hair again before slicing the shears through it.</p>
		
		<p>The scream that escaped Delilah was not a sound. It was a visceral silence that barreled from her gaping mouth as a wildness born of terror was birthed in eyes that were very nearly empty of all else for her inability to accept what she was seeing or hearing. Her mind and her body could not receive it, and she retreated into the safety of the cocoon that the darkness would offer.</p>
		
		<p>Her head fell back again with the release of her hair as it was severed, and it seemed with that first cut, that the last vestiges of Angelica&#8217;s control disappeared. She grabbed wildly, gleefully at the woman&#8217;s dark curls, mangling her hair so that the longest pieces barely reached that pretty neck. Delilah was passive beneath the assault, her expression glazed as if she were no longer a part of the scene, but watching detachedly from a distance. She did not look toward her hair, or reach up to touch the places where her crown had been laid bare. </p>
		
		<p>&#8220;Oh&#8230; Yes&#8230;&#8221; Angelica shuddered a sigh of ecstatic release. The shears dropped to the floor, and the vampiress instead grabbed the binding that held Delilah&#8217;s wrists to drag her to the ground. &#8220;They&#8217;re going to drain you at your throne, your majesty, your court of the lords and ladies of the night. They&#8217;ll take your blood to the last drop, and if you&#8217;re lucky, you&#8217;ll be so lost to the sweetest cloud of ecstasy that you won&#8217;t realize you&#8217;re dying.&#8221; Angelica pulled her across the floor and the rugs. &#8220;And if you are not, you will suffer the entire time. I think a few hours of pain will be a fair price to pay. Victor&#8230; Victor, please help me get her on her throne. They&#8217;ll be getting impatient.&#8221;</p>
		
		<p>Delilah heard Angelica though a fog of silence, safe in the place that her mind had found to hide. She would die, and some part of her welcomed the thought. It would be harder to live with the truth.</p>


	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="24-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter XXIV.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="26-link">Chapter XXVI. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
