<div class="row">
	<div class="col-xs-12">
		<h1>Chapter XXVI.</h1>
		<hr>
		
		<p>Delilah opened her eyes. For long moments, she stared at the wall that she was facing. It was unfamiliar, but she could feel, sense somehow, that she was underground — in the belly of a beast. The stonework was old and bare of any effort to soften it with paint or color. It was black, not because it was painted, but for the patina built up on the rock over generations. There was no daylight that she could see, but there was a flickering waver of light coming from somewhere behind her that she knew to be candle light. Candles, in this modern age of gas lighting. Vaguely, her mind noticed the detail. Under her, the surface that she was laying on had no sheets, she could feel the worn scratchiness of its cover against her feet. It had once been soft, she thought, but no more. Her ankles were sore, and heavy.</p>
		 
		<p>Slowly, like a mariner navigating through a fog, her mind was seeking a course to somewhere, but she didn&#8217;t know yet what that place was. She only knew in her belly a dread and a fascination both for the elusive objective. This wasn&#8217;t where she belonged. Where did she belong? Her eyes trailed down the wall, her mind detached, to the place where it met the side of the surface that she was laying on. In the semi gloom her eyes could only just make out its color. It was red. Delilah rolled over to the opposite side of the bed, lifted herself up weakly onto her elbows, and retched.</p>
		
		<p>&#8220;Well now, my dear. That will not do at all.&#8221;</p>
		
		<p>The voice in the darkness poured over Delilah like oil, and as if it was its own ignition device set her skin on fire. She could feel a flush of desire flood her body with the stab of betrayal and the weight of her heart hammering against her chest. Her lips parted and she found her air coming in short, breathless pants. She curled her fingers against her palms in an effort to control her body. It seemed to have a mind of its own. She could not see him, but she could feel him there in the shadows, studying her as if she were a peculiar specimen worthy of the attention.</p>
		
		<p>&#8220;Better&#8230; much better&#8230;&#8221; The voice seemed amused, almost. &#8220;So responsive for one untrained." There was a pause, &#8220;But a fit welcome for the one who saved your life.&#8221; Finally, he stepped out of the shadows and let the light fall upon his features. They were etched with the beauty of his kind: a pale, flawless perfection framed by hair the color of onyx that fell past his shoulders. His eyes were the pale green of young summer grass, and a startling contrast with everything else about him that seemed to be either black or white, including his dark suit and perfectly folded cravat. &#8220;You present me with an interesting dilemma, Ms. Flowers.&#8221;</p>
		
		<p>Philippe Denard studied the prize that had dropped into his lap. The woman was either going be his greatest triumph and success or his death sentence. He found that he was not averse to either idea. Eternity had all but exhausted its ability to amuse. Even butchered and debauched in the way that only his kind could manage, she was a pinprick of light in his darkness. He could well see why Redmond had desired to hoard her for himself. Philippe could even appreciate the man&#8217;s sentiment in refusing to turn her. There was something about her humanity that was exquisite. It would be criminal to destroy it. Perhaps it had already been destroyed. What was left of her hair lay in uneven chunks about her head, and violet eyes that were too large in the darkness looked at him with a fearful confusion that made him want to reach out and touch her face with an offer of comfort. Almost. But Philippe was a businessman, and the Raven Manor was, in the end, about profits. One didn&#8217;t play with the profits.</p>
		
		<p>Delilah stared at the man staring at her, and it was as if her eyes were seeing into many moments at once. He was here, standing now, and also in another bright place showing himself a beast with fangs to others who cowered before him. And there was another. That image was the reason her flesh had betrayed her for a welcome of the voice she could barely remember. Delilah reached up with the back of her wrist to wipe the tart taste of bile from her lips, and if it were possible the memory of the pleasure the coolness of his lips had given her — both when they had saluted her lips and while he had lingered over her throat. She understood now, that he had bitten her as the others had, but he had waited until they were alone.</p>
		
		<p>Philippe&#8217;s eyes seemed almost to glow for the flash of awareness that leapt up in him, in answer to the recognition that entered her eyes. Good. He needed her to remember. It was not the first time that a subject had been provided for the throne at one of the parties held on his premises, but it was the first time that the elder had seen a near bloodbath erupt at a gathering, over access to the blood of the one seated upon it. Philippe always attended those larger convened gatherings, as host and as a manager, of a sort, to ensure that rules were followed. He had not survived this long in proximity and service to the mortals by becoming a den of murder. Bodies drew attention. However, the convenient nearness of the river meant that evidence could be sunken for the fishes to devour, and Angelica had made it known that the river was the destiny intended for her offering. That had meant there would be an inclination toward a feeding frenzy. She and Victor had remained only long enough to watch the beginning of the festivities, to watch the oldest among them take their rights for first blood, and then had disappeared into the night. No doubt they would be on their way to establish alibis for what was expected to be the death and disappearance of her victim. All would have gone according to plan, except that the pretty offering of a queen on her throne had not been what was expected.</p>
		
		<p>Philippe lowered himself to a seat on the chaise which was the only piece of furniture in the room, and moved the weight of a thick brass chain aside with the toe of his boot. It was connected to a shackle on one of her ankles. He reached out and ran a finger down the column of her throat. &#8220;Your blood&#8230; is exquisite my dear. Intoxicating,&#8221; he murmured. He could feel his need for it tightening his veins again, despite that he had been the last to sample it, directly from her veins not so very long ago. &#8220;It&#8230;&#8221; He paused, searching for the words to express the effect that she had had on him. &#8220;It causes me to feel alive.&#8221; </p>
		
		<p>Feeling existent, was all that remained for the immortals. Existence went on, and on, and they filled it with every possible hedonistic pleasure, because they were searching for, needing, to feel alive again. To feel alive, was to feel the fear of death. It was to know that pleasure could end, that happiness and feeling could end, because someday you would end. It made any pleasure found in that moment, any feeling, any joy, any sorrow, any desperation, any lust, anything, everything, that much more valuable because it was as if it would be the very last moment to experience it again. Delilah&#8217;s gift was her very mortality, and it was addictive for those who no longer remembered what feeling mortal was like. He drew his hand away, reached into his jacket and withdrew gloves of the finest, thin leather and began working them over his fingers.</p>
		
		<p>Delilah could only watch him, warily as a cornered prey. His words made no sense. She did not understand what he was, what Angelica was, what they all had been. What Lian was. Were they dead, if they must be made to feel alive? The thought of Lian was like a slice to the heart of her conscience. She had felt pleasure when this man had bitten her. She had wanted to feel it again when she heard his voice. It confused her. She did not know him, her heart knew Lian. Could Lian make her feel like this? Is this what Angelica thought she had stolen? Delilah&#8217;s emotions were a storm rising within her, and she found that she could not bare to look at her visitor&#8217;s haunting beauty any longer. She turned her back to him, almost as would a child, and laid down with her palms cupped beneath her cheek, staring at the wall.</p>
		
		<p>Philippe smiled, faintly. Somehow, she had retained such innocence. &#8220;I am sure it was not the most pleasant of experiences to have them swarming like so many locusts, and snarling like the uncivilized beasts that they can become.&#8221; His tone was vaguely condescending, &#8220;&#8230; as much as I am sure that they tried to make it worth the sacrifice.&#8221; He reached out and trailed a gloved finger along the back of the length of her silver necklace where it was exposed for her turned back and lack of hair. &#8220;I am afraid I shall have to take this. I apologize if it has sentimental value.&#8221; He reached out and released the clasp, lingering as he reached around her to withdraw it, over the beat of her pulse. Delilah held her breath until his touch was gone, and then her body released some of its tension again. She refused to look at him and so his continued conversation was with her back.</p>
		
		<p>&#8220;It is fortunate for you, Ms. Flowers, that I think with a mind for the future, and not merely of the moment.&#8221; He folded her necklace into a silk handkerchief, and secured it into his pocket. &#8220;They would have bled you dry&#8230; would have wasted the treasure laid at our feet for one moment of gratification when the future could be filled with so many more moments.&#8221; For a moment he seemed almost apologetic. &#8220;I apologize that the alternative was less&#8230; comfortable, for you.&#8221; It had taken a considerable exertion of his seniority, and his leverage as an owner of the Raven to restrain the crowd in their blood lust. Bites had been forbidden. Instead, the golden clamps about her forearms had been put to their secondary use. The teeth that had sunken into her veins there, carried no reward of pleasure, only the numbness of the controlled, slow drip of precious drops of her blood as she had slipped in and out of consciousness throughout the night. He had been aware, the entire time of just how much of her life she was releasing, and had predetermined at what point he would remove and secure his new prize. He had been pleased to note that as little as two drops of her blood, could produce a desired effect. It meant that nearly all of his clientele could be afforded the privilege of her gift, if they were willing to pay for it.</p>
		
		<p>&#8220;You will be in great demand, Ms. Flowers,&#8221; he murmured. &#8220;The word will spread, and they will come from far and wide, to worship at your feet.&#8221; He smiled a smile that she could not see, but it would be heard in his voice. &#8220;You will be a queen, desired and coveted&#8230;&#8221; Not for herself, but for what she carried inside. &#8220;But no one should be asked to provide a service without being paid.&#8221; Now, he made his demand. The pressure of his touch against her shoulder was enough that if she resisted it she would be in discomfort.</p>
		
		<p>Delilah was turned onto her back and he had her eyes staring up at him, wounded and just a little bit defiant. He skimmed a thumb over her lower lip. &#8220;I have decided that I am more than willing to take up that cost.&#8221; Suddenly, more quickly that she could see or react to, he was upon her, his cheek at her ear. His lips traced the angle of her cheek bone and then drifted lower to find the flutter of the vein in her throat. &#8220;Your body remembers, if your mind does not. And soon&#8230; soon you will not want to forget. You will feel, as you make me feel, Ms. Flowers,&#8221; he murmured. &#8220;I give you my word.&#8221; It was all he had left of value, anyway. His hand reached up to cradle her jaw, to support her head and to steady her in a grip that could not be denied.</p>
		
		<p>&#8220;He will come for you&#8230; as he must,&#8221; It was a breath against her skin. Philippe knew that for such a treasure as the one he had found, Lian Redmond would stop at nothing to recover it. &#8220;And so&#8230; if we are to begin this partnership, you and I, we must find a way to survive his coming.&#8221; That might be easier said than done. Philippe was counting on the fact that Lian had not turned the girl, for evidence that he had no interest in her for a bride. If his heart was not invested, if he valued the woman merely as property or his private fountain of life, then it might be possible to negotiate. &#8220;Come&#8230;&#8221; His words were weighted now, with the seductive power and beauty of his kind. &#8220;It time to assuage your fears. It was not so very terrible&#8230; was it?&#8221;</p>
		
		<p>Delilah knew that it had not been, and her body betrayed her now with a shiver of want for the remembering as she tried to turn her head away from having to look at him. It only bared her throat open to his hold. Philippe did not need more of an invitation and immediately he was paying the price that was owed the woman. As the first wave of release crested over her, Delilah thought of Lian.</p>
		
		<p class="text-center">***</p>
		
		<p>There was a lingering sentiment of restless anticipation among the vampires of an age to be awake within the halls of Raven Manor who had gathered in the throne room, and a deathly stillness to the darker, more elegant form standing in the shadow of the oversized window that looked out over the gardens. Word had spread and there were early arrivals for the planned festivities. Philippe had already determined that the girl would not be exposed, but in the darkness below, the steady drip of her life into the collection of vials that he was preparing for the evening, was creating an aromatic cloud in the atmosphere that had increased that sense of expectancy. Philippe had a sample with him now, sealed tight against their already fevered desire. With each moment that had passed in that day, Lord Denard had seemed to grow more watchful, a macabre sort of amusement marking the twist of his lips, waiting.</p>
		
		<p>After the intoxication of their latest revelry, the current fare in the throne room of a common prostitute was beyond unsatisfying and frustration was mounting. The woman secured in the throne was staring listlessly at the gilded ceiling while her current company sampled the almost toxic fare that seeped sluggishly from the veins of her wrists. The blonde vampire turned and spit a splatter of blood over his shoulder. &#8220;What&#8217;s it take to get a decent meal around here?&#8230;&#8221; he hissed. &#8220;Philippe, you must give us the girl. It is what we are paying for.&#8221; His eyes flared red. &#8220;You will call down a war on your head, if you try to keep her from us. We know she lives. We know she is here.&#8221;</p>
		
		<p>A soft, low laugh came from the shadow of the window. &#8220;You are an uncommon sort of fool, Marcus&#8230;&#8221; Philippe turned, his sculpted marble beauty unmasked, and Marcus had instead distorted and gaunt, pale as death features directed his way. &#8220;Foolish enough not to understand that tainted blood will soon enough be the least of your worries.&#8221; His smile was tight, and grim. Ms. Flowers had almost been worth the price that would be paid. Angelica had made what would be his last day of existence well, well worth his while. Just when he had come to that realization he was not certain. Perhaps it had been when Ms. Flowers had shuddered to her climax in his arms under the sway of his gift. </p>
		
		<p>He had realized then, that despite one day only of possessing her, he was willing to kill to keep her. Lian Redmond was coming, and it would not take him long to find her. Those who had gathered in anticipation of their new pleasure, had been summoned to their own demise. At some distance, down the long halls of the manor, a burst of laughter, followed by a scream of terror, drifted down a corridor. It was enough sound to draw a moan from the whore on her throne.</p>
		
		<p>Long before the door to Raven Manor had been pulled open to allow in a flood of afternoon sunlight, Lian Redmond had already made up his mind. There was only one soul within the walls that he could - would - leave alive. How quickly the rest fell would be determined by what state his Delilah was in. He refused, despite the wisdom and knowledge that came with his age, to let himself think that she was anything but alive, if not well.</p>
		
		<p>Two thralls overseeing the door had stepped forward with the usual welcome, but if in that moment they realized what Lian&#8217;s coming meant, they were dead in the next second through the force of Lian&#8217;s mind alone. His silver gaze watched them fall in a spray of blood that covered the red walls, the floor and himself. He put his hands in his pockets, stepping over the headless bodies. He tore through the bodies of the thralls and older vampires occupying the rooms that he passed through with his mind, or with his hands, if one happened to come too close. Bodies, limbs and heads, and the overpowering scent of the blood that he spilled, was all that was left in his wake.</p>
		
		<p>Yet Lian carried himself like the noble gentleman that he presented to the world, despite the growing pattern of slick blood that covered him. Some managed to scream out, other bodies were broken with no time for a cry against the walls, but finally, silence seemed to reign in the manor. For all that Lian&#8217;s face was composure covered in a red mask, he knew he was growing closer.</p>
		
		<p>He could smell her blood, like some hunting hound giving tongue. Delilah, his rose, bled so much that even the massacre could not keep her scent from him. The final door, the entrance to that depraved throne room, exploded inward, and Lian stepped inside. His clawed fingers tore into the hair of a thrall who had remained too close to the door on the Elder&#8217;s entrance. With one quick motion he had dragged the human closer, his opposite finding anchor on the thrall&#8217;s throat. The man was spun inward before the pop and subsequent rip had his body continuing sideways to the floor. Lian&#8217;s hand lowered, and he dropped the head to the floor. He looked forward, but those silver eyes did not seem to see. Another thrall stopped, shuddered and seemed to be ripped apart at the waist, both halves spilling onto the floorboards.</p>
		
		<p>Philippe lifted his gloved hand, and let the silver heart necklace dangle from his fingertips. &#8220;If I die, she dies,&#8221; the vampire did not waste time with chit chat and pleasantries. He knew the power of the Elder he faced. &#8220;And unfortunately, even I don&#8217;t know how it would happen. So it will do you no good to search my mind for the answer.&#8221; It was a bluff. Foolish, perhaps with the scent of the woman&#8217;s blood thick in the air. But Lian could not know what of the torturous resources within these walls had a hold of the woman. Or if he had a thrall or fledgling in attendance to slay her upon command.</p>
		
		<p>&#8220;If my mind sleeps her death will begin. How much do you trust your ability to find her before Death does?&#8221; he waved a dismissive hand. &#8220;I do not care what you do with the rest.&#8221; The place needed a good purge anyway. He raised the vial in his possession to Lian&#8217;s attention. &#8220;Drink? No doubt for you, a familiar blend.&#8221; He removed the seal from the vial, and the deep rich scent of Delilah&#8217;s life force would fill the room like a perfume. &#8220;I am not surprised she is so desired a prize&#8230; I am surprised, however, that you have not seen fit to protect her with your claim.&#8221; He raised the vial and passed it under his nostrils. &#8220;I was beyond tempted.&#8221; To make her his own.</p>
		
		<p>Lian&#8217;s silver gaze pinned Philippe, not even lowering to the necklace he held. The vial exploded in the man&#8217;s hand, spilling blood and glass across the floor. Around them, the room was indeed being purged. Lian had not moved from his place in front of the door, but his position did not keep him from tearing those within apart. The prostitute&#8217;s head was detached from her body, and for the sake of her &#8216;crown&#8217;, it was the latter that slid onto the floor. Others fell apart in halves, or without their heads. Only Phillipe stood unscathed amid the carnage. For him, there was the sensation of a white-hot iron driving its way through his skull. The more who fell around him, the more intense the pain became as his memories were torn into. Lian tore the man&#8217;s mind apart, piece by piece. There were worse things than death.</p>
		
		<p>Philippe&#8217;s face distorted completely, losing whatever vestiges of humanity remained for a mask, and his scream of pain was feral as clawed fingers reached up to his head. What Lian found there would do little to tamp the Elder&#8217;s blazing fury.</p>
		
		<p><em>Delilah was strapped into the golden throne, clothed in a torn underdress and with a blindly glazed over expression on her face. She was the center of attention, mounted on a farcical display in her elevation as the &#8216;queen&#8217; presiding over the debauchery that was happening all around her. A slow seep of blood flowed from various bite marks on both of her arms, and occasionally one of the guests would approach the throne in a mockery of obeisance before licking the savor of her blood from too pale skin. The faces passed by in a blurring flurry of strangers, until one with a familiar face who had until then remained in the background, approached the throne. She was dressed in red, with hair as dark as the night.</em></p>
		
		<p><em>&#8220;My turn&#8230;&#8221; her voice purred, and Angelica sank her fingers into the anchor of a short shag of butchered hair that remained on Delilah&#8217;s crown. &#8220;I should drain you myself, but that would be too kind,&#8221; she snarled. The vampiress&#8217; fangs slid down and it was a penetrating lock into her victim&#8217;s throat that secured her desire. She jerked back as if burned for something in that taste, and hissed, a feral noise that summoned another to her side. </em></p>
		
		<p><em>Golden eyes flashed on a dark-haired fledgeling. &#8220;Enough,&#8221; he said. &#8220;You will carry her scent.&#8221; </em></p>
		
		<p><em>Angelica shoved him away, and turned back to her victim. &#8220;You&#8217;re rather a plain Jane without your hair, aren&#8217;t you pet?&#8221; she all but sang it, running her fingers over Delilah&#8217;s shorn locks almost as a lover would. She reached out and scraped a finger along Delilah&#8217;s throat. &#8220;He was never for you, pet.&#8221; Her nail extended, and pressed slightly, breaking skin. &#8220;I&#8217;ll see you in hell&#8230; Eventually.&#8221;</em></p>
		
		<p><em>She turned to face Phillippe. &#8220;Leave her somewhere the dogs will find her&#8230;&#8221; It was a bitten out directive. &#8220;Or dump her in the river. I don&#8217;t care. I just want her dead.&#8221;</em></p>
		
		<p>In the Raven manor, Philippe was screaming now. &#8220;She&#8217;s as good as dead! Dead! You hear me?" </p>
		
		<p>Lian moved forward, plucking the necklace delicately up to the haven of a curled hand. The silver burned where it pressed against his palm, but if he was aware of the pain, it did not show on the veiled calmness of his expression. As he stood over the other man, he tore the remainder of the man&#8217;s mind, spreading and crushing the pieces until there would be little but fragments of sanity left. Better to be dead than the husk he had left Philippe Denard. Lian had already turned to move on into the belly of Raven Manor where his rose waited.</p>

	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="25-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter XXV.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="27-link">Chapter XXVII. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
