<div class="row">
	<div class="col-xs-12">
		<h1>Chapter XX.</h1>
		<hr>
		
		<p>Raven Manor had always been a place of &#8217;hospitality&#8217; in Easthaven. Likely because its owners over the years and generations had been of the race that took a particular delight in the pleasures and the pains of the night hours. Most who haunted its parlors knew little of the true face of horror that lay beneath the beauty offered by servant thralls. It was they who lured many a victim to its walls in the name of pleasure, only to offer them up as living sacrifices to their masters who were the true lords of greed and pleasure in this place. Most &#8216;guests&#8217; came willingly, and some came as unexpected treats. Angelica had found some solace there. As the winter thawed into a cool spring she had become a fixture amid the softness of mattress and pillows in one of the more ornate rooms of the manor. With every visitation Lian made to the castle and every song he wove with a woman that was not her, Angelica had taken her pleasures and her petty revenge with the mortals who fed their own addictions with her bites.</p>
		
		<p>She had found her favorites among the regulars. Enthralled humans had been expected pets, but there was one, a dark-haired vampire with golden eyes, who had all but laid his heart at her feet. They all made for poor substitutes for Lian. If his kind words and company were meant to make her forget that she had all but been replaced, he had failed miserably for it. There was only one at whose feet she could lay the blame. That bitch. Still in his house and playing dress up and wife while surrendering neither her life nor her future as a penance for the pleasures she was gifted. Angelica inhaled in a shuddering breath to calm herself, lifting her hand to rest it flatly on the naked curve of her stomach. There was nothing to cover her where she lay propped in a recline on the thick mounds of pillows; nothing but the tangle of her raven hair and the ruby choker at her throat. Even the sheets had been kicked to the base of the bed for the sake of the company she shared. Irritated, she bounced her leg where it had folded over its opposing knee, as if punting the little wretch. Damn her to a thousand hells. Groaning, Angelica lifted her palm to press her hand against her brow.</p>
		
		<p>The warmth of a larger, slightly callused hand arrived as if summoned by that huff of frustration. A mindless, drifting stroke petted Angelica&#8217;s belly and lower, over the curve of her hips where her legs had crossed, as if to soothe a ruffled cat. Were it not for the longer, windswept blonde of the hair, a rounder, more youthful cast of expression and a distinct tan to the skin of the man in her bed, it might have been Lian Redmond there, and not Seth Andrews, doorman of the Raven Manor. A rust-colored streak was inked into the paleness of her skin, where the slow seep of blood from the man&#8217;s wrist still smeared, as if from a scratch unhealed; residue from the place that his mistress had so recently fed. Seth&#8217;s body was hot against her, the hardness of muscle and the weight of his unsated arousal, proof that the pleasure she had given him with the suckle of red lips on his wrist was still stirring in his blood. He needed Angelica, he had to have her, and through the haze of his lust, he knew that <em>the woman</em> was getting in the way of that again.</p>
		
		<p>He lowered his head to kiss her breast, lifted high for the rise of her arm, and then her throat, and the coldness of the rubies that glittered there as red as the blood that she had taken from him — the blood that he willingly gave. Seth didn&#8217;t know who <em>the woman</em> was, only that Angelica hated her, and that every time he had done the things that Angelica demanded of him, she had permitted him to come to her like this; to pleasure her with his body, and to receive pleasure from her that was incomparable. He moved his upper body to frame hers, above her waist and across her, as if to stay any attempt to rise and leave him unsatisfied.</p>
		
		<p>No mere woman would ever be able to duplicate the heights to which the dark ones could take him. Male or female, he knew no preference save for the need to stay in that place high above the world, lost in the haze of a pleasure that need never die so long as he could meet their needs. Seth had done things, terrible things, for the sake of their gifts. Angelica had not been the first to make use of his services, but she was now the one who had done so for the longest.</p>

		<p>It was almost five months since she had arrived and finally noticed him holding the door. He did not think she had ever looked at him, or seen him until that night, and she had called for him. Her taking had been almost savage, that first time, so little of what he had craved being offered as if she had withheld her pleasure to punish him. He had found himself unable to restrain his own frustration in answering her denial and had punished her hips that night to steal from her his own brand of pleasure. She had not denied him again and had seemed to find satisfaction in the blind aggression of their contract. Her pleasure for his. And yet she was ever unsatisfied, ever chasing the ghost in the fog. Seth had become her willing accomplice — her arm in the sun that she still could not tolerate.</p>
		
		<p>It had begun with small things. A folded note, empty of words of anything save for the drops of blood that had spread a stain across parchment, deposited into the woman&#8217;s basket at the farmer&#8217;s market. Seth had remained at a distance to assure that she received it, and had taken a certain vicarious pleasure in seeing the hesitant, fear-touched expression that had dawned on the woman&#8217;s face as she had looked about the bustle of the busy market in search of its source. His had been the blade that had shredded newly ordered gowns, and he had been the one to pay for the delivery of the songbirds, limp with twisted necks, boxed up and wrapped with a bow as if a gift and addressed to her name. He knew that much. She was Flowers. It had been a constant, subtle bombardment of harassment that the woman had grown to anticipate and had seemed to accept with resignation. Seth had seen the gradual loss of some of her innocence in her travels beyond the manor walls. Focused, hurried steps accompanied by an alertness to her surroundings that had not been there when he had begun his duty. She had less of smiles and laughter for the traders in the marketplace, and he reported as much to Angelica who had at first been pleased, and then more and more frustrated as the months had gone by and their mischief seemed to bring no change beyond that of mood.</p>
		
		<p>He lowered his head now, between the queen&#8217;s breasts to lip at her chest bone. &#8220;Just tell me what to do,&#8221; his voice was raspy with the desire that raged unchecked in his blood. &#8220;Anything&#8230;&#8221; He slid a hand into the weight of her hair and wrapped it around his fist. &#8220;Just&#8230; don&#8217;t leave me like this.&#8221; She had intoxicated and enthralled him, and he needed to spend himself in her.</p>
		
		<p>&#8220;And if I did&#8230;?&#8221; Her lips parted with the smirk, the scent of his blood still on her breath. &#8220;Leave you like this&#8230;?&#8221; Her words were as sweet as they had always been, dripping with honey and a layer of heat. It was her eyes that were as cold as the rubies on her throat. She lifted a hand cupping his jaw at first gently, before her fingers curved to grip the length of her nails into his skin. Her opposite hand lifted to claim the wrist of the hand that had her hair, and it was a tightening, twisting hold that seized him. The strength in her hand was more than any mortal man, and he released her quickly. &#8220;Wouldn&#8217;t that just be a slow sort of death&#8230;?&#8221; She shoved him from her.</p>
		
		<p>&#8220;You make me sick,&#8221; she murmured, shifting into a sit and swinging her long legs over the edge of the bed. He had her back to him.</p>
		
		<p>There was a certain deadness to Seth&#8217;s eyes as he rolled backward into the bedding. The weight of his arousal was a leaden betrayal. He was sick, and she was his sickness. &#8220;Angelica&#8230; Please.&#8221; Her name, his plea scratched his throat. &#8220;I&#8217;ll kill her. I&#8217;ll finish this, and you&#8217;ll never have to think about her again.&#8221; It was a desperate promise. He shifted, daring to inch closer to the nakedness of her back. &#8220;Today. This morning. I&#8217;ll find a way to do it. Only&#8230; I can&#8217;t&#8230;&#8221; He couldn&#8217;t bear the torment of the pleasure without a release.</p>
		
		<p>&#8220;I can&#8217;t, I can&#8217;t, I can&#8217;t,&#8221; Angelica mocked. &#8220;You, stupid little child. Of course, you can&#8217;t. You&#8217;ve more than proven that bloody much. I should have asked Victor.&#8221; That golden eyed suitor would not have failed so miserably.</p>
		
		<p>He knew that she would not submit to taking him in her body, this time. But there were other ways. The warmth of his chest came up against her back and his breath brushed over her ear. &#8220;I&#8217;ll do it today&#8230;&#8221; He brought an arm around her shoulders and presented his wrist, and the scent of his blood to her face. &#8220;Everything you want will be yours. Just give me what I need.&#8221; There was a ragged urgency to his voice and a shortness of breath. She could bring him to release with the pleasure of her bite alone. She had in the past and he could feel his body reaching out for that peak, just for the memory.</p>
		
		<p>&#8220;Don&#8217;t you dare fail me,&#8221; Angelica warned. She curled her hands beneath his arm as if she meant to take his offering. However, the woman was on him in an instant with a preternatural quickness. A hand on his chest pressed him deeper into the mattress, the other on that bleeding arm as if to keep it pinned and away from her. She straddled over his stomach so that the warmth and dew between her thighs were cruelly near the evidence of his own want. </p>
		
		<p>It was a guttural sound of pleasure that escaped Seth when she claimed him for a mount, their separation part of the torment that was his pleasure. His hands reached reflexively for her hips to anchor her against his body.</p>
		
		<p>&#8220;You mortals are ten a penny,&#8221; she murmured, leaning forward to drag her tongue across along the pulse of his neck, moistening the skin. Her nose tucked beneath the shell of his ear, a nibble of fangs offered against his jaw. &#8220;And I have more coin than that to make sure this handsome little throat of yours is never touched by my kind again.&#8221; That denial of his addiction truly would be a slow death, then. Her hand shifted, fingers splaying against the side of his face to push it against the pillow, further opening his neck to her fangs. &#8220;Swear it,&#8221; she breathed, over the quickening beat beneath her lips. &#8220;Swear she&#8217;ll be dead.&#8221;</p>
		
		<p>&#8220;I swear it&#8230;&#8221; he gasped. &#8220;I swear it. I won&#8217;t fail you.&#8221; Especially not if the cost of failure was to be denied his pleasures.
Her teeth sliced through his wet skin with no resistance, penetrating deep into the flesh of his neck and cutting through the thin veins to release the spill of life on her tongue. She latched onto the wound, that clever little muscle flicking back and forth to keep it from clotting as she suckled from him.</p>
 
	<p>The explosion of pleasure that rocketed through him with her bite was instantaneous. Beneath her, his body bucked into a climax as he dug into the flesh of her hips with a white knuckled grip. His eyes rolled back into his head and his mouth fell open slack as if he were in the throes of a seizure. The guttural sound that was torn from him was almost one of anguish. He had no knowledge of who Angelica was in those moments, or of the seductive beauty of her body, or the power of the twisted, angry song that snaked through her blood as she took in his own.</p>
	 
	<p>He had no knowledge of anything but the delirium of his shuddering climax; and of the fact that Lady Flowers was as good as dead.</p>

	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="19-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter XIX.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="21-link">Chapter XXI. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
