<div class="row">
	<div class="col-xs-12">
		<h1>Chapter XXIII.</h1>
		<hr>
		
		<p>Sixteen queens were gathered in Anowen Castle&#8217;s drawing room, and tonight, it was for a far more special purpose than they had been expecting. The spring rain had begun to fall in earnest, creating a steady patter of a tempo against the stone walls outside. It was accompanied by the rich chords of a cello, played by one bride with a mess of loose, gold curls. It was not the music that had drawn the women, however. It was Dorian&#8217;s arrival with two new men that had stirred the nest. John and Alexander, he said — <em>new brothers.</em> That the room had <em>only</em> erupted into a controlled frenzy was as close to a miracle as could be expected of the coven.</p>
		
		<p>John was clearly the older of the two men, appearing to be in his early thirties and taller and broader than his brothers. His almost rigid posture and stance was a giveaway of his previous career and rank within the British 1st Foot Guards. He had escaped none the worse for his rescue from death&#8217;s door in the infantry hospital, post-surgery for a ball to the lung. His thick, dark brown hair was cropped almost unfashionably close to his crown, and similarly dark brows winged in arcs over gray eyes that held a steady, hawkish intensity and focus to them. A large but perfectly proportioned nose and lips that managed a sensuality despite almost always being set to a tighter, unsmiling expression were framed by chiseled features made perfect by the new lease on life that he had signed up for. He appeared to have little but a polite interest in the bevy of beauties, but that may have been some of Dorian&#8217;s doing for his warning of what was to be expected. The Castilian had not been in error.</p>
		
		<p>Then there was Alexander, smaller by far. He was tall, of course, and broad-chested, but if he was a sculpture, there had not been enough clay packed around an armature clearly meant for a larger build. He had a mess of short, black hair with dark eyes and lips that were perhaps fuller than was the norm for a man. Although none of his features could be individually counted as attractive, they came together in a pleasing composition on his face. He was thin, with long fingers that belonged to an artist; quite literally, in fact. If it had been his beauty that caught Lian&#8217;s attention first, it was his art that had made it linger. He had carried his portfolio and paints with him, and wherever he set up was his home until he was forced to move to another location. His art had not kept him from the streets. Lian had.</p>
		
		<p>They were as beautiful as any vampire, although for their youth they seemed far, far too perfect and too inhuman to pass among the mortals. There was a paleness to both the men and their skin was so smooth that they seemed almost to be living dolls or marble sculptures. It was a beauty suited only to the darkness. Otherwise, the humans might see the telltale glint of fangs that could not yet be hidden.</p>
		
		<p>Even the brides who did not engage beyond polite conversation had crowded them before dispersing to their own corners of the room. Two beauties stolen from the Far East with dark hair and porcelain skin sat on the floor, one tangled in the legs of the other whilst her hair was braided. They alone seemed content to their own company, stealing quiet brushes against one another&#8217;s arms or murmuring softly beneath the sound of the rain.</p>
		
		<p>Eden was ignoring the men too, leaning as far out of the open window as she dared, so that the rain poured over her. Her bare feet kicked slightly where she dangled, so that the petite, ebon-haired woman standing alongside her was distracted from her disguised study of the smaller of the two new males. Raven was kind enough to reach out and wrap a rescuing hold around Eden&#8217;s bare calf, rocking the younger queen back onto the safety of solid ground inside. Satisfied with the success of her mission, the librarian gathered up her skirts and lowered herself into another seat. Her curious blue-eyed stare never did leave Alexander, although she made no effort to approach. That, after all, was for the bolder of the queens.</p>
		 
		<p>They had already expressed their interest in the men. Sophie and Kristiana made for quite the attractive pair, both such experts in their flirtations that poor Alexander had already colored twice, despite his best efforts thus far to present a cooler face. Eva too, for her grandiose personality, seemed to have taken the approach that her efforts at flirting would be more successful if she were louder than the others. Ayla had watched the three queens titillate until Angelica had crossed into the room to take her place at Shar&#8217;s side. Then, Ayla was staring at the two of them. Her quiet study had eventually drawn a hiss of a warning from the older of the two, although Ayla did not care. It was Angelica who had the most of her attention, anyway. For all of the youngest queen&#8217;s boldness from behind Shar&#8217;s skirts, the girl managed to bite her tongue quite a bit when it came to the older queens.</p>
		
		<p>Lian had told Ayla on the day that she had saved his mortal, nearly three weeks before, that it had been Angelica whose visit had brought his irritation on the coven. She had told him then, what she suspected of the man in the market, that he had known what she was and that she thought he was a thrall. She did not make a connection between the young queen and the thrall aloud, and neither did Lian. However, for those weeks after, he had not returned to the coven. If not for Dorian saying it was otherwise, they might have all thought Lian would not attend the meeting he had planned.</p>
		
		<p>Dorian had arrived nearly an hour before with the men, and Lian as of yet was not in sight. The Castilian had been watching the feeding frenzy with something close to amusement on his expression. It had been literally the first time in hundreds of years that he was to be found in a room with his sisters, and not one of them was hovering at his elbow. There was something to be said for brotherhood, to be sure, if it meant peace from the hens.</p>
		
		<p>Joanna was ever one of the last to arrive, only showing her head if Dorian coaxed her from her hole or when Lian&#8217;s song was near. That she drifted in now, meant that the Lord of the Castle had finally arrived. She did not mind that she went unnoticed by most. Most, of course, save one. Dorian&#8217;s dark-eyed gaze tracked Joanna across the room, his smile faint for her near disregard of its occupants, the male ones, especially. It disappeared when she slipped alongside his chair with the boldness to offer a brush of fingers across his shoulders and back as she passed. Joanna walked behind and around his seat, finding another one that was close enough for conversation to lower into. Not for the first time, Dorian cursed the need for their carefulness in the presence of the brides. Everything in him wanted to reach out and capture her hand to bring it to his lips for a kiss that would linger.</p>
		
		<p>&#8220;You did not come for me,&#8221; Joanna murmured as she settled. She lifted her eyes to watch the two new men for a moment before a faint smirk emerged. &#8220;They do not seem so terrible.&#8221; He had already warned her, of course, that in no uncertain terms, John and Alexander could not be trusted. He had not been so forthcoming as to why. Dorian answered her tease with a growl of warning.</p>
		
		<p>&#8220;Looks can be deceiving,&#8221; he muttered, darkly. &#8220;To look at them you&#8217;d think John incapable of a smile and Alex incapable of standing in the wind. You&#8217;d be wrong on both.&#8221; He&#8217;d gotten to know the men during their stay at his residence and had found them companionable, good conversation and inquisitive about what was to be expected in the life that had been foisted upon them; all things that might render them appealing to their sisters, which meant that they were not to be trusted around his chosen.</p>
		
		<p>Dorian cast a glance Joanna&#8217;s way that remained to linger. &#8220;I would have come for you if I could.&#8221;</p>
		
		<p>&#8220;I know.&#8221;</p>
		
		<p>There was a sudden singular focus of the elder&#8217;s attention on her that bordered on predatory, and Dorian had to will himself to look away and relax against the chair. &#8220;It&#8217;s going to be a very interesting evening,&#8221; he murmured, when he finally trusted himself to speak again. To say the least. Everything about their family dynamic was about to change.</p>
		
		<p>The steady ripple of change had already begun in the room. It started with the men. Despite the time to adjust to the presence of the song in their blood, it was still new enough and strong enough that it suddenly took the most of their attention. Eva was the first to detach from them. Alexander, unfortunately, found himself caught by Kristiana, who seemed pleased to herd him to one of the sofas to sit with her. John was not quite so inclined to move, despite Sophie&#8217;s encouragement, and she eventually gave up with a feigned huff. The cellist began to pack up her instrument.</p>
		
		<p>Lian entered, his umbrella tucked under his arm. John and Alexander had his attention, first. &#8220;I am pleased to see that you have both survived so far,&#8221; he observed, dryly. That he was referring to their introduction to his family, would remain unspoken. Of course, he made no apologies for being late. Despite the time that had passed since the attack on Delilah, he had still all but been her shadow, whether it had been in the form of an escort to the market, or within the confines of the manor. It was only with the security of added locks and the caveat that no one should come or go until he had returned, that he had felt comfortable enough to leave.</p>
		
		<p>&#8220;Lian!&#8221; Eden grinned, bounding to throw her arms around Lian as she collided with his chest. &#8220;Lian, I am so happy for brothers.&#8221;</p>
		
		<p>&#8220;Are you?&#8221;</p>
		
		<p>&#8220;Yes, but remember how we talked about certain new sisters too?&#8221;</p>
		
		<p>&#8220;Have you been leaning your head out the window? You are soaked.&#8221;</p>
		
		<p>&#8220;You are changin&#8217; the subject, you ratbag,&#8221; she huffed. Eden released him, and spared a kick of her toes to his shin before turning to head back to her perch.</p>
		
		<p>Lian watched her settle in before moving to his armchair. That was where he was content to sit and wait, watching the coven as they slowly stirred back to quieter conversation. After all, tonight was about far more than just introducing brothers to the family. He could hear Celia. In all of the centuries that they had existed together, it was only in their first giving and taking of blood together that he had realized the power of that two way bond. He could feel her song resonating through him as if he were taking her, in those moments, and he closed his eyes to listen.</p>
		
		<p class="text-center">***</p>

		<p>&#8220;You should have worn a train, mother, like a real bride&#8230;&#8221; The voice that spoke was gentle enough and soft enough that it almost took the power of Celia&#8217;s preternatural hearing to hear it, as she walked just ahead of Nadine down the corridor toward the drawing room. Nadine had been the only one permitted to help Celia dress both her body and her hair, and she had been there to gentle the flutter of nerves and the threat of tears, when they had come, with the magic that she wove on her harp in the queen&#8217;s chambers.</p>
		
		<p>&#8220;Have I not always been a real bride, child? It has been an eternity of misunderstanding if I have not&#8230;&#8221; she teased in answer. But she understood why the one sister she held as close as a daughter had chosen to express her thoughts in that manner. She had not been without thoughts and sleepless nights filled with memories, as she considered the significance of Lian&#8217;s decision and what it would mean for them all. He had chosen her, for his last season. She knew in her heart that hers would be the last temporary season that the Elder would endure. When her time in his sun came to an end, this time, it would be because they were free.</p>
		
		<p>The realization was overwhelming for both the joy of knowing that he was hers, at last, and for the pain of knowing that someday it would end. It might be the mortal who so captivated him now who might be his eternal song, or another after her, if Delilah&#8217;s song failed, but there would be no new brides for a season in Anowen. The ones already within its walls, were about to be set free, and Celia would be his Queen; his only Queen, until the end. Even where she was, at some distance from the room, she felt her song rising in her blood in a sweet, haunting melody that sought out his music in her soul to whisper of her love in the language that only he might hear. She could not believe how much she did, now that she was free to face it without the anguish of betrayal to steal her very breath.</p>
		
		<p>Nadine colored for the elder queen&#8217;s rebuke, the paleness of her skin flushing a visible rose through the diaphanous material of her nearly translucent gown. The golden honey of her hair as it fell in rippling waves nearly to her ankles, served almost as an overdress to the gown and the frail, bird-like beauty of the woman who wore it. If Nadine was not at her harp, she was at Celia&#8217;s side. It had been so almost immediately upon the ending of the fledgling&#8217;s season, and it had not been difficult to discern that she loved the elder queen with a devotion that bordered on worship. That Celia was finally receiving the honor she was due, made this day almost as special for her favored, as it was for her. &#8220;Yes, mother, you have always been a real bride,&#8221; she answered softly. &#8220;But now, he knows.&#8221;</p>
		
		<p>Celia looked down at the golden songbird and smiled, gently. &#8220;Yes, Nadine. Now he knows.&#8221;</p>
		
		<p>The Queen could not have been a starker contrast to her handmaiden if she had orchestrated it. Where Nadine was soft golden tones and flyaway warmth, Celia was a stormy icy boldness in a satin and lace gown of silver and black. The satin underdress that clung to and highlighted the fullness of her hips and breasts also emphasized her trim waist in that lower waistline that she favored, before falling in a flow of material to the floor. Each step caused the shimmering material to flash like lightning, through the sheer overlay of black patterned lace that was studded throughout with pinheads of diamonds to look like stars in the night sky. The low scoop of her collar skimmed the rise of milk-pale breasts, just dipping at her cleavage to frame them in the cup of a heart, and baring the expanse of her throat as a stage for the black onyx and diamond necklace that she wore. </p>
		
		<p>Her hair was almost free, falling in a tumble of silky waves to her waist, but she had made some attempt at restraining it for the beginning of one of her more traditional braids on one side of her crown that had been left to trail off into a flood of waves that beckoned an invitation to free it from its captivity. She alone, knew the symbolism that lay in the offering her hair made to her bond, to liberate it completely. It was swept over one shoulder now as they made the final steps toward the gathering that waited beyond. Celia paused a beat to settle her expression into the serene mask to which her family was accustomed, then stepped into the room with Nadine in her wake.</p>
		
		<p class="text-center">***</p>
		
		<p>Perhaps the women sensed the change in Lian&#8217;s song. It had begun with a gentle rise of strings, over scored by resonant layers of piano. Then, there she was. Lian opened his eyes, and the moment they found her, the rise of a triumphant strumming of guitar strings betrayed how he felt to see her. He unfolded to a stand and extended a hand to invite her to his side. </p>
		
		<p>Celia moved through the mass of songs and bodies that had gathered, with Nadine alongside her, closing the distance between herself and the Elder. If it had never been made clear that Celia was the Queen of the castle, and that it would be in one&#8217;s interest to have her ear and favor, it was going to be established now. Nadine melted away into her surrounding family about halfway through Celia&#8217;s journey, but the silver-haired queen was hardly aware.</p>
		
		<p>When she arrived at the Elder&#8217;s side, it was to offer her hand to his accompanied by a slight smile of assurance. Tonight was bigger than them both. It was a new beginning, a new chapter in an unending story, but they would write it together, as they always had. &#8220;My Lord&#8230;&#8221; The greeting was as much a claim, as it was an offer of her bended knee. She was his to command, until the final hour.</p>
		
		<p>Words were not needed in those moments, not when he had eyes only for his Queen. He lifted her hand to brush a lingering kiss to her knuckles. It seemed a long time that he only held her; even when he lowered her hand, his thumb still skimmed a brush over fingers.</p>
		
		<p>At last, he turned to address the others. &#8220;I can admit to my faults. I sought in each of you what could not be given, what I had already possessed for longer than you have lived and lived again.&#8221; His fingers closed tighter around Celia&#8217;s hand. He could feel her song as clearly as if it were playing in his own blood. &#8220;The blame for the state of our family falls only to my feet,&#8221; he continued. &#8220;I cannot undo what has been done. You have all paid a greater price for an eternity alone, than I should have ever forced onto you. What I can give you now is your freedom. Here is my Queen, and yours.&#8221;</p>
		
		<p>He lifted Celia&#8217;s hand to touch a kiss to the side of her wrist. &#8220;You have my blessing to take bonds amongst yourselves. For now, be gentle with your brothers. There will be more in our family as I can find them. I cannot say that either John or Alexander have given their own eternities to resign themselves to a bond so quickly.&#8221;</p>
		
		<p>For a moment, then two, and then for a what felt like an eternity the women were quiet. The two porcelain beauties on the floor were the first to beam, melting into one another as if it had only been Lian&#8217;s bond of claim that had kept them from their touches and their kisses. Suddenly, there was a promise of songs that they had only heard in fantasy, and of rediscovering with another, the harmonies that had been explored in Lian&#8217;s short seasons, upon the horizon. A few quieter, more reflective pockets dotted the room amid an otherwise sudden flurry of excitement. It included a wave of secondary, more interested looks that were directed the way of all of the men present, Dorian included. Then there were those, like Eden and Ayla who seemed not to care about the news one way or the other.</p>
		
		<p>Angelica&#8217;s expression flattened, and she watched Lian with a quiet fury burning in her eyes. He did not look her way, but she felt him intruding on her song like a father trying to force a child to behave. Her hands lifted, pressing against either side of her head as if by sheer force of will alone she could tune him out. Yet he remained, a treacherous stain on her soul that made her heart and her gut clench. It was all that girl&#8217;s fault. Everything was different, everything was changing, and she did not want to be thrown aside when she had surrendered her eternity to Lian. He could not cast her away. She mattered. She mattered as much as Celia and as much as that mortal. She could not help the trembling of her rage, and finally, she threw herself up into a stand. Wordless, she gathered her skirts and stomped out of the room.</p>
		
		<p>Shar studied the scene that was being orchestrated before her, her gaze trailing after Angelica and knew that it was the end. For all that she had fed her hatred like a seed to be nourished until it could blossom, there had always been a hope, a twisted distortion of a belief that somehow, someway, Lian would be hers again. The news that was welcomed so eagerly by brides too young to have known what eternity without him felt like, for Shar, was like the final bitter blade slicing into her soul.</p>
		 
		<p>There would be no more visits, no more private wars between the sheets, and no more memories of their dark duets to hold onto for a cold comfort, in the times when he was away. Celia would have all that Lian had to give; all that had not been secured and hoarded away for his mortal whore. He had cut them off, left them like so many concubines to fend for themselves over the scraps that he would throw their way. Children, worthy of little more than an in-house opportunity to feed. How could one love, when he had taught them just how shallow a betrayal love was? No. There would be no place for love in Shar&#8217;s heart. She would take her pleasures where she could find them, but none would ever be fooled by the thought that there was love to be found in the icy darkness that Shar&#8217;s heart and soul had become. They could thank the kindnesses of Lord Redmond for that gift.</p>
		
		<p>The queen swept up to her feet. She made no pretense of acknowledging Celia or Lian in the place where they stood, nor did she spare even a glance in the direction of the other women in the room. Brides, no more, children eternally. Fools. They did not know the treasure that had just been stolen from their grasp, and for that, she could almost pity them. But pity was for the weak, and that was one thing Shar had determined not to be. She would show them the mercy that Lian had not granted in putting them out of their misery, in time. The room had Shar&#8217;s back, held ramrod straight for her pride and the brush of chestnut locks against her waist, as the only indicator that she was taking her leave. They would hear from her soon enough.</p>

	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="22-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter III.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="24-link">Chapter V. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
