<div class="row">
	<div class="col-xs-12">
		<h1>Chapter XXIV.</h1>
		<hr>
		
		<p>Celia made it a point to wait until almost all of those gathered in the room had departed before rising from her seat. Only a careful observer would have noticed the slow exhale of breath and the release of a subtle tension that had been holding her frame upright. It could have gone worse than it had, and for Lian&#8217;s sake, she was glad that they had successfully weathered this first of many storms. For some reason, she found the sudden want to retreat from all of it: the theatrics, the drama, and the intensity of the moment. With the approach of the sun, the shadowed comfort of her suite seemed just the respite needed after a long and busy night.</p>
		
		<p>Lian had stood, talking with Dorian and her new brothers in those waning moments. She had not been able to help the drift of her gaze in her bond&#8217;s direction. She did not interrupt him except to say that she was retiring from company. It would not have done to be too clingy or to assume that he would visit her, even if he had just made a formal announcement that she was his Queen. Thus it was, that Celia had more or less successfully set thoughts of Lian to the back of her mind as she sat in the lamp-lit shadows of her suite. She sat before the mirror at her vanity, brushing out the length of her hair. She had changed out of her evening gown and into the nightgown that she intended to rest in.</p>
		
		<p>It was fitted more for comfort than seduction, black silk flowing over her curves, and a bit of black lace fitted empire style under the curve of her breasts, which were covered by pleats of the same silken fabric. The wide strap on one shoulder had slipped off as she angled her head to stroke through silver, and the Queen was content for her own company.</p>
		
		<p>However, it would not be solitary company that she had for long.</p>
		
		<p>His Queen felt the rise of his song before he made his presence known. It was a steady crescendo of blood like violin strings, and a nimble dance over their souls like a pianist&#8217;s fingers over the keys. Lian stood in her doorway. He knew she had felt him and heard him, long before he had lifted a hand to rap his knuckles against her doorframe. It had caused a momentary hitch in her brush stroke as she let the bristles pass through her hair. For a few heartbeats, he seemed content to watch the way her silver tresses shimmered in the oil-light — stars captured in the bristles of her brush. He particularly enjoyed the sight of those strands as they lifted away from the curve of her neck, revealing the rise of her breath and pulse.</p>
		
		<p>Silently, the Elder closed the distance to her seat, and Celia closed her eyes so that she could not see him in the mirror as he approached, testing the deeper awareness that their newly forged bond evoked. It was only the slowly increasing and heavier thud of her heart, that let her know that he was closer with each step that he took.</p>
		
		<p>Suddenly, Lian was not quite sure how to handle her, his neglected Queen, so long-reigning in the shadows. For a moment, he felt almost as he had when he had first seen her in her window. He had only been a boy, then, undeserving; coveting her human life and the heart that had played such beautiful music that it brought life back to his silence.</p>
		
		<p>That had been centuries past. Lord Redmond was no boy, despite that age had not touched his face in all those years. It would be long, cool fingers that brushed her neck, stroking that steady thrum of her pulse.</p>
		
		<p>Celia&#8217;s body and soul had never been this attuned to his, and it stole her breath away, even before his touch. When it finally came, it was as if he had drawn his fingers over a rippling chord on a harp. She felt her gut clench, a short quick intake of breath betraying to her bond that she was under the sway of some new and powerful experience. Was this what it was like to sing to each other? A kiss of minds and souls?</p>
		 
		<p>When he lowered his head to touch lips to her temple, it was as if Lian had poured cool water on her flushed skin, and she shivered, her fingers curling around the handle of her brush. Celia let herself open her eyes, finally, and her gaze found him in the mirror. She set her brush aside and rose gracefully to her feet to face him. She eased one button of his jacket open, then another, and then his undershirt endured the same treatment until he stood bare-chested in front of her. Almost as an experiment, she spread her palm over the flat expanse of his stomach, feeling his song roll over her like a blanket of desire. It floated through her blood, twisting another knot in her core. Her lips parted on an exhale of breath, and her silver-gray eyes dilated slightly in the gloom. &#8220;Lian&#8230;&#8221; It was a muted whisper in the predawn light.</p>
		
		<p>The word on her lips expressed her amazement with the force of the waves that were crashing over her senses. Celia&#8217;s fingers drifted to his side and up his back, passing over each rib like a note on a keyboard, overlaying her own song on his. Her hair spilled free down her back, and she reached her free hand to slide around his neck until he was, for all intents and purposes, her captive in that embrace. The Queen touched her temple to his own, her breath a whisper on the column of his throat. His life was a kiss away, and yet somehow, it was not that which called to her: it was the increasing crescendo of his wordless seduction. It made Celia&#8217;s legs tremble, slightly, and her fingers closed over the strength of his neck for an anchor, as if she would fall. Yet, even as his song was touching and arousing every nerve ending in her body, she remained unaware in the cloud of her rising desire, of how her own soul song had begun to reach out to ensnare him in its own responsive magic.</p>
		
		<p><em>&#8220;Beloved&#8230;&#8221;</em> It was almost a moan on Celia&#8217;s breath, a helpless near apology for his Queen&#8217;s shameless melting at his feet. &#8220;What are you doing to me?&#8221; Her voice was husky with desire. She was heavy with an ache in her womb, and she had not even kissed him yet.</p>
		
		<p>Lian was quiet, exploring the new melodies that he could weave of the notes between them and in their blood. The storm-grey of his eyes was dark in the intensity of his stare, one hand still touching her throat and the other lifting to caress her lips. Beloved. The question. He had been watching her lips move, and now, he turned his attention to her eyes. She held him. His hand slipped lower tracing the sculpted line of her jaw until it had disappeared into the paleness of her hair. He turned his head.</p>
		
		<p>&#8220;Playing,&#8221; he answered. There was a curve of a smile on Lian&#8217;s lips where he touched them to the corner of her eye. Playing, like a maestro conducting an orchestra. He let his fingers skim an exploratory touch along the bare skin of her chest; there was the stroke of the bow across the strings, as smooth as the breath of the sigh that escaped him. His fingerprints found black lace, and drew it aside, curling into her gown as he sought out contact with the smooth coolness of her flesh beneath. He felt the beating of her heart like a drum under her breast, and his own pounding against his ribs to answer and match that rush. He tilted his head so that they were cheek to cheek, then he was plundering and caressing the soft mounds that protected her heart, the way her heart protected him. There rose a surge of strings: cellos and violas and the rich calls of the violins as they sang out in the echo of the rising tide of his desire.</p>
		
		<p>The music quieted again, into a slow, smooth drift of chords, as he let his touch leave her pulse to skim down the curves and dips of Celia&#8217;s frame. It was with an Elder&#8217;s strength that he lifted her against him, then; his arm wrapped around her waist while the other remained shamelessly occupied with the skin it massaged beneath lace.</p>
		
		<p>He stole her deeper into her suite on the swirl of woodwinds, but he did not make it far. His body suddenly warmed against hers. His Queen was a fast learner and his hissed intake of a breath was the evidence that she had found her way to the places in his soul&#8217;s song that no other had yet been. Her song lingered there, making his heart race and stealing his breath. A sound escaped him, punctuating the music of his blood. It was a physical, almost guttural growl from his throat. The only surface close enough was her chaise, plush and velvet. It was her throne, and he lowered her upon it.</p>
		
		<p>&#8220;What are you doing to me?&#8221; He echoed her earlier demand, hoarse with the want that was fiercer than any desire that he had felt in an eternity of lifetimes.</p>

		<p>&#8220;Dancing with you&#8230;&#8221; she gasped her answer, as she reached out, helpless for the want and need for him.</p>
		
		<p>Lian&#8217;s arm surrendered its wrap around her waist to prop himself above her, and his other hand drifted higher to tease the strap of her gown from her shoulder. It fell to a shimmering black pool at her white waist. Now, there was only the fall of silver hair over her shoulders and breasts to keep the beast at bay. But she did not want him at bay.</p>
		
		<p>Celia arched into his caress, the crash of thunder cracking in her soul. When had he become a storm? A whirlwind of savage notes that threatened to sweep her away on a flood. She couldn&#8217;t see him. It was as if light was beginning to fill her mind, her inner sight; a light so blinding that it was as close to the full blazing of the sun as she might ever see again in her life. Her fingers reached up to his bare pectoral, and a suddenly pointed nail drew a line across his flesh, splitting it over his heart to release a swelling line of blood that began to flow over his muscle.</p>
		
		<p>The scent of his own blood and the faint sting in his chest brought Lian&#8217;s senses to a heated peak. He felt her insistence wrestle with his clothes, and the answer of his body even when he had lifted his hand to offer impatient aid. Then the Elder was drowning in her taste, his loosened pants forgotten as he hooked his fingers into her gown to hitch it higher above pale thighs.</p>
		
		<p>The rise of an orchestra crashed into Celia&#8217;s soul, and she could not help a small arc beneath him for the shuddering reaction of her body to the peal of his music overwhelming her senses. One hand reached up to find an anchor against the bulge of bicep that was supporting his weight, and the Queen lifted her head to draw her tongue over the red flow; tasting and soothing with a patiently lingering exploration, almost as if it were his mouth that she explored and not his chest. She finally, finally gave in to that more physical yearning to breathe his breath and began dancing a seductive waltz with his tongue, even as her free hand battled with the obstacle that was his slacks. His song was singing now from within her, for the taste of his life, and she wanted more, needed more. She needed to drink and to feel him resonate within her. She craved them both at once, and her song was a violent, urgent demand for his kiss and his bond, in all the ways that mattered.</p>
		
		<p>Celia&#8217;s fangs slid down in anticipation, and his Queen was a wildling with heat in her silver-eyed gaze. She looked up into his face with something close to a pained plea for satiation. Only he could quiet the raging storm that threatened to hurl her over the cliffs. She lifted her chin to bare her throat and shoulder to his claim.</p>
		
		<p>The Elder had no patience, and a groan escaped his lips. Far too lost in the swell of their song to moisten her skin in preparation, he bent over her, and the warmth of his lips found her throat. Lian&#8217;s teeth sank into her skin, and wave after wave of her beating heart passed into him. The orchestra rose, and he rocked with the layers of crescendo, weightless, devouring her. </p>
		
		<p>His lips were stained with her life when he pulled back, gasping, his mind flooded with the taste of her ecstasy. His hand left her breast, to find the stain that she had left over his heart where it had begun to seal closed. His blood and song were hers, he said, not with words, but with that storm of music that battered her soul. He sank his body into the heart of his Queen, then, a pinch of stinging fang against his own tongue drawing his blood. It mingled with the taste of hers, and then he pressed his lips to her own to invite that taste once more in the mating of tongues that was punctuated by the rhythmic dance their bodies intuitively found. It was hers to take, that which she had spilled first, to reach the climax of their duet.</p>
		
		<p>Celia cried out his name, a hoarse song of ecstasy as his body and his blood became a singular offering. She let him swallow the sounds that chased her first cry, the coppery tangle of their tongues lifting her into the shattering crescendo of their duet. Lian&#8217;s back arched convulsively as he rocked against her, into her, again and again in answer to her call. <em>Celia.</em> Her name was on his lips as he followed her over the edge and into their light. The climax of their song exploded, full and bright as it resonated through the core of their souls, consuming them both in its flame. In that moment, they were one person.</p>
		
		<p>It felt as if they hung there, suspended on eagle&#8217;s wings in the storm for a timeless eternity, before the music began to gentle, drifting like a feather into a floating whimsical plucking of strings that feathered aftershocks along Celia&#8217;s nerve endings. Her hair and breasts were stained with blood, and there was a faint spattering of it on the furnishings. Her gown was a knot of silk at her waist, and her inner thighs were warm and wet where she had wrapped her legs around Lian&#8217;s, hugging him to her body. The Queen tucked her head in against his throat and she rested there, hiding against his body from the violence of their emotions. It had never been like that. She shivered slightly and touched her lips to his shoulder in a tender kiss. She did not speak. How could she when there were no words?</p>
		
		<p>Lian held her, stroking her hair. He was careful of the knots and wounds of their love-making, threading his fingers almost carefully over them. She was a picture of blood on the snow. With eyes closed, he could let those last wooden notes sing their sweet finish through his soul. He nosed a languid kiss into her silver silk, breathing in the musky scent of their duet: the salt and the copper tinge of their life mixed together. His lips lingered there as the minutes ticked by in their eternity. It was a slow rise, once he detached from her, one that had a hand slipping under her back, the other drawing beneath her backside to pull her in with his stand. He carried her, a husband with his bride, crossing that threshold into the depths of her chambers. </p>


	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-xs-6">
	<p><a href="#" class="23-link"><i class="fa fa-caret-left" aria-hidden="true"></i> Chapter XXIII.</a></p>
	</div>
	
	<div class="col-sm-4 col-sm-offset-4 col-xs-6">
	<p><a href="#" class="25-link">Chapter XXV. <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
	</div>		
</div>
